package crs.model.vo;

import crs.model.eo.CrsDocClassImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 27 12:34:35 EEST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CrsDocClassViewRowImpl
  extends ViewRowImpl
{


  public static final int ENTITY_CRSDOCCLASS = 0;

  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    DocClassPk,
    DistributionTypeFk,
    CreatedBy,
    CreationDate,
    ModifiedBy,
    ModifiedDate,
    UserDepartmentFk,
    DisplayDistributionTypeFk,
    DisplayDistributionTypeFkSearch,
    DisplayDocClass,
    DisplayDocClassSearch,
    DistributionTypeFkSearch,
    CrsDocClassCcView,
    CrsDocClassTlView,
    SsoActiveLookupValuesVwView1DistributionTypeFk;
    private static AttributesEnum[] vals = null;
    ;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int DOCCLASSPK = AttributesEnum.DocClassPk.index();
  public static final int DISTRIBUTIONTYPEFK = AttributesEnum.DistributionTypeFk.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
  public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
  public static final int USERDEPARTMENTFK = AttributesEnum.UserDepartmentFk.index();
  public static final int DISPLAYDISTRIBUTIONTYPEFK = AttributesEnum.DisplayDistributionTypeFk.index();
  public static final int DISPLAYDISTRIBUTIONTYPEFKSEARCH = AttributesEnum.DisplayDistributionTypeFkSearch.index();
  public static final int DISPLAYDOCCLASS = AttributesEnum.DisplayDocClass.index();
  public static final int DISPLAYDOCCLASSSEARCH = AttributesEnum.DisplayDocClassSearch.index();
  public static final int DISTRIBUTIONTYPEFKSEARCH = AttributesEnum.DistributionTypeFkSearch.index();
  public static final int CRSDOCCLASSCCVIEW = AttributesEnum.CrsDocClassCcView.index();
  public static final int CRSDOCCLASSTLVIEW = AttributesEnum.CrsDocClassTlView.index();
  public static final int SSOACTIVELOOKUPVALUESVWVIEW1DISTRIBUTIONTYPEFK =
    AttributesEnum.SsoActiveLookupValuesVwView1DistributionTypeFk.index();

  /**
   * This is the default constructor (do not remove).
   */
  public CrsDocClassViewRowImpl()
  {
  }

  /**
   * Gets CrsDocClass entity object.
   * @return the CrsDocClass
   */
  public CrsDocClassImpl getCrsDocClass()
  {
    return (CrsDocClassImpl) getEntity(ENTITY_CRSDOCCLASS);
  }

  /**
   * Gets the attribute value for DOC_CLASS_PK using the alias name DocClassPk.
   * @return the DOC_CLASS_PK
   */
  public BigDecimal getDocClassPk()
  {
    return (BigDecimal) getAttributeInternal(DOCCLASSPK);
  }

  /**
   * Sets <code>value</code> as attribute value for DOC_CLASS_PK using the alias name DocClassPk.
   * @param value value to set the DOC_CLASS_PK
   */
  public void setDocClassPk(BigDecimal value)
  {
    setAttributeInternal(DOCCLASSPK, value);
  }

  /**
   * Gets the attribute value for DISTRIBUTION_TYPE_FK using the alias name DistributionTypeFk.
   * @return the DISTRIBUTION_TYPE_FK
   */
  public BigDecimal getDistributionTypeFk()
  {
    return (BigDecimal) getAttributeInternal(DISTRIBUTIONTYPEFK);
  }

  /**
   * Sets <code>value</code> as attribute value for DISTRIBUTION_TYPE_FK using the alias name DistributionTypeFk.
   * @param value value to set the DISTRIBUTION_TYPE_FK
   */
  public void setDistributionTypeFk(BigDecimal value)
  {
    setAttributeInternal(DISTRIBUTIONTYPEFK, value);
  }

  /**
   * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
   * @return the CREATED_BY
   */
  public BigDecimal getCreatedBy()
  {
    return (BigDecimal) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
   * @param value value to set the CREATED_BY
   */
  public void setCreatedBy(BigDecimal value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
   * @return the CREATION_DATE
   */
  public Timestamp getCreationDate()
  {
    return (Timestamp) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
   * @param value value to set the CREATION_DATE
   */
  public void setCreationDate(Timestamp value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
   * @return the MODIFIED_BY
   */
  public BigDecimal getModifiedBy()
  {
    return (BigDecimal) getAttributeInternal(MODIFIEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy.
   * @param value value to set the MODIFIED_BY
   */
  public void setModifiedBy(BigDecimal value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
   * @return the MODIFIED_DATE
   */
  public Timestamp getModifiedDate()
  {
    return (Timestamp) getAttributeInternal(MODIFIEDDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
   * @param value value to set the MODIFIED_DATE
   */
  public void setModifiedDate(Timestamp value)
  {
    setAttributeInternal(MODIFIEDDATE, value);
  }

  /**
   * Gets the attribute value for USER_DEPARTMENT_FK using the alias name UserDepartmentFk.
   * @return the USER_DEPARTMENT_FK
   */
  public BigDecimal getUserDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(USERDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as attribute value for USER_DEPARTMENT_FK using the alias name UserDepartmentFk.
   * @param value value to set the USER_DEPARTMENT_FK
   */
  public void setUserDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(USERDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDistributionTypeFk.
   * @return the DisplayDistributionTypeFk
   */
  public String getDisplayDistributionTypeFk()
  {
    return (String) getAttributeInternal(DISPLAYDISTRIBUTIONTYPEFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDistributionTypeFk.
   * @param value value to set the  DisplayDistributionTypeFk
   */
  public void setDisplayDistributionTypeFk(String value)
  {
    setAttributeInternal(DISPLAYDISTRIBUTIONTYPEFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDistributionTypeFkSearch.
   * @return the DisplayDistributionTypeFkSearch
   */
  public String getDisplayDistributionTypeFkSearch()
  {
    return (String) getAttributeInternal(DISPLAYDISTRIBUTIONTYPEFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDistributionTypeFkSearch.
   * @param value value to set the  DisplayDistributionTypeFkSearch
   */
  public void setDisplayDistributionTypeFkSearch(String value)
  {
    setAttributeInternal(DISPLAYDISTRIBUTIONTYPEFKSEARCH, value);
  }

  /**
   * Gets the attribute value for DISPLAY_DOC_CLASS using the alias name DisplayDocClass.
   * @return the DISPLAY_DOC_CLASS
   */
  public String getDisplayDocClass()
  {
    return (String) getAttributeInternal(DISPLAYDOCCLASS);
  }

  /**
   * Sets <code>value</code> as attribute value for DISPLAY_DOC_CLASS using the alias name DisplayDocClass.
   * @param value value to set the DISPLAY_DOC_CLASS
   */
  public void setDisplayDocClass(String value)
  {
    setAttributeInternal(DISPLAYDOCCLASS, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDocClassSearch.
   * @return the DisplayDocClassSearch
   */
  public String getDisplayDocClassSearch()
  {
    return (String) getAttributeInternal(DISPLAYDOCCLASS);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDocClassSearch.
   * @param value value to set the  DisplayDocClassSearch
   */
  public void setDisplayDocClassSearch(String value)
  {
    setAttributeInternal(DISPLAYDOCCLASSSEARCH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DistributionTypeFkSearch.
   * @return the DistributionTypeFkSearch
   */
  public BigDecimal getDistributionTypeFkSearch()
  {
    return (BigDecimal) getAttributeInternal(DISTRIBUTIONTYPEFK);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link CrsDocClassCcView.
   */
  public RowIterator getCrsDocClassCcView()
  {
    return (RowIterator) getAttributeInternal(CRSDOCCLASSCCVIEW);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link CrsDocClassTlView.
   */
  public RowIterator getCrsDocClassTlView()
  {
    return (RowIterator) getAttributeInternal(CRSDOCCLASSTLVIEW);
  }

  /**
   * Gets the view accessor <code>RowSet</code> SsoActiveLookupValuesVwView1DistributionTypeFk.
   */
  public RowSet getSsoActiveLookupValuesVwView1DistributionTypeFk()
  {
    return (RowSet) getAttributeInternal(SSOACTIVELOOKUPVALUESVWVIEW1DISTRIBUTIONTYPEFK);
  }
}

