package crs.model.vo;

import crs.model.eo.CrsDocClassCcImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 30 15:40:37 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CrsDocClassCcViewRowImpl
  extends ViewRowImpl
{


  public static final int ENTITY_CRSDOCCLASSCC = 0;

  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    DocClassCcPk,
    DocClassFk,
    DepartmentsFk,
    ActionFk,
    CreatedBy,
    CreationDate,
    ModifiedBy,
    ModifiedDate,
    UserDepartmentFk,
    DisplayDocClassFkSearch,
    DisplayDepartmentsFk,
    DisplayDepartmentsFkSearch,
    DisplayActionFk,
    DisplayActionFkSearch,
    DisplayNotes,
    DisplayNotesSearch,
    ActionFkSearch,
    DepartmentsFkSearch,
    CrsDocClassCcTlView,
    HcmDepartmentsVwView1,
    SsoActiveLookupValuesVwView,
    DeparmentsRVO;
    private static AttributesEnum[] vals = null;
    ;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int DOCCLASSCCPK = AttributesEnum.DocClassCcPk.index();
  public static final int DOCCLASSFK = AttributesEnum.DocClassFk.index();
  public static final int DEPARTMENTSFK = AttributesEnum.DepartmentsFk.index();
  public static final int ACTIONFK = AttributesEnum.ActionFk.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
  public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
  public static final int USERDEPARTMENTFK = AttributesEnum.UserDepartmentFk.index();
  public static final int DISPLAYDOCCLASSFKSEARCH = AttributesEnum.DisplayDocClassFkSearch.index();
  public static final int DISPLAYDEPARTMENTSFK = AttributesEnum.DisplayDepartmentsFk.index();
  public static final int DISPLAYDEPARTMENTSFKSEARCH = AttributesEnum.DisplayDepartmentsFkSearch.index();
  public static final int DISPLAYACTIONFK = AttributesEnum.DisplayActionFk.index();
  public static final int DISPLAYACTIONFKSEARCH = AttributesEnum.DisplayActionFkSearch.index();
  public static final int DISPLAYNOTES = AttributesEnum.DisplayNotes.index();
  public static final int DISPLAYNOTESSEARCH = AttributesEnum.DisplayNotesSearch.index();
  public static final int ACTIONFKSEARCH = AttributesEnum.ActionFkSearch.index();
  public static final int DEPARTMENTSFKSEARCH = AttributesEnum.DepartmentsFkSearch.index();
  public static final int CRSDOCCLASSCCTLVIEW = AttributesEnum.CrsDocClassCcTlView.index();
  public static final int HCMDEPARTMENTSVWVIEW1 = AttributesEnum.HcmDepartmentsVwView1.index();
  public static final int SSOACTIVELOOKUPVALUESVWVIEW = AttributesEnum.SsoActiveLookupValuesVwView.index();
  public static final int DEPARMENTSRVO = AttributesEnum.DeparmentsRVO.index();

  /**
   * This is the default constructor (do not remove).
   */
  public CrsDocClassCcViewRowImpl()
  {
  }

  /**
   * Gets CrsDocClassCc entity object.
   * @return the CrsDocClassCc
   */
  public CrsDocClassCcImpl getCrsDocClassCc()
  {
    return (CrsDocClassCcImpl) getEntity(ENTITY_CRSDOCCLASSCC);
  }

  /**
   * Gets the attribute value for DOC_CLASS_CC_PK using the alias name DocClassCcPk.
   * @return the DOC_CLASS_CC_PK
   */
  public BigDecimal getDocClassCcPk()
  {
    return (BigDecimal) getAttributeInternal(DOCCLASSCCPK);
  }

  /**
   * Sets <code>value</code> as attribute value for DOC_CLASS_CC_PK using the alias name DocClassCcPk.
   * @param value value to set the DOC_CLASS_CC_PK
   */
  public void setDocClassCcPk(BigDecimal value)
  {
    setAttributeInternal(DOCCLASSCCPK, value);
  }

  /**
   * Gets the attribute value for DOC_CLASS_FK using the alias name DocClassFk.
   * @return the DOC_CLASS_FK
   */
  public BigDecimal getDocClassFk()
  {
    return (BigDecimal) getAttributeInternal(DOCCLASSFK);
  }

  /**
   * Sets <code>value</code> as attribute value for DOC_CLASS_FK using the alias name DocClassFk.
   * @param value value to set the DOC_CLASS_FK
   */
  public void setDocClassFk(BigDecimal value)
  {
    setAttributeInternal(DOCCLASSFK, value);
  }

  /**
   * Gets the attribute value for DEPARTMENTS_FK using the alias name DepartmentsFk.
   * @return the DEPARTMENTS_FK
   */
  public BigDecimal getDepartmentsFk()
  {
    return (BigDecimal) getAttributeInternal(DEPARTMENTSFK);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPARTMENTS_FK using the alias name DepartmentsFk.
   * @param value value to set the DEPARTMENTS_FK
   */
  public void setDepartmentsFk(BigDecimal value)
  {
    setAttributeInternal(DEPARTMENTSFK, value);
  }

  /**
   * Gets the attribute value for ACTION_FK using the alias name ActionFk.
   * @return the ACTION_FK
   */
  public BigDecimal getActionFk()
  {
    return (BigDecimal) getAttributeInternal(ACTIONFK);
  }

  /**
   * Sets <code>value</code> as attribute value for ACTION_FK using the alias name ActionFk.
   * @param value value to set the ACTION_FK
   */
  public void setActionFk(BigDecimal value)
  {
    setAttributeInternal(ACTIONFK, value);
  }

  /**
   * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
   * @return the CREATED_BY
   */
  public BigDecimal getCreatedBy()
  {
    return (BigDecimal) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
   * @param value value to set the CREATED_BY
   */
  public void setCreatedBy(BigDecimal value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
   * @return the CREATION_DATE
   */
  public Timestamp getCreationDate()
  {
    return (Timestamp) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
   * @param value value to set the CREATION_DATE
   */
  public void setCreationDate(Timestamp value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
   * @return the MODIFIED_BY
   */
  public BigDecimal getModifiedBy()
  {
    return (BigDecimal) getAttributeInternal(MODIFIEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy.
   * @param value value to set the MODIFIED_BY
   */
  public void setModifiedBy(BigDecimal value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
   * @return the MODIFIED_DATE
   */
  public Timestamp getModifiedDate()
  {
    return (Timestamp) getAttributeInternal(MODIFIEDDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
   * @param value value to set the MODIFIED_DATE
   */
  public void setModifiedDate(Timestamp value)
  {
    setAttributeInternal(MODIFIEDDATE, value);
  }

  /**
   * Gets the attribute value for USER_DEPARTMENT_FK using the alias name UserDepartmentFk.
   * @return the USER_DEPARTMENT_FK
   */
  public BigDecimal getUserDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(USERDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as attribute value for USER_DEPARTMENT_FK using the alias name UserDepartmentFk.
   * @param value value to set the USER_DEPARTMENT_FK
   */
  public void setUserDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(USERDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDocClassFkSearch.
   * @return the DisplayDocClassFkSearch
   */
  public String getDisplayDocClassFkSearch()
  {
    return (String) getAttributeInternal(DISPLAYDOCCLASSFKSEARCH);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDocClassFkSearch.
   * @param value value to set the  DisplayDocClassFkSearch
   */
  public void setDisplayDocClassFkSearch(String value)
  {
    setAttributeInternal(DISPLAYDOCCLASSFKSEARCH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDepartmentsFk.
   * @return the DisplayDepartmentsFk
   */
  public String getDisplayDepartmentsFk()
  {
    return (String) getAttributeInternal(DISPLAYDEPARTMENTSFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDepartmentsFk.
   * @param value value to set the  DisplayDepartmentsFk
   */
  public void setDisplayDepartmentsFk(String value)
  {
    setAttributeInternal(DISPLAYDEPARTMENTSFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDepartmentsFkSearch.
   * @return the DisplayDepartmentsFkSearch
   */
  public String getDisplayDepartmentsFkSearch()
  {
    return (String) getAttributeInternal(DISPLAYDEPARTMENTSFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDepartmentsFkSearch.
   * @param value value to set the  DisplayDepartmentsFkSearch
   */
  public void setDisplayDepartmentsFkSearch(String value)
  {
    setAttributeInternal(DISPLAYDEPARTMENTSFKSEARCH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayActionFk.
   * @return the DisplayActionFk
   */
  public String getDisplayActionFk()
  {
    return (String) getAttributeInternal(DISPLAYACTIONFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayActionFk.
   * @param value value to set the  DisplayActionFk
   */
  public void setDisplayActionFk(String value)
  {
    setAttributeInternal(DISPLAYACTIONFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayActionFkSearch.
   * @return the DisplayActionFkSearch
   */
  public String getDisplayActionFkSearch()
  {
    return (String) getAttributeInternal(DISPLAYACTIONFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayActionFkSearch.
   * @param value value to set the  DisplayActionFkSearch
   */
  public void setDisplayActionFkSearch(String value)
  {
    setAttributeInternal(DISPLAYACTIONFKSEARCH, value);
  }

  /**
   * Gets the attribute value for DISPLAY_NOTES using the alias name DisplayNotes.
   * @return the DISPLAY_NOTES
   */
  public String getDisplayNotes()
  {
    return (String) getAttributeInternal(DISPLAYNOTES);
  }

  /**
   * Sets <code>value</code> as attribute value for DISPLAY_NOTES using the alias name DisplayNotes.
   * @param value value to set the DISPLAY_NOTES
   */
  public void setDisplayNotes(String value)
  {
    setAttributeInternal(DISPLAYNOTES, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayNotesSearch.
   * @return the DisplayNotesSearch
   */
  public String getDisplayNotesSearch()
  {
    return (String) getAttributeInternal(DISPLAYNOTES);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayNotesSearch.
   * @param value value to set the  DisplayNotesSearch
   */
  public void setDisplayNotesSearch(String value)
  {
    setAttributeInternal(DISPLAYNOTESSEARCH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute ActionFkSearch.
   * @return the ActionFkSearch
   */
  public BigDecimal getActionFkSearch()
  {
    return (BigDecimal) getAttributeInternal(ACTIONFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute ActionFkSearch.
   * @param value value to set the  ActionFkSearch
   */
  public void setActionFkSearch(BigDecimal value)
  {
    setAttributeInternal(ACTIONFKSEARCH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DepartmentsFkSearch.
   * @return the DepartmentsFkSearch
   */
  public BigDecimal getDepartmentsFkSearch()
  {
    return (BigDecimal) getAttributeInternal(DEPARTMENTSFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DepartmentsFkSearch.
   * @param value value to set the  DepartmentsFkSearch
   */
  public void setDepartmentsFkSearch(BigDecimal value)
  {
    setAttributeInternal(DEPARTMENTSFKSEARCH, value);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link CrsDocClassCcTlView.
   */
  public RowIterator getCrsDocClassCcTlView()
  {
    return (RowIterator) getAttributeInternal(CRSDOCCLASSCCTLVIEW);
  }

  /**
   * Gets the view accessor <code>RowSet</code> HcmDepartmentsVwView1.
   */
  public RowSet getHcmDepartmentsVwView1()
  {
    return (RowSet) getAttributeInternal(HCMDEPARTMENTSVWVIEW1);
  }

  /**
   * Gets the view accessor <code>RowSet</code> SsoActiveLookupValuesVwView.
   */
  public RowSet getSsoActiveLookupValuesVwView()
  {
    return (RowSet) getAttributeInternal(SSOACTIVELOOKUPVALUESVWVIEW);
  }

  /**
   * Gets the view accessor <code>RowSet</code> DeparmentsRVO.
   */
  public RowSet getDeparmentsRVO()
  {
    return (RowSet) getAttributeInternal(DEPARMENTSRVO);
  }
}

