package crs.model.vo;

import crs.model.eo.CrsIncomingBeneficiariesImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 25 13:00:02 EEST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CrsIncomingBeneficiariesViewRowImpl
  extends ViewRowImpl
{


  public static final int ENTITY_CRSINCOMINGBENEFICIARIES = 0;

  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    IncomingBeneficiariesPk,
    BeneficiariesFk,
    IncomingDocumentsFk,
    CreatedBy,
    CreationDate,
    ModifiedBy,
    ModifiedDate,
    UserDepartmentFk,
    DisplayBeneficiariesFk,
    DisplayBeneficiarieBeneficiaryId,
    DisplayBeneficiarieEmail,
    DisplayBeneficiarieMobileNo,
    BeneficiariesFkSearch,
    DisplayBeneficiariesFkSearch,
    CrsBeneficiariesBeneficiariesFk,
    CrsIncomingDocumentsIncomingDocumentsFk;
    private static AttributesEnum[] vals = null;
    ;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int INCOMINGBENEFICIARIESPK = AttributesEnum.IncomingBeneficiariesPk.index();
  public static final int BENEFICIARIESFK = AttributesEnum.BeneficiariesFk.index();
  public static final int INCOMINGDOCUMENTSFK = AttributesEnum.IncomingDocumentsFk.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
  public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
  public static final int USERDEPARTMENTFK = AttributesEnum.UserDepartmentFk.index();
  public static final int DISPLAYBENEFICIARIESFK = AttributesEnum.DisplayBeneficiariesFk.index();
  public static final int DISPLAYBENEFICIARIEBENEFICIARYID = AttributesEnum.DisplayBeneficiarieBeneficiaryId.index();
  public static final int DISPLAYBENEFICIARIEEMAIL = AttributesEnum.DisplayBeneficiarieEmail.index();
  public static final int DISPLAYBENEFICIARIEMOBILENO = AttributesEnum.DisplayBeneficiarieMobileNo.index();
  public static final int BENEFICIARIESFKSEARCH = AttributesEnum.BeneficiariesFkSearch.index();
  public static final int DISPLAYBENEFICIARIESFKSEARCH = AttributesEnum.DisplayBeneficiariesFkSearch.index();
  public static final int CRSBENEFICIARIESBENEFICIARIESFK = AttributesEnum.CrsBeneficiariesBeneficiariesFk.index();
  public static final int CRSINCOMINGDOCUMENTSINCOMINGDOCUMENTSFK =
    AttributesEnum.CrsIncomingDocumentsIncomingDocumentsFk.index();

  /**
   * This is the default constructor (do not remove).
   */
  public CrsIncomingBeneficiariesViewRowImpl()
  {
  }

  /**
   * Gets CrsIncomingBeneficiaries entity object.
   * @return the CrsIncomingBeneficiaries
   */
  public CrsIncomingBeneficiariesImpl getCrsIncomingBeneficiaries()
  {
    return (CrsIncomingBeneficiariesImpl) getEntity(ENTITY_CRSINCOMINGBENEFICIARIES);
  }

  /**
   * Gets the attribute value for INCOMING_BENEFICIARIES_PK using the alias name IncomingBeneficiariesPk.
   * @return the INCOMING_BENEFICIARIES_PK
   */
  public BigDecimal getIncomingBeneficiariesPk()
  {
    return (BigDecimal) getAttributeInternal(INCOMINGBENEFICIARIESPK);
  }

  /**
   * Sets <code>value</code> as attribute value for INCOMING_BENEFICIARIES_PK using the alias name IncomingBeneficiariesPk.
   * @param value value to set the INCOMING_BENEFICIARIES_PK
   */
  public void setIncomingBeneficiariesPk(BigDecimal value)
  {
    setAttributeInternal(INCOMINGBENEFICIARIESPK, value);
  }

  /**
   * Gets the attribute value for BENEFICIARIES_FK using the alias name BeneficiariesFk.
   * @return the BENEFICIARIES_FK
   */
  public BigDecimal getBeneficiariesFk()
  {
    return (BigDecimal) getAttributeInternal(BENEFICIARIESFK);
  }

  /**
   * Sets <code>value</code> as attribute value for BENEFICIARIES_FK using the alias name BeneficiariesFk.
   * @param value value to set the BENEFICIARIES_FK
   */
  public void setBeneficiariesFk(BigDecimal value)
  {
    setAttributeInternal(BENEFICIARIESFK, value);
  }

  /**
   * Gets the attribute value for INCOMING_DOCUMENTS_FK using the alias name IncomingDocumentsFk.
   * @return the INCOMING_DOCUMENTS_FK
   */
  public BigDecimal getIncomingDocumentsFk()
  {
    return (BigDecimal) getAttributeInternal(INCOMINGDOCUMENTSFK);
  }

  /**
   * Sets <code>value</code> as attribute value for INCOMING_DOCUMENTS_FK using the alias name IncomingDocumentsFk.
   * @param value value to set the INCOMING_DOCUMENTS_FK
   */
  public void setIncomingDocumentsFk(BigDecimal value)
  {
    setAttributeInternal(INCOMINGDOCUMENTSFK, value);
  }

  /**
   * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
   * @return the CREATED_BY
   */
  public BigDecimal getCreatedBy()
  {
    return (BigDecimal) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
   * @param value value to set the CREATED_BY
   */
  public void setCreatedBy(BigDecimal value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
   * @return the CREATION_DATE
   */
  public Timestamp getCreationDate()
  {
    return (Timestamp) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
   * @param value value to set the CREATION_DATE
   */
  public void setCreationDate(Timestamp value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
   * @return the MODIFIED_BY
   */
  public BigDecimal getModifiedBy()
  {
    return (BigDecimal) getAttributeInternal(MODIFIEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy.
   * @param value value to set the MODIFIED_BY
   */
  public void setModifiedBy(BigDecimal value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
   * @return the MODIFIED_DATE
   */
  public Timestamp getModifiedDate()
  {
    return (Timestamp) getAttributeInternal(MODIFIEDDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
   * @param value value to set the MODIFIED_DATE
   */
  public void setModifiedDate(Timestamp value)
  {
    setAttributeInternal(MODIFIEDDATE, value);
  }

  /**
   * Gets the attribute value for USER_DEPARTMENT_FK using the alias name UserDepartmentFk.
   * @return the USER_DEPARTMENT_FK
   */
  public BigDecimal getUserDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(USERDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as attribute value for USER_DEPARTMENT_FK using the alias name UserDepartmentFk.
   * @param value value to set the USER_DEPARTMENT_FK
   */
  public void setUserDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(USERDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayBeneficiariesFk.
   * @return the DisplayBeneficiariesFk
   */
  public String getDisplayBeneficiariesFk()
  {
    return (String) getAttributeInternal(DISPLAYBENEFICIARIESFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayBeneficiariesFk.
   * @param value value to set the  DisplayBeneficiariesFk
   */
  public void setDisplayBeneficiariesFk(String value)
  {
    setAttributeInternal(DISPLAYBENEFICIARIESFK, value);
  }


  /**
   * Gets the attribute value for the calculated attribute DisplayBeneficiarieBeneficiaryId.
   * @return the DisplayBeneficiarieBeneficiaryId
   */
  public String getDisplayBeneficiarieBeneficiaryId()
  {
    return (String) getAttributeInternal(DISPLAYBENEFICIARIEBENEFICIARYID);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayBeneficiarieBeneficiaryId.
   * @param value value to set the  DisplayBeneficiarieBeneficiaryId
   */
  public void setDisplayBeneficiarieBeneficiaryId(String value)
  {
    setAttributeInternal(DISPLAYBENEFICIARIEBENEFICIARYID, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayBeneficiarieEmail.
   * @return the DisplayBeneficiarieEmail
   */
  public String getDisplayBeneficiarieEmail()
  {
    return (String) getAttributeInternal(DISPLAYBENEFICIARIEEMAIL);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayBeneficiarieEmail.
   * @param value value to set the  DisplayBeneficiarieEmail
   */
  public void setDisplayBeneficiarieEmail(String value)
  {
    setAttributeInternal(DISPLAYBENEFICIARIEEMAIL, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayBeneficiarieMobileNo.
   * @return the DisplayBeneficiarieMobileNo
   */
  public String getDisplayBeneficiarieMobileNo()
  {
    return (String) getAttributeInternal(DISPLAYBENEFICIARIEMOBILENO);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayBeneficiarieMobileNo.
   * @param value value to set the  DisplayBeneficiarieMobileNo
   */
  public void setDisplayBeneficiarieMobileNo(String value)
  {
    setAttributeInternal(DISPLAYBENEFICIARIEMOBILENO, value);
  }


    /**
     * Gets the attribute value for the calculated attribute BeneficiariesFkSearch.
     * @return the BeneficiariesFkSearch
     */
  public BigDecimal getBeneficiariesFkSearch()
  {
    return (BigDecimal) getAttributeInternal(BENEFICIARIESFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute BeneficiariesFkSearch.
   * @param value value to set the  BeneficiariesFkSearch
   */
  public void setBeneficiariesFkSearch(BigDecimal value)
  {
    setAttributeInternal(BENEFICIARIESFKSEARCH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayBeneficiariesFkSearch.
   * @return the DisplayBeneficiariesFkSearch
   */
  public String getDisplayBeneficiariesFkSearch()
  {
    return (String) getAttributeInternal(DISPLAYBENEFICIARIESFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayBeneficiariesFkSearch.
   * @param value value to set the  DisplayBeneficiariesFkSearch
   */
  public void setDisplayBeneficiariesFkSearch(String value)
  {
    setAttributeInternal(DISPLAYBENEFICIARIESFKSEARCH, value);
  }


  /**
   * Gets the view accessor <code>RowSet</code> CrsBeneficiariesBeneficiariesFk.
   */
  public RowSet getCrsBeneficiariesBeneficiariesFk()
  {
    return (RowSet) getAttributeInternal(CRSBENEFICIARIESBENEFICIARIESFK);
  }

  /**
   * Gets the view accessor <code>RowSet</code> CrsIncomingDocumentsIncomingDocumentsFk.
   */
  public RowSet getCrsIncomingDocumentsIncomingDocumentsFk()
  {
    return (RowSet) getAttributeInternal(CRSINCOMINGDOCUMENTSINCOMINGDOCUMENTSFK);
  }
}

