package crs.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 05 11:21:45 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CrsIncomingDocumentsViewImpl
  extends ViewObjectImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public CrsIncomingDocumentsViewImpl()
  {
  }

  /**
   * Returns the bind variable value for p_lang.
   * @return bind variable value for p_lang
   */
  public Integer getp_lang()
  {
    return (Integer) getNamedWhereClauseParam("p_lang");
  }

  /**
   * Sets <code>value</code> for bind variable p_lang.
   * @param value value to bind as p_lang
   */
  public void setp_lang(Integer value)
  {
    setNamedWhereClauseParam("p_lang", value);
  }
}

