package crs.model.vo;

import crs.model.eo.CrsIncomingRelatedLettersImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 27 17:57:33 EEST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CrsIncomingRelatedLettersViewRowImpl extends ViewRowImpl
{


  public static final int ENTITY_CRSINCOMINGRELATEDLETTERS = 0;

  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
    protected enum AttributesEnum {
    IncomingRelatedLettersPk,
    IncomingDocumentsFk,
    RelatedIncomingDocumentFk,
    CreatedBy,
    CreationDate,
    ModifiedBy,
    ModifiedDate,
    UserDepartmentFk,
    RelatedOutgoingDocumentsFk,
    RelatedDocumentTypeFk,
    DisplayRelatedIncomingDocumentFk,
    DisplayRelatedIncomingOutgoingDocumentFk,
    DisplayDocDateG,
    DisplayDocDateH,
    RelatedOutgoingDocumentsFkSearch,
    RelatedDocumentTypeFkSearch,
    DisplayRelatedIncomingOutgoingDocumentFkSearch,
    DisplayDocNo,
    RelatedIncomingDocumentFkSearch,
    CrsIncomingDocumentsRelatedIncomingDocumentFk,
    CrsIncomingDocumentsIncomingDocumentsFk,
    CrsOutgoingDocumentsRelatedOutgoingDocumentsFk,
    SsoSystemLookupValuesRelatedDocumentTypeFk;
    private static AttributesEnum[] vals = null;
    ;
    private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


  public static final int INCOMINGRELATEDLETTERSPK = AttributesEnum.IncomingRelatedLettersPk.index();
  public static final int INCOMINGDOCUMENTSFK = AttributesEnum.IncomingDocumentsFk.index();
  public static final int RELATEDINCOMINGDOCUMENTFK = AttributesEnum.RelatedIncomingDocumentFk.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
  public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
  public static final int USERDEPARTMENTFK = AttributesEnum.UserDepartmentFk.index();
  public static final int RELATEDOUTGOINGDOCUMENTSFK = AttributesEnum.RelatedOutgoingDocumentsFk.index();
  public static final int RELATEDDOCUMENTTYPEFK = AttributesEnum.RelatedDocumentTypeFk.index();
  public static final int DISPLAYRELATEDINCOMINGDOCUMENTFK = AttributesEnum.DisplayRelatedIncomingDocumentFk.index();
  public static final int DISPLAYRELATEDINCOMINGOUTGOINGDOCUMENTFK =
    AttributesEnum.DisplayRelatedIncomingOutgoingDocumentFk.index();
  public static final int DISPLAYDOCDATEG = AttributesEnum.DisplayDocDateG.index();
  public static final int DISPLAYDOCDATEH = AttributesEnum.DisplayDocDateH.index();
  public static final int RELATEDOUTGOINGDOCUMENTSFKSEARCH = AttributesEnum.RelatedOutgoingDocumentsFkSearch.index();
  public static final int RELATEDDOCUMENTTYPEFKSEARCH = AttributesEnum.RelatedDocumentTypeFkSearch.index();
  public static final int DISPLAYRELATEDINCOMINGOUTGOINGDOCUMENTFKSEARCH =
    AttributesEnum.DisplayRelatedIncomingOutgoingDocumentFkSearch.index();
  public static final int DISPLAYDOCNO = AttributesEnum.DisplayDocNo.index();
  public static final int RELATEDINCOMINGDOCUMENTFKSEARCH = AttributesEnum.RelatedIncomingDocumentFkSearch.index();
  public static final int CRSINCOMINGDOCUMENTSRELATEDINCOMINGDOCUMENTFK =
    AttributesEnum.CrsIncomingDocumentsRelatedIncomingDocumentFk.index();
  public static final int CRSINCOMINGDOCUMENTSINCOMINGDOCUMENTSFK =
    AttributesEnum.CrsIncomingDocumentsIncomingDocumentsFk.index();
  public static final int CRSOUTGOINGDOCUMENTSRELATEDOUTGOINGDOCUMENTSFK =
    AttributesEnum.CrsOutgoingDocumentsRelatedOutgoingDocumentsFk.index();
  public static final int SSOSYSTEMLOOKUPVALUESRELATEDDOCUMENTTYPEFK =
    AttributesEnum.SsoSystemLookupValuesRelatedDocumentTypeFk.index();

  /**
   * This is the default constructor (do not remove).
   */
    public CrsIncomingRelatedLettersViewRowImpl() {
    }

    /**
     * Gets CrsIncomingRelatedLetters entity object.
     * @return the CrsIncomingRelatedLetters
     */
    public CrsIncomingRelatedLettersImpl getCrsIncomingRelatedLetters() {
        return (CrsIncomingRelatedLettersImpl) getEntity(ENTITY_CRSINCOMINGRELATEDLETTERS);
    }

    /**
     * Gets the attribute value for INCOMING_RELATED_LETTERS_PK using the alias name IncomingRelatedLettersPk.
     * @return the INCOMING_RELATED_LETTERS_PK
     */
    public BigDecimal getIncomingRelatedLettersPk() {
        return (BigDecimal) getAttributeInternal(INCOMINGRELATEDLETTERSPK);
    }

    /**
     * Sets <code>value</code> as attribute value for INCOMING_RELATED_LETTERS_PK using the alias name IncomingRelatedLettersPk.
     * @param value value to set the INCOMING_RELATED_LETTERS_PK
     */
    public void setIncomingRelatedLettersPk(BigDecimal value) {
        setAttributeInternal(INCOMINGRELATEDLETTERSPK, value);
    }

    /**
     * Gets the attribute value for INCOMING_DOCUMENTS_FK using the alias name IncomingDocumentsFk.
     * @return the INCOMING_DOCUMENTS_FK
     */
    public BigDecimal getIncomingDocumentsFk() {
        return (BigDecimal) getAttributeInternal(INCOMINGDOCUMENTSFK);
    }

    /**
     * Sets <code>value</code> as attribute value for INCOMING_DOCUMENTS_FK using the alias name IncomingDocumentsFk.
     * @param value value to set the INCOMING_DOCUMENTS_FK
     */
    public void setIncomingDocumentsFk(BigDecimal value) {
        setAttributeInternal(INCOMINGDOCUMENTSFK, value);
    }

    /**
     * Gets the attribute value for RELATED_INCOMING_DOCUMENT_FK using the alias name RelatedIncomingDocumentFk.
     * @return the RELATED_INCOMING_DOCUMENT_FK
     */
    public BigDecimal getRelatedIncomingDocumentFk() {
        return (BigDecimal) getAttributeInternal(RELATEDINCOMINGDOCUMENTFK);
    }

    /**
     * Sets <code>value</code> as attribute value for RELATED_INCOMING_DOCUMENT_FK using the alias name RelatedIncomingDocumentFk.
     * @param value value to set the RELATED_INCOMING_DOCUMENT_FK
     */
    public void setRelatedIncomingDocumentFk(BigDecimal value) {
        setAttributeInternal(RELATEDINCOMINGDOCUMENTFK, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public BigDecimal getCreatedBy() {
        return (BigDecimal) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @return the MODIFIED_BY
     */
    public BigDecimal getModifiedBy() {
        return (BigDecimal) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @param value value to set the MODIFIED_BY
     */
    public void setModifiedBy(BigDecimal value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Timestamp getModifiedDate() {
        return (Timestamp) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Timestamp value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for USER_DEPARTMENT_FK using the alias name UserDepartmentFk.
     * @return the USER_DEPARTMENT_FK
     */
    public BigDecimal getUserDepartmentFk() {
        return (BigDecimal) getAttributeInternal(USERDEPARTMENTFK);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_DEPARTMENT_FK using the alias name UserDepartmentFk.
     * @param value value to set the USER_DEPARTMENT_FK
     */
    public void setUserDepartmentFk(BigDecimal value) {
        setAttributeInternal(USERDEPARTMENTFK, value);
    }

    /**
     * Gets the attribute value for RELATED_OUTGOING_DOCUMENTS_FK using the alias name RelatedOutgoingDocumentsFk.
     * @return the RELATED_OUTGOING_DOCUMENTS_FK
     */
    public BigDecimal getRelatedOutgoingDocumentsFk() {
        return (BigDecimal) getAttributeInternal(RELATEDOUTGOINGDOCUMENTSFK);
    }

    /**
     * Sets <code>value</code> as attribute value for RELATED_OUTGOING_DOCUMENTS_FK using the alias name RelatedOutgoingDocumentsFk.
     * @param value value to set the RELATED_OUTGOING_DOCUMENTS_FK
     */
    public void setRelatedOutgoingDocumentsFk(BigDecimal value) {
        setAttributeInternal(RELATEDOUTGOINGDOCUMENTSFK, value);
    }

    /**
     * Gets the attribute value for RELATED_DOCUMENT_TYPE_FK using the alias name RelatedDocumentTypeFk.
     * @return the RELATED_DOCUMENT_TYPE_FK
     */
    public BigDecimal getRelatedDocumentTypeFk() {
        return (BigDecimal) getAttributeInternal(RELATEDDOCUMENTTYPEFK);
    }

    /**
     * Sets <code>value</code> as attribute value for RELATED_DOCUMENT_TYPE_FK using the alias name RelatedDocumentTypeFk.
     * @param value value to set the RELATED_DOCUMENT_TYPE_FK
     */
    public void setRelatedDocumentTypeFk(BigDecimal value) {
        setAttributeInternal(RELATEDDOCUMENTTYPEFK, value);
    }

  /**
   * Gets the attribute value for the calculated attribute DisplayRelatedIncomingDocumentFk.
   * @return the DisplayRelatedIncomingDocumentFk
   */
  public String getDisplayRelatedIncomingDocumentFk()
  {
    return (String) getAttributeInternal(DISPLAYRELATEDINCOMINGDOCUMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayRelatedIncomingDocumentFk.
   * @param value value to set the  DisplayRelatedIncomingDocumentFk
   */
  public void setDisplayRelatedIncomingDocumentFk(String value)
  {
    setAttributeInternal(DISPLAYRELATEDINCOMINGDOCUMENTFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayRelatedIncomingDocumentFk.
   * @return the DisplayRelatedIncomingDocumentFk
   */
    public String getDisplayRelatedIncomingOutgoingDocumentFk() {
        return (String) getAttributeInternal(DISPLAYRELATEDINCOMINGOUTGOINGDOCUMENTFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DisplayRelatedIncomingDocumentFk.
     * @param value value to set the  DisplayRelatedIncomingDocumentFk
     */
    public void setDisplayRelatedIncomingOutgoingDocumentFk(String value) {
        setAttributeInternal(DISPLAYRELATEDINCOMINGOUTGOINGDOCUMENTFK, value);
    }


  /**
   * Gets the attribute value for the calculated attribute DisplayInDocDateG.
   * @return the DisplayInDocDateG
   */
    public Timestamp getDisplayDocDateG() {
        return (Timestamp) getAttributeInternal(DISPLAYDOCDATEG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DisplayInDocDateG.
     * @param value value to set the  DisplayInDocDateG
     */
    public void setDisplayDocDateG(Timestamp value) {
        setAttributeInternal(DISPLAYDOCDATEG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DisplayInDocDateH.
     * @return the DisplayInDocDateH
     */
    public BigDecimal getDisplayDocDateH() {
        return (BigDecimal) getAttributeInternal(DISPLAYDOCDATEH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DisplayInDocDateH.
     * @param value value to set the  DisplayInDocDateH
     */
    public void setDisplayDocDateH(BigDecimal value) {
        setAttributeInternal(DISPLAYDOCDATEH, value);
    }


  /**
   * Gets the attribute value for the calculated attribute RelatedOutgoingDocumentsFkSearch.
   * @return the RelatedOutgoingDocumentsFkSearch
   */
    public BigDecimal getRelatedOutgoingDocumentsFkSearch() {
        return (BigDecimal) getAttributeInternal(RELATEDOUTGOINGDOCUMENTSFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RelatedOutgoingDocumentsFkSearch.
     * @param value value to set the  RelatedOutgoingDocumentsFkSearch
     */
    public void setRelatedOutgoingDocumentsFkSearch(BigDecimal value) {
        setAttributeInternal(RELATEDOUTGOINGDOCUMENTSFKSEARCH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RelatedDocumentTypeFkSearch.
     * @return the RelatedDocumentTypeFkSearch
     */
    public BigDecimal getRelatedDocumentTypeFkSearch() {
        return (BigDecimal) getAttributeInternal(RELATEDDOCUMENTTYPEFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RelatedDocumentTypeFkSearch.
     * @param value value to set the  RelatedDocumentTypeFkSearch
     */
    public void setRelatedDocumentTypeFkSearch(BigDecimal value) {
        setAttributeInternal(RELATEDDOCUMENTTYPEFKSEARCH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DisplayRelatedIncomingDocumentFkSearch.
     * @return the DisplayRelatedIncomingDocumentFkSearch
     */
    public String getDisplayRelatedIncomingOutgoingDocumentFkSearch() {
        return (String) getAttributeInternal(DISPLAYRELATEDINCOMINGOUTGOINGDOCUMENTFK);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DisplayRelatedIncomingDocumentFkSearch.
     * @param value value to set the  DisplayRelatedIncomingDocumentFkSearch
     */
    public void setDisplayRelatedIncomingOutgoingDocumentFkSearch(String value) {
        setAttributeInternal(DISPLAYRELATEDINCOMINGOUTGOINGDOCUMENTFKSEARCH, value);
    }


  /**
   * Gets the attribute value for the calculated attribute DisplayInDocNo.
   * @return the DisplayInDocNo
   */
  public String getDisplayDocNo()
  {
    return (String) getAttributeInternal(DISPLAYDOCNO);
  }


  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDocNo.
   * @param value value to set the  DisplayDocNo
   */
  public void setDisplayDocNo(String value)
  {
    setAttributeInternal(DISPLAYDOCNO, value);
  }


  /**
   * Gets the attribute value for the calculated attribute RelatedIncomingDocumentFkSearch.
   * @return the RelatedIncomingDocumentFkSearch
   */
  public BigDecimal getRelatedIncomingDocumentFkSearch()
  {
    return (BigDecimal) getAttributeInternal(RELATEDINCOMINGDOCUMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute RelatedIncomingDocumentFkSearch.
   * @param value value to set the  RelatedIncomingDocumentFkSearch
   */
  public void setRelatedIncomingDocumentFkSearch(BigDecimal value)
  {
    setAttributeInternal(RELATEDINCOMINGDOCUMENTFKSEARCH, value);
  }

  /**
   * Gets the view accessor <code>RowSet</code> CrsIncomingDocumentsRelatedIncomingDocumentFk.
   */
    public RowSet getCrsIncomingDocumentsRelatedIncomingDocumentFk() {
        return (RowSet) getAttributeInternal(CRSINCOMINGDOCUMENTSRELATEDINCOMINGDOCUMENTFK);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CrsIncomingDocumentsIncomingDocumentsFk.
     */
    public RowSet getCrsIncomingDocumentsIncomingDocumentsFk() {
        return (RowSet) getAttributeInternal(CRSINCOMINGDOCUMENTSINCOMINGDOCUMENTSFK);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CrsOutgoingDocumentsRelatedOutgoingDocumentsFk.
     */
    public RowSet getCrsOutgoingDocumentsRelatedOutgoingDocumentsFk() {
        return (RowSet) getAttributeInternal(CRSOUTGOINGDOCUMENTSRELATEDOUTGOINGDOCUMENTSFK);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SsoSystemLookupValuesRelatedDocumentTypeFk.
     */
    public RowSet getSsoSystemLookupValuesRelatedDocumentTypeFk() {
        return (RowSet) getAttributeInternal(SSOSYSTEMLOOKUPVALUESRELATEDDOCUMENTTYPEFK);
    }
}

