package crs.model.vo;

import crs.model.eo.HcmDepartmentsImpl;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 26 17:17:14 GMT+03:00 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HcmDepartmentsViewRowImpl
  extends ViewRowImpl
{


  public static final int ENTITY_HCMDEPARTMENTS = 0;

  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    DepartmentsPk,
    AdminParentFk,
    DeptStatusFl,
    CreatedBy,
    CreationDate,
    ModifiedBy,
    ModifiedDate,
    UserDepartmentFk,
    DeptTypeFk,
    DeptLevelFk,
    DeptCatFk,
    DeptExternalFl,
    DeptManagerFk,
    DeptSubManagerFk,
    DeptOrgCode,
    DeptGovCode,
    DeptPhoneNo,
    GeoParentFk,
    FinParentFk,
    InvParentFk,
    MainParentFk,
    RegionParentFk,
    DeptCityFk,
    TrafficCode,
    DeptLongitude,
    DeptLatitude,
    BudgetFl,
    DeptFax,
    DeptOrder,
    VacationFl,
    VacationPercent,
    DeptIban,
    DeptBankFk,
    DeptSecurityFk,
    DeptMilitaryRegionFk,
    DeptItemFk,
    DeptCode,
    DeptClassFk,
    DeptCountryFk,
    Division,
    MainFl,
    MilitaryFl,
    MainInvFl,
    DeptItem,
    NumberingDependencyFk,
    DisplayAdminParentFk,
    DisplayDepartmentsPk,
    DisplayAdminParentFkSearch,
    DisplayDepartmentsPkSearch,
    DisplayNumberingDependencyFk,
    DisplayNumberingDependencyFkSearch,
    NumberingDependencyFkSearch,
    CrsOutgoingDocPreparationView,
    CrsOutgoingDocPreparationView1,
    CrsDeptGroupDeptsView,
    CrsAllowedSendDepartmentsView,
    CrsAllowedSendDepartmentsView1,
    HcmDepartmentsView,
    HcmDepartmentsView1,
    HcmDepartmentsView2,
    HcmDepartmentsView3,
    HcmDepartmentsView4,
    HcmDepartmentsView5,
    CrsFilesLocationView,
    CrsDocClassCcView,
    CrsOutgoingDocCcView,
    CrsIncomingDocumentsView,
    CrsIncomingDocumentsView1,
    CrsOutgoingDocumentsView,
    CrsOutgoingDocumentsView1,
    CrsLetterTemplatesView,
    CrsIncomingDocCcView,
    CrsAllowedSendTypesView,
    DeparmentsRVO;
    private static AttributesEnum[] vals = null;
    ;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int DEPARTMENTSPK = AttributesEnum.DepartmentsPk.index();
  public static final int ADMINPARENTFK = AttributesEnum.AdminParentFk.index();
  public static final int DEPTSTATUSFL = AttributesEnum.DeptStatusFl.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
  public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
  public static final int USERDEPARTMENTFK = AttributesEnum.UserDepartmentFk.index();
  public static final int DEPTTYPEFK = AttributesEnum.DeptTypeFk.index();
  public static final int DEPTLEVELFK = AttributesEnum.DeptLevelFk.index();
  public static final int DEPTCATFK = AttributesEnum.DeptCatFk.index();
  public static final int DEPTEXTERNALFL = AttributesEnum.DeptExternalFl.index();
  public static final int DEPTMANAGERFK = AttributesEnum.DeptManagerFk.index();
  public static final int DEPTSUBMANAGERFK = AttributesEnum.DeptSubManagerFk.index();
  public static final int DEPTORGCODE = AttributesEnum.DeptOrgCode.index();
  public static final int DEPTGOVCODE = AttributesEnum.DeptGovCode.index();
  public static final int DEPTPHONENO = AttributesEnum.DeptPhoneNo.index();
  public static final int GEOPARENTFK = AttributesEnum.GeoParentFk.index();
  public static final int FINPARENTFK = AttributesEnum.FinParentFk.index();
  public static final int INVPARENTFK = AttributesEnum.InvParentFk.index();
  public static final int MAINPARENTFK = AttributesEnum.MainParentFk.index();
  public static final int REGIONPARENTFK = AttributesEnum.RegionParentFk.index();
  public static final int DEPTCITYFK = AttributesEnum.DeptCityFk.index();
  public static final int TRAFFICCODE = AttributesEnum.TrafficCode.index();
  public static final int DEPTLONGITUDE = AttributesEnum.DeptLongitude.index();
  public static final int DEPTLATITUDE = AttributesEnum.DeptLatitude.index();
  public static final int BUDGETFL = AttributesEnum.BudgetFl.index();
  public static final int DEPTFAX = AttributesEnum.DeptFax.index();
  public static final int DEPTORDER = AttributesEnum.DeptOrder.index();
  public static final int VACATIONFL = AttributesEnum.VacationFl.index();
  public static final int VACATIONPERCENT = AttributesEnum.VacationPercent.index();
  public static final int DEPTIBAN = AttributesEnum.DeptIban.index();
  public static final int DEPTBANKFK = AttributesEnum.DeptBankFk.index();
  public static final int DEPTSECURITYFK = AttributesEnum.DeptSecurityFk.index();
  public static final int DEPTMILITARYREGIONFK = AttributesEnum.DeptMilitaryRegionFk.index();
  public static final int DEPTITEMFK = AttributesEnum.DeptItemFk.index();
  public static final int DEPTCODE = AttributesEnum.DeptCode.index();
  public static final int DEPTCLASSFK = AttributesEnum.DeptClassFk.index();
  public static final int DEPTCOUNTRYFK = AttributesEnum.DeptCountryFk.index();
  public static final int DIVISION = AttributesEnum.Division.index();
  public static final int MAINFL = AttributesEnum.MainFl.index();
  public static final int MILITARYFL = AttributesEnum.MilitaryFl.index();
  public static final int MAININVFL = AttributesEnum.MainInvFl.index();
  public static final int DEPTITEM = AttributesEnum.DeptItem.index();
  public static final int NUMBERINGDEPENDENCYFK = AttributesEnum.NumberingDependencyFk.index();
  public static final int DISPLAYADMINPARENTFK = AttributesEnum.DisplayAdminParentFk.index();
  public static final int DISPLAYDEPARTMENTSPK = AttributesEnum.DisplayDepartmentsPk.index();
  public static final int DISPLAYADMINPARENTFKSEARCH = AttributesEnum.DisplayAdminParentFkSearch.index();
  public static final int DISPLAYDEPARTMENTSPKSEARCH = AttributesEnum.DisplayDepartmentsPkSearch.index();
  public static final int DISPLAYNUMBERINGDEPENDENCYFK = AttributesEnum.DisplayNumberingDependencyFk.index();
  public static final int DISPLAYNUMBERINGDEPENDENCYFKSEARCH =
    AttributesEnum.DisplayNumberingDependencyFkSearch.index();
  public static final int NUMBERINGDEPENDENCYFKSEARCH = AttributesEnum.NumberingDependencyFkSearch.index();
  public static final int CRSOUTGOINGDOCPREPARATIONVIEW = AttributesEnum.CrsOutgoingDocPreparationView.index();
  public static final int CRSOUTGOINGDOCPREPARATIONVIEW1 = AttributesEnum.CrsOutgoingDocPreparationView1.index();
  public static final int CRSDEPTGROUPDEPTSVIEW = AttributesEnum.CrsDeptGroupDeptsView.index();
  public static final int CRSALLOWEDSENDDEPARTMENTSVIEW = AttributesEnum.CrsAllowedSendDepartmentsView.index();
  public static final int CRSALLOWEDSENDDEPARTMENTSVIEW1 = AttributesEnum.CrsAllowedSendDepartmentsView1.index();
  public static final int HCMDEPARTMENTSVIEW = AttributesEnum.HcmDepartmentsView.index();
  public static final int HCMDEPARTMENTSVIEW1 = AttributesEnum.HcmDepartmentsView1.index();
  public static final int HCMDEPARTMENTSVIEW2 = AttributesEnum.HcmDepartmentsView2.index();
  public static final int HCMDEPARTMENTSVIEW3 = AttributesEnum.HcmDepartmentsView3.index();
  public static final int HCMDEPARTMENTSVIEW4 = AttributesEnum.HcmDepartmentsView4.index();
  public static final int HCMDEPARTMENTSVIEW5 = AttributesEnum.HcmDepartmentsView5.index();
  public static final int CRSFILESLOCATIONVIEW = AttributesEnum.CrsFilesLocationView.index();
  public static final int CRSDOCCLASSCCVIEW = AttributesEnum.CrsDocClassCcView.index();
  public static final int CRSOUTGOINGDOCCCVIEW = AttributesEnum.CrsOutgoingDocCcView.index();
  public static final int CRSINCOMINGDOCUMENTSVIEW = AttributesEnum.CrsIncomingDocumentsView.index();
  public static final int CRSINCOMINGDOCUMENTSVIEW1 = AttributesEnum.CrsIncomingDocumentsView1.index();
  public static final int CRSOUTGOINGDOCUMENTSVIEW = AttributesEnum.CrsOutgoingDocumentsView.index();
  public static final int CRSOUTGOINGDOCUMENTSVIEW1 = AttributesEnum.CrsOutgoingDocumentsView1.index();
  public static final int CRSLETTERTEMPLATESVIEW = AttributesEnum.CrsLetterTemplatesView.index();
  public static final int CRSINCOMINGDOCCCVIEW = AttributesEnum.CrsIncomingDocCcView.index();
  public static final int CRSALLOWEDSENDTYPESVIEW = AttributesEnum.CrsAllowedSendTypesView.index();
  public static final int DEPARMENTSRVO = AttributesEnum.DeparmentsRVO.index();

  /**
   * This is the default constructor (do not remove).
   */
  public HcmDepartmentsViewRowImpl()
  {
  }

  /**
   * Gets HcmDepartments entity object.
   * @return the HcmDepartments
   */
  public HcmDepartmentsImpl getHcmDepartments()
  {
    return (HcmDepartmentsImpl) getEntity(ENTITY_HCMDEPARTMENTS);
  }

  /**
   * Gets the attribute value for DEPARTMENTS_PK using the alias name DepartmentsPk.
   * @return the DEPARTMENTS_PK
   */
  public BigDecimal getDepartmentsPk()
  {
    return (BigDecimal) getAttributeInternal(DEPARTMENTSPK);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPARTMENTS_PK using the alias name DepartmentsPk.
   * @param value value to set the DEPARTMENTS_PK
   */
  public void setDepartmentsPk(BigDecimal value)
  {
    setAttributeInternal(DEPARTMENTSPK, value);
  }

  /**
   * Gets the attribute value for ADMIN_PARENT_FK using the alias name AdminParentFk.
   * @return the ADMIN_PARENT_FK
   */
  public BigDecimal getAdminParentFk()
  {
    return (BigDecimal) getAttributeInternal(ADMINPARENTFK);
  }

  /**
   * Sets <code>value</code> as attribute value for ADMIN_PARENT_FK using the alias name AdminParentFk.
   * @param value value to set the ADMIN_PARENT_FK
   */
  public void setAdminParentFk(BigDecimal value)
  {
    setAttributeInternal(ADMINPARENTFK, value);
  }

  /**
   * Gets the attribute value for DEPT_STATUS_FL using the alias name DeptStatusFl.
   * @return the DEPT_STATUS_FL
   */
  public BigDecimal getDeptStatusFl()
  {
    return (BigDecimal) getAttributeInternal(DEPTSTATUSFL);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPT_STATUS_FL using the alias name DeptStatusFl.
   * @param value value to set the DEPT_STATUS_FL
   */
  public void setDeptStatusFl(BigDecimal value)
  {
    setAttributeInternal(DEPTSTATUSFL, value);
  }

  /**
   * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
   * @return the CREATED_BY
   */
  public BigDecimal getCreatedBy()
  {
    return (BigDecimal) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
   * @param value value to set the CREATED_BY
   */
  public void setCreatedBy(BigDecimal value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
   * @return the CREATION_DATE
   */
  public Date getCreationDate()
  {
    return (Date) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
   * @param value value to set the CREATION_DATE
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
   * @return the MODIFIED_BY
   */
  public BigDecimal getModifiedBy()
  {
    return (BigDecimal) getAttributeInternal(MODIFIEDBY);
  }

  /**
   * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy.
   * @param value value to set the MODIFIED_BY
   */
  public void setModifiedBy(BigDecimal value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
   * @return the MODIFIED_DATE
   */
  public Date getModifiedDate()
  {
    return (Date) getAttributeInternal(MODIFIEDDATE);
  }

  /**
   * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
   * @param value value to set the MODIFIED_DATE
   */
  public void setModifiedDate(Date value)
  {
    setAttributeInternal(MODIFIEDDATE, value);
  }

  /**
   * Gets the attribute value for USER_DEPARTMENT_FK using the alias name UserDepartmentFk.
   * @return the USER_DEPARTMENT_FK
   */
  public BigDecimal getUserDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(USERDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as attribute value for USER_DEPARTMENT_FK using the alias name UserDepartmentFk.
   * @param value value to set the USER_DEPARTMENT_FK
   */
  public void setUserDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(USERDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for DEPT_TYPE_FK using the alias name DeptTypeFk.
   * @return the DEPT_TYPE_FK
   */
  public BigDecimal getDeptTypeFk()
  {
    return (BigDecimal) getAttributeInternal(DEPTTYPEFK);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPT_TYPE_FK using the alias name DeptTypeFk.
   * @param value value to set the DEPT_TYPE_FK
   */
  public void setDeptTypeFk(BigDecimal value)
  {
    setAttributeInternal(DEPTTYPEFK, value);
  }

  /**
   * Gets the attribute value for DEPT_LEVEL_FK using the alias name DeptLevelFk.
   * @return the DEPT_LEVEL_FK
   */
  public BigDecimal getDeptLevelFk()
  {
    return (BigDecimal) getAttributeInternal(DEPTLEVELFK);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPT_LEVEL_FK using the alias name DeptLevelFk.
   * @param value value to set the DEPT_LEVEL_FK
   */
  public void setDeptLevelFk(BigDecimal value)
  {
    setAttributeInternal(DEPTLEVELFK, value);
  }

  /**
   * Gets the attribute value for DEPT_CAT_FK using the alias name DeptCatFk.
   * @return the DEPT_CAT_FK
   */
  public BigDecimal getDeptCatFk()
  {
    return (BigDecimal) getAttributeInternal(DEPTCATFK);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPT_CAT_FK using the alias name DeptCatFk.
   * @param value value to set the DEPT_CAT_FK
   */
  public void setDeptCatFk(BigDecimal value)
  {
    setAttributeInternal(DEPTCATFK, value);
  }

  /**
   * Gets the attribute value for DEPT_EXTERNAL_FL using the alias name DeptExternalFl.
   * @return the DEPT_EXTERNAL_FL
   */
  public BigDecimal getDeptExternalFl()
  {
    return (BigDecimal) getAttributeInternal(DEPTEXTERNALFL);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPT_EXTERNAL_FL using the alias name DeptExternalFl.
   * @param value value to set the DEPT_EXTERNAL_FL
   */
  public void setDeptExternalFl(BigDecimal value)
  {
    setAttributeInternal(DEPTEXTERNALFL, value);
  }

  /**
   * Gets the attribute value for DEPT_MANAGER_FK using the alias name DeptManagerFk.
   * @return the DEPT_MANAGER_FK
   */
  public BigDecimal getDeptManagerFk()
  {
    return (BigDecimal) getAttributeInternal(DEPTMANAGERFK);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPT_MANAGER_FK using the alias name DeptManagerFk.
   * @param value value to set the DEPT_MANAGER_FK
   */
  public void setDeptManagerFk(BigDecimal value)
  {
    setAttributeInternal(DEPTMANAGERFK, value);
  }

  /**
   * Gets the attribute value for DEPT_SUB_MANAGER_FK using the alias name DeptSubManagerFk.
   * @return the DEPT_SUB_MANAGER_FK
   */
  public BigDecimal getDeptSubManagerFk()
  {
    return (BigDecimal) getAttributeInternal(DEPTSUBMANAGERFK);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPT_SUB_MANAGER_FK using the alias name DeptSubManagerFk.
   * @param value value to set the DEPT_SUB_MANAGER_FK
   */
  public void setDeptSubManagerFk(BigDecimal value)
  {
    setAttributeInternal(DEPTSUBMANAGERFK, value);
  }

  /**
   * Gets the attribute value for DEPT_ORG_CODE using the alias name DeptOrgCode.
   * @return the DEPT_ORG_CODE
   */
  public String getDeptOrgCode()
  {
    return (String) getAttributeInternal(DEPTORGCODE);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPT_ORG_CODE using the alias name DeptOrgCode.
   * @param value value to set the DEPT_ORG_CODE
   */
  public void setDeptOrgCode(String value)
  {
    setAttributeInternal(DEPTORGCODE, value);
  }

  /**
   * Gets the attribute value for DEPT_GOV_CODE using the alias name DeptGovCode.
   * @return the DEPT_GOV_CODE
   */
  public String getDeptGovCode()
  {
    return (String) getAttributeInternal(DEPTGOVCODE);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPT_GOV_CODE using the alias name DeptGovCode.
   * @param value value to set the DEPT_GOV_CODE
   */
  public void setDeptGovCode(String value)
  {
    setAttributeInternal(DEPTGOVCODE, value);
  }

  /**
   * Gets the attribute value for DEPT_PHONE_NO using the alias name DeptPhoneNo.
   * @return the DEPT_PHONE_NO
   */
  public String getDeptPhoneNo()
  {
    return (String) getAttributeInternal(DEPTPHONENO);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPT_PHONE_NO using the alias name DeptPhoneNo.
   * @param value value to set the DEPT_PHONE_NO
   */
  public void setDeptPhoneNo(String value)
  {
    setAttributeInternal(DEPTPHONENO, value);
  }

  /**
   * Gets the attribute value for GEO_PARENT_FK using the alias name GeoParentFk.
   * @return the GEO_PARENT_FK
   */
  public BigDecimal getGeoParentFk()
  {
    return (BigDecimal) getAttributeInternal(GEOPARENTFK);
  }

  /**
   * Sets <code>value</code> as attribute value for GEO_PARENT_FK using the alias name GeoParentFk.
   * @param value value to set the GEO_PARENT_FK
   */
  public void setGeoParentFk(BigDecimal value)
  {
    setAttributeInternal(GEOPARENTFK, value);
  }

  /**
   * Gets the attribute value for FIN_PARENT_FK using the alias name FinParentFk.
   * @return the FIN_PARENT_FK
   */
  public BigDecimal getFinParentFk()
  {
    return (BigDecimal) getAttributeInternal(FINPARENTFK);
  }

  /**
   * Sets <code>value</code> as attribute value for FIN_PARENT_FK using the alias name FinParentFk.
   * @param value value to set the FIN_PARENT_FK
   */
  public void setFinParentFk(BigDecimal value)
  {
    setAttributeInternal(FINPARENTFK, value);
  }

  /**
   * Gets the attribute value for INV_PARENT_FK using the alias name InvParentFk.
   * @return the INV_PARENT_FK
   */
  public BigDecimal getInvParentFk()
  {
    return (BigDecimal) getAttributeInternal(INVPARENTFK);
  }

  /**
   * Sets <code>value</code> as attribute value for INV_PARENT_FK using the alias name InvParentFk.
   * @param value value to set the INV_PARENT_FK
   */
  public void setInvParentFk(BigDecimal value)
  {
    setAttributeInternal(INVPARENTFK, value);
  }

  /**
   * Gets the attribute value for MAIN_PARENT_FK using the alias name MainParentFk.
   * @return the MAIN_PARENT_FK
   */
  public BigDecimal getMainParentFk()
  {
    return (BigDecimal) getAttributeInternal(MAINPARENTFK);
  }

  /**
   * Sets <code>value</code> as attribute value for MAIN_PARENT_FK using the alias name MainParentFk.
   * @param value value to set the MAIN_PARENT_FK
   */
  public void setMainParentFk(BigDecimal value)
  {
    setAttributeInternal(MAINPARENTFK, value);
  }

  /**
   * Gets the attribute value for REGION_PARENT_FK using the alias name RegionParentFk.
   * @return the REGION_PARENT_FK
   */
  public BigDecimal getRegionParentFk()
  {
    return (BigDecimal) getAttributeInternal(REGIONPARENTFK);
  }

  /**
   * Sets <code>value</code> as attribute value for REGION_PARENT_FK using the alias name RegionParentFk.
   * @param value value to set the REGION_PARENT_FK
   */
  public void setRegionParentFk(BigDecimal value)
  {
    setAttributeInternal(REGIONPARENTFK, value);
  }

  /**
   * Gets the attribute value for DEPT_CITY_FK using the alias name DeptCityFk.
   * @return the DEPT_CITY_FK
   */
  public BigDecimal getDeptCityFk()
  {
    return (BigDecimal) getAttributeInternal(DEPTCITYFK);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPT_CITY_FK using the alias name DeptCityFk.
   * @param value value to set the DEPT_CITY_FK
   */
  public void setDeptCityFk(BigDecimal value)
  {
    setAttributeInternal(DEPTCITYFK, value);
  }

  /**
   * Gets the attribute value for TRAFFIC_CODE using the alias name TrafficCode.
   * @return the TRAFFIC_CODE
   */
  public String getTrafficCode()
  {
    return (String) getAttributeInternal(TRAFFICCODE);
  }

  /**
   * Sets <code>value</code> as attribute value for TRAFFIC_CODE using the alias name TrafficCode.
   * @param value value to set the TRAFFIC_CODE
   */
  public void setTrafficCode(String value)
  {
    setAttributeInternal(TRAFFICCODE, value);
  }

  /**
   * Gets the attribute value for DEPT_LONGITUDE using the alias name DeptLongitude.
   * @return the DEPT_LONGITUDE
   */
  public String getDeptLongitude()
  {
    return (String) getAttributeInternal(DEPTLONGITUDE);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPT_LONGITUDE using the alias name DeptLongitude.
   * @param value value to set the DEPT_LONGITUDE
   */
  public void setDeptLongitude(String value)
  {
    setAttributeInternal(DEPTLONGITUDE, value);
  }

  /**
   * Gets the attribute value for DEPT_LATITUDE using the alias name DeptLatitude.
   * @return the DEPT_LATITUDE
   */
  public String getDeptLatitude()
  {
    return (String) getAttributeInternal(DEPTLATITUDE);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPT_LATITUDE using the alias name DeptLatitude.
   * @param value value to set the DEPT_LATITUDE
   */
  public void setDeptLatitude(String value)
  {
    setAttributeInternal(DEPTLATITUDE, value);
  }

  /**
   * Gets the attribute value for BUDGET_FL using the alias name BudgetFl.
   * @return the BUDGET_FL
   */
  public BigDecimal getBudgetFl()
  {
    return (BigDecimal) getAttributeInternal(BUDGETFL);
  }

  /**
   * Sets <code>value</code> as attribute value for BUDGET_FL using the alias name BudgetFl.
   * @param value value to set the BUDGET_FL
   */
  public void setBudgetFl(BigDecimal value)
  {
    setAttributeInternal(BUDGETFL, value);
  }

  /**
   * Gets the attribute value for DEPT_FAX using the alias name DeptFax.
   * @return the DEPT_FAX
   */
  public String getDeptFax()
  {
    return (String) getAttributeInternal(DEPTFAX);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPT_FAX using the alias name DeptFax.
   * @param value value to set the DEPT_FAX
   */
  public void setDeptFax(String value)
  {
    setAttributeInternal(DEPTFAX, value);
  }

  /**
   * Gets the attribute value for DEPT_ORDER using the alias name DeptOrder.
   * @return the DEPT_ORDER
   */
  public BigDecimal getDeptOrder()
  {
    return (BigDecimal) getAttributeInternal(DEPTORDER);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPT_ORDER using the alias name DeptOrder.
   * @param value value to set the DEPT_ORDER
   */
  public void setDeptOrder(BigDecimal value)
  {
    setAttributeInternal(DEPTORDER, value);
  }

  /**
   * Gets the attribute value for VACATION_FL using the alias name VacationFl.
   * @return the VACATION_FL
   */
  public BigDecimal getVacationFl()
  {
    return (BigDecimal) getAttributeInternal(VACATIONFL);
  }

  /**
   * Sets <code>value</code> as attribute value for VACATION_FL using the alias name VacationFl.
   * @param value value to set the VACATION_FL
   */
  public void setVacationFl(BigDecimal value)
  {
    setAttributeInternal(VACATIONFL, value);
  }

  /**
   * Gets the attribute value for VACATION_PERCENT using the alias name VacationPercent.
   * @return the VACATION_PERCENT
   */
  public BigDecimal getVacationPercent()
  {
    return (BigDecimal) getAttributeInternal(VACATIONPERCENT);
  }

  /**
   * Sets <code>value</code> as attribute value for VACATION_PERCENT using the alias name VacationPercent.
   * @param value value to set the VACATION_PERCENT
   */
  public void setVacationPercent(BigDecimal value)
  {
    setAttributeInternal(VACATIONPERCENT, value);
  }

  /**
   * Gets the attribute value for DEPT_IBAN using the alias name DeptIban.
   * @return the DEPT_IBAN
   */
  public String getDeptIban()
  {
    return (String) getAttributeInternal(DEPTIBAN);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPT_IBAN using the alias name DeptIban.
   * @param value value to set the DEPT_IBAN
   */
  public void setDeptIban(String value)
  {
    setAttributeInternal(DEPTIBAN, value);
  }

  /**
   * Gets the attribute value for DEPT_BANK_FK using the alias name DeptBankFk.
   * @return the DEPT_BANK_FK
   */
  public BigDecimal getDeptBankFk()
  {
    return (BigDecimal) getAttributeInternal(DEPTBANKFK);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPT_BANK_FK using the alias name DeptBankFk.
   * @param value value to set the DEPT_BANK_FK
   */
  public void setDeptBankFk(BigDecimal value)
  {
    setAttributeInternal(DEPTBANKFK, value);
  }

  /**
   * Gets the attribute value for DEPT_SECURITY_FK using the alias name DeptSecurityFk.
   * @return the DEPT_SECURITY_FK
   */
  public BigDecimal getDeptSecurityFk()
  {
    return (BigDecimal) getAttributeInternal(DEPTSECURITYFK);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPT_SECURITY_FK using the alias name DeptSecurityFk.
   * @param value value to set the DEPT_SECURITY_FK
   */
  public void setDeptSecurityFk(BigDecimal value)
  {
    setAttributeInternal(DEPTSECURITYFK, value);
  }

  /**
   * Gets the attribute value for DEPT_MILITARY_REGION_FK using the alias name DeptMilitaryRegionFk.
   * @return the DEPT_MILITARY_REGION_FK
   */
  public BigDecimal getDeptMilitaryRegionFk()
  {
    return (BigDecimal) getAttributeInternal(DEPTMILITARYREGIONFK);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPT_MILITARY_REGION_FK using the alias name DeptMilitaryRegionFk.
   * @param value value to set the DEPT_MILITARY_REGION_FK
   */
  public void setDeptMilitaryRegionFk(BigDecimal value)
  {
    setAttributeInternal(DEPTMILITARYREGIONFK, value);
  }

  /**
   * Gets the attribute value for DEPT_ITEM_FK using the alias name DeptItemFk.
   * @return the DEPT_ITEM_FK
   */
  public BigDecimal getDeptItemFk()
  {
    return (BigDecimal) getAttributeInternal(DEPTITEMFK);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPT_ITEM_FK using the alias name DeptItemFk.
   * @param value value to set the DEPT_ITEM_FK
   */
  public void setDeptItemFk(BigDecimal value)
  {
    setAttributeInternal(DEPTITEMFK, value);
  }

  /**
   * Gets the attribute value for DEPT_CODE using the alias name DeptCode.
   * @return the DEPT_CODE
   */
  public String getDeptCode()
  {
    return (String) getAttributeInternal(DEPTCODE);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPT_CODE using the alias name DeptCode.
   * @param value value to set the DEPT_CODE
   */
  public void setDeptCode(String value)
  {
    setAttributeInternal(DEPTCODE, value);
  }

  /**
   * Gets the attribute value for DEPT_CLASS_FK using the alias name DeptClassFk.
   * @return the DEPT_CLASS_FK
   */
  public BigDecimal getDeptClassFk()
  {
    return (BigDecimal) getAttributeInternal(DEPTCLASSFK);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPT_CLASS_FK using the alias name DeptClassFk.
   * @param value value to set the DEPT_CLASS_FK
   */
  public void setDeptClassFk(BigDecimal value)
  {
    setAttributeInternal(DEPTCLASSFK, value);
  }

  /**
   * Gets the attribute value for DEPT_COUNTRY_FK using the alias name DeptCountryFk.
   * @return the DEPT_COUNTRY_FK
   */
  public BigDecimal getDeptCountryFk()
  {
    return (BigDecimal) getAttributeInternal(DEPTCOUNTRYFK);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPT_COUNTRY_FK using the alias name DeptCountryFk.
   * @param value value to set the DEPT_COUNTRY_FK
   */
  public void setDeptCountryFk(BigDecimal value)
  {
    setAttributeInternal(DEPTCOUNTRYFK, value);
  }

  /**
   * Gets the attribute value for DIVISION using the alias name Division.
   * @return the DIVISION
   */
  public String getDivision()
  {
    return (String) getAttributeInternal(DIVISION);
  }

  /**
   * Sets <code>value</code> as attribute value for DIVISION using the alias name Division.
   * @param value value to set the DIVISION
   */
  public void setDivision(String value)
  {
    setAttributeInternal(DIVISION, value);
  }

  /**
   * Gets the attribute value for MAIN_FL using the alias name MainFl.
   * @return the MAIN_FL
   */
  public BigDecimal getMainFl()
  {
    return (BigDecimal) getAttributeInternal(MAINFL);
  }

  /**
   * Sets <code>value</code> as attribute value for MAIN_FL using the alias name MainFl.
   * @param value value to set the MAIN_FL
   */
  public void setMainFl(BigDecimal value)
  {
    setAttributeInternal(MAINFL, value);
  }

  /**
   * Gets the attribute value for MILITARY_FL using the alias name MilitaryFl.
   * @return the MILITARY_FL
   */
  public BigDecimal getMilitaryFl()
  {
    return (BigDecimal) getAttributeInternal(MILITARYFL);
  }

  /**
   * Sets <code>value</code> as attribute value for MILITARY_FL using the alias name MilitaryFl.
   * @param value value to set the MILITARY_FL
   */
  public void setMilitaryFl(BigDecimal value)
  {
    setAttributeInternal(MILITARYFL, value);
  }

  /**
   * Gets the attribute value for MAIN_INV_FL using the alias name MainInvFl.
   * @return the MAIN_INV_FL
   */
  public BigDecimal getMainInvFl()
  {
    return (BigDecimal) getAttributeInternal(MAININVFL);
  }

  /**
   * Sets <code>value</code> as attribute value for MAIN_INV_FL using the alias name MainInvFl.
   * @param value value to set the MAIN_INV_FL
   */
  public void setMainInvFl(BigDecimal value)
  {
    setAttributeInternal(MAININVFL, value);
  }

  /**
   * Gets the attribute value for DEPT_ITEM using the alias name DeptItem.
   * @return the DEPT_ITEM
   */
  public String getDeptItem()
  {
    return (String) getAttributeInternal(DEPTITEM);
  }

  /**
   * Sets <code>value</code> as attribute value for DEPT_ITEM using the alias name DeptItem.
   * @param value value to set the DEPT_ITEM
   */
  public void setDeptItem(String value)
  {
    setAttributeInternal(DEPTITEM, value);
  }

  /**
   * Gets the attribute value for NUMBERING_DEPENDENCY_FK using the alias name NumberingDependencyFk.
   * @return the NUMBERING_DEPENDENCY_FK
   */
  public BigDecimal getNumberingDependencyFk()
  {
    return (BigDecimal) getAttributeInternal(NUMBERINGDEPENDENCYFK);
  }

  /**
   * Sets <code>value</code> as attribute value for NUMBERING_DEPENDENCY_FK using the alias name NumberingDependencyFk.
   * @param value value to set the NUMBERING_DEPENDENCY_FK
   */
  public void setNumberingDependencyFk(BigDecimal value)
  {
    setAttributeInternal(NUMBERINGDEPENDENCYFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayAdminParentFk.
   * @return the DisplayAdminParentFk
   */
  public String getDisplayAdminParentFk()
  {
    return (String) getAttributeInternal(DISPLAYADMINPARENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayAdminParentFk.
   * @param value value to set the  DisplayAdminParentFk
   */
  public void setDisplayAdminParentFk(String value)
  {
    setAttributeInternal(DISPLAYADMINPARENTFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDepartmentsPk.
   * @return the DisplayDepartmentsPk
   */
  public String getDisplayDepartmentsPk()
  {
    return (String) getAttributeInternal(DISPLAYDEPARTMENTSPK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDepartmentsPk.
   * @param value value to set the  DisplayDepartmentsPk
   */
  public void setDisplayDepartmentsPk(String value)
  {
    setAttributeInternal(DISPLAYDEPARTMENTSPK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayAdminParentFkSearch.
   * @return the DisplayAdminParentFkSearch
   */
  public String getDisplayAdminParentFkSearch()
  {
    return (String) getAttributeInternal(DISPLAYADMINPARENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayAdminParentFkSearch.
   * @param value value to set the  DisplayAdminParentFkSearch
   */
  public void setDisplayAdminParentFkSearch(String value)
  {
    setAttributeInternal(DISPLAYADMINPARENTFKSEARCH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDepartmentsPkSearch.
   * @return the DisplayDepartmentsPkSearch
   */
  public String getDisplayDepartmentsPkSearch()
  {
    return (String) getAttributeInternal(DISPLAYDEPARTMENTSPK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDepartmentsPkSearch.
   * @param value value to set the  DisplayDepartmentsPkSearch
   */
  public void setDisplayDepartmentsPkSearch(String value)
  {
    setAttributeInternal(DISPLAYDEPARTMENTSPKSEARCH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayNumberingDependencyFk.
   * @return the DisplayNumberingDependencyFk
   */
  public String getDisplayNumberingDependencyFk()
  {
    return (String) getAttributeInternal(DISPLAYNUMBERINGDEPENDENCYFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayNumberingDependencyFk.
   * @param value value to set the  DisplayNumberingDependencyFk
   */
  public void setDisplayNumberingDependencyFk(String value)
  {
    setAttributeInternal(DISPLAYNUMBERINGDEPENDENCYFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayNumberingDependencyFkSearch.
   * @return the DisplayNumberingDependencyFkSearch
   */
  public String getDisplayNumberingDependencyFkSearch()
  {
    return (String) getAttributeInternal(DISPLAYNUMBERINGDEPENDENCYFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayNumberingDependencyFkSearch.
   * @param value value to set the  DisplayNumberingDependencyFkSearch
   */
  public void setDisplayNumberingDependencyFkSearch(String value)
  {
    setAttributeInternal(DISPLAYNUMBERINGDEPENDENCYFKSEARCH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute NumberingDependencyFkSearch.
   * @return the NumberingDependencyFkSearch
   */
  public BigDecimal getNumberingDependencyFkSearch()
  {
    return (BigDecimal) getAttributeInternal(NUMBERINGDEPENDENCYFK);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link CrsOutgoingDocPreparationView.
   */
  public RowIterator getCrsOutgoingDocPreparationView()
  {
    return (RowIterator) getAttributeInternal(CRSOUTGOINGDOCPREPARATIONVIEW);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link CrsOutgoingDocPreparationView1.
   */
  public RowIterator getCrsOutgoingDocPreparationView1()
  {
    return (RowIterator) getAttributeInternal(CRSOUTGOINGDOCPREPARATIONVIEW1);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link CrsDeptGroupDeptsView.
   */
  public RowIterator getCrsDeptGroupDeptsView()
  {
    return (RowIterator) getAttributeInternal(CRSDEPTGROUPDEPTSVIEW);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link CrsAllowedSendDepartmentsView.
   */
  public RowIterator getCrsAllowedSendDepartmentsView()
  {
    return (RowIterator) getAttributeInternal(CRSALLOWEDSENDDEPARTMENTSVIEW);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link CrsAllowedSendDepartmentsView1.
   */
  public RowIterator getCrsAllowedSendDepartmentsView1()
  {
    return (RowIterator) getAttributeInternal(CRSALLOWEDSENDDEPARTMENTSVIEW1);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link HcmDepartmentsView.
   */
  public RowIterator getHcmDepartmentsView()
  {
    return (RowIterator) getAttributeInternal(HCMDEPARTMENTSVIEW);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link HcmDepartmentsView1.
   */
  public RowIterator getHcmDepartmentsView1()
  {
    return (RowIterator) getAttributeInternal(HCMDEPARTMENTSVIEW1);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link HcmDepartmentsView2.
   */
  public RowIterator getHcmDepartmentsView2()
  {
    return (RowIterator) getAttributeInternal(HCMDEPARTMENTSVIEW2);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link HcmDepartmentsView3.
   */
  public RowIterator getHcmDepartmentsView3()
  {
    return (RowIterator) getAttributeInternal(HCMDEPARTMENTSVIEW3);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link HcmDepartmentsView4.
   */
  public RowIterator getHcmDepartmentsView4()
  {
    return (RowIterator) getAttributeInternal(HCMDEPARTMENTSVIEW4);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link HcmDepartmentsView5.
   */
  public RowIterator getHcmDepartmentsView5()
  {
    return (RowIterator) getAttributeInternal(HCMDEPARTMENTSVIEW5);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link CrsFilesLocationView.
   */
  public RowIterator getCrsFilesLocationView()
  {
    return (RowIterator) getAttributeInternal(CRSFILESLOCATIONVIEW);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link CrsDocClassCcView.
   */
  public RowIterator getCrsDocClassCcView()
  {
    return (RowIterator) getAttributeInternal(CRSDOCCLASSCCVIEW);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link CrsOutgoingDocCcView.
   */
  public RowIterator getCrsOutgoingDocCcView()
  {
    return (RowIterator) getAttributeInternal(CRSOUTGOINGDOCCCVIEW);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link CrsIncomingDocumentsView.
   */
  public RowIterator getCrsIncomingDocumentsView()
  {
    return (RowIterator) getAttributeInternal(CRSINCOMINGDOCUMENTSVIEW);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link CrsIncomingDocumentsView1.
   */
  public RowIterator getCrsIncomingDocumentsView1()
  {
    return (RowIterator) getAttributeInternal(CRSINCOMINGDOCUMENTSVIEW1);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link CrsOutgoingDocumentsView.
   */
  public RowIterator getCrsOutgoingDocumentsView()
  {
    return (RowIterator) getAttributeInternal(CRSOUTGOINGDOCUMENTSVIEW);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link CrsOutgoingDocumentsView1.
   */
  public RowIterator getCrsOutgoingDocumentsView1()
  {
    return (RowIterator) getAttributeInternal(CRSOUTGOINGDOCUMENTSVIEW1);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link CrsLetterTemplatesView.
   */
  public RowIterator getCrsLetterTemplatesView()
  {
    return (RowIterator) getAttributeInternal(CRSLETTERTEMPLATESVIEW);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link CrsIncomingDocCcView.
   */
  public RowIterator getCrsIncomingDocCcView()
  {
    return (RowIterator) getAttributeInternal(CRSINCOMINGDOCCCVIEW);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link CrsAllowedSendTypesView.
   */
  public RowIterator getCrsAllowedSendTypesView()
  {
    return (RowIterator) getAttributeInternal(CRSALLOWEDSENDTYPESVIEW);
  }

  /**
   * Gets the view accessor <code>RowSet</code> DeparmentsRVO.
   */
  public RowSet getDeparmentsRVO()
  {
    return (RowSet) getAttributeInternal(DEPARMENTSRVO);
  }
}

