package crs.model.ro;

import java.math.BigDecimal;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 05 11:25:56 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CrsFilesLocationRVOImpl
  extends ViewObjectImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public CrsFilesLocationRVOImpl()
  {
  }
}

