package crs.model.ro;

import java.util.Collection;

import oracle.jbo.Key;
import oracle.jbo.RangePagingDataFilter;
import oracle.jbo.ScrollableDataFilter;
import oracle.jbo.server.ProgrammaticViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 06 15:42:18 EEST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DeliveryStatmentAttachPVOImpl
  extends ProgrammaticViewObjectImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public DeliveryStatmentAttachPVOImpl()
  {
  }

  /**
   * getRangePagingData - for custom java data source support.
   */
  public Collection<Object> getRangePagingData(RangePagingDataFilter filter)
  {
    Collection<Object> value = super.getRangePagingData(filter);
    return value;
  }

  /**
   * retrieveDataByKey - for custom java data source support.
   */
  public Collection<Object> retrieveDataByKey(Key key, int size)
  {
    Collection<Object> value = super.retrieveDataByKey(key, size);
    return value;
  }

  /**
   * getScrollableData - for custom java data source support.
   */
  public Collection<Object> getScrollableData(ScrollableDataFilter filter)
  {
    Collection<Object> value = super.getScrollableData(filter);
    return value;
  }
}

