package crs.model.ro;

import java.math.BigDecimal;

import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 14 11:48:05 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DeparmentsRVORowImpl
  extends ViewRowImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    DepartmentsPk,
    DepartmentName,
    DeptTypeFk,
    DisplayDeptTypeFk,
    DeptStatusFl,
    DeptSecurityFk,
    DeptExternalFl,
    SelectedFl,
    DepartmentNameSearch,
    ActionFk,
    DisplayActionFk,
    Guidance,
    SsoSystemLookupValuesActionFk;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int DEPARTMENTSPK = AttributesEnum.DepartmentsPk.index();
  public static final int DEPARTMENTNAME = AttributesEnum.DepartmentName.index();
  public static final int DEPTTYPEFK = AttributesEnum.DeptTypeFk.index();
  public static final int DISPLAYDEPTTYPEFK = AttributesEnum.DisplayDeptTypeFk.index();
  public static final int DEPTSTATUSFL = AttributesEnum.DeptStatusFl.index();
  public static final int DEPTSECURITYFK = AttributesEnum.DeptSecurityFk.index();
  public static final int DEPTEXTERNALFL = AttributesEnum.DeptExternalFl.index();
  public static final int SELECTEDFL = AttributesEnum.SelectedFl.index();
  public static final int DEPARTMENTNAMESEARCH = AttributesEnum.DepartmentNameSearch.index();
  public static final int ACTIONFK = AttributesEnum.ActionFk.index();
  public static final int DISPLAYACTIONFK = AttributesEnum.DisplayActionFk.index();
  public static final int GUIDANCE = AttributesEnum.Guidance.index();
  public static final int SSOSYSTEMLOOKUPVALUESACTIONFK = AttributesEnum.SsoSystemLookupValuesActionFk.index();

  /**
   * This is the default constructor (do not remove).
   */
  public DeparmentsRVORowImpl()
  {
  }

  /**
   * Gets the attribute value for the calculated attribute DepartmentsPk.
   * @return the DepartmentsPk
   */
  public BigDecimal getDepartmentsPk()
  {
    return (BigDecimal) getAttributeInternal(DEPARTMENTSPK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DepartmentsPk.
   * @param value value to set the  DepartmentsPk
   */
  public void setDepartmentsPk(BigDecimal value)
  {
    setAttributeInternal(DEPARTMENTSPK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DepartmentName.
   * @return the DepartmentName
   */
  public String getDepartmentName()
  {
    return (String) getAttributeInternal(DEPARTMENTNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DepartmentName.
   * @param value value to set the  DepartmentName
   */
  public void setDepartmentName(String value)
  {
    setAttributeInternal(DEPARTMENTNAME, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DeptTypeFk.
   * @return the DeptTypeFk
   */
  public BigDecimal getDeptTypeFk()
  {
    return (BigDecimal) getAttributeInternal(DEPTTYPEFK);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDeptTypeFk.
   * @return the DisplayDeptTypeFk
   */
  public String getDisplayDeptTypeFk()
  {
    return (String) getAttributeInternal(DISPLAYDEPTTYPEFK);
  }

  /**
   * Gets the attribute value for the calculated attribute DeptStatusFl.
   * @return the DeptStatusFl
   */
  public BigDecimal getDeptStatusFl()
  {
    return (BigDecimal) getAttributeInternal(DEPTSTATUSFL);
  }

  /**
   * Gets the attribute value for the calculated attribute DeptSecurityFk.
   * @return the DeptSecurityFk
   */
  public BigDecimal getDeptSecurityFk()
  {
    return (BigDecimal) getAttributeInternal(DEPTSECURITYFK);
  }

  /**
   * Gets the attribute value for the calculated attribute DeptExternalFl.
   * @return the DeptExternalFl
   */
  public BigDecimal getDeptExternalFl()
  {
    return (BigDecimal) getAttributeInternal(DEPTEXTERNALFL);
  }

  /**
   * Gets the attribute value for the calculated attribute SeletedFl.
   * @return the SeletedFl
   */
  public BigDecimal getSelectedFl()
  {
    return (BigDecimal) getAttributeInternal(SELECTEDFL);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute SeletedFl.
   * @param value value to set the  SeletedFl
   */
  public void setSelectedFl(BigDecimal value)
  {
    setAttributeInternal(SELECTEDFL, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DepartmentNameSearch.
   * @return the DepartmentNameSearch
   */
  public String getDepartmentNameSearch()
  {
    return (String) getAttributeInternal(DEPARTMENTNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DepartmentNameSearch.
   * @param value value to set the  DepartmentNameSearch
   */
  public void setDepartmentNameSearch(String value)
  {
    setAttributeInternal(DEPARTMENTNAMESEARCH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute ActionFk.
   * @return the ActionFk
   */
  public BigDecimal getActionFk()
  {
    return (BigDecimal) getAttributeInternal(ACTIONFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute ActionFk.
   * @param value value to set the  ActionFk
   */
  public void setActionFk(BigDecimal value)
  {
    setAttributeInternal(ACTIONFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayActionFk.
   * @return the DisplayActionFk
   */
  public String getDisplayActionFk()
  {
    return (String) getAttributeInternal(DISPLAYACTIONFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayActionFk.
   * @param value value to set the  DisplayActionFk
   */
  public void setDisplayActionFk(String value)
  {
    setAttributeInternal(DISPLAYACTIONFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute Guidance.
   * @return the Guidance
   */
  public String getGuidance()
  {
    return (String) getAttributeInternal(GUIDANCE);
  }


  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute Guidance.
   * @param value value to set the  Guidance
   */
  public void setGuidance(String value)
  {
    setAttributeInternal(GUIDANCE, value);
  }

  /**
   * Gets the view accessor <code>RowSet</code> SsoSystemLookupValuesActionFk.
   */
  public RowSet getSsoSystemLookupValuesActionFk()
  {
    return (RowSet) getAttributeInternal(SSOSYSTEMLOOKUPVALUESACTIONFK);
  }
}

