package crs.model.ro;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 06 12:36:18 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DocCcVwViewRowImpl
  extends ViewRowImpl {
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
        DocTypeFk,
        IncomingDocCcPk,
        DepartmentsFk,
        IncomingDocumentsFk,
        CreatedBy,
        CreationDate,
        ModifiedBy,
        ModifiedDate,
        DisplayDocTypeFk,
        DisplayCreatedBy,
        DisplayModifiedBy,
        DisplayDepartmentsFk,
        DisplayActionFk,
        ExecutionDateG,
        ExecutionDateH,
        ActionFk,
        UserDepartmentFk,
        DisplayDocTypeFkSearch,
        DocTypeFkSearch,
        DisplayDepartmentsFkSearch,
        DisplayCreatedBySearch,
        DisplayModifiedBySearch,
        DisplayActionFkSearch,
        SsoActiveLookupValuesVwActionFK;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


    public static final int DOCTYPEFK = AttributesEnum.DocTypeFk.index();
    public static final int INCOMINGDOCCCPK = AttributesEnum.IncomingDocCcPk.index();
    public static final int DEPARTMENTSFK = AttributesEnum.DepartmentsFk.index();
    public static final int INCOMINGDOCUMENTSFK = AttributesEnum.IncomingDocumentsFk.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int DISPLAYDOCTYPEFK = AttributesEnum.DisplayDocTypeFk.index();
    public static final int DISPLAYCREATEDBY = AttributesEnum.DisplayCreatedBy.index();
    public static final int DISPLAYMODIFIEDBY = AttributesEnum.DisplayModifiedBy.index();
    public static final int DISPLAYDEPARTMENTSFK = AttributesEnum.DisplayDepartmentsFk.index();
    public static final int DISPLAYACTIONFK = AttributesEnum.DisplayActionFk.index();
    public static final int EXECUTIONDATEG = AttributesEnum.ExecutionDateG.index();
    public static final int EXECUTIONDATEH = AttributesEnum.ExecutionDateH.index();
    public static final int ACTIONFK = AttributesEnum.ActionFk.index();
    public static final int USERDEPARTMENTFK = AttributesEnum.UserDepartmentFk.index();
    public static final int DISPLAYDOCTYPEFKSEARCH = AttributesEnum.DisplayDocTypeFkSearch.index();
    public static final int DOCTYPEFKSEARCH = AttributesEnum.DocTypeFkSearch.index();
    public static final int DISPLAYDEPARTMENTSFKSEARCH = AttributesEnum.DisplayDepartmentsFkSearch.index();
    public static final int DISPLAYCREATEDBYSEARCH = AttributesEnum.DisplayCreatedBySearch.index();
    public static final int DISPLAYMODIFIEDBYSEARCH = AttributesEnum.DisplayModifiedBySearch.index();
    public static final int DISPLAYACTIONFKSEARCH = AttributesEnum.DisplayActionFkSearch.index();
    public static final int SSOACTIVELOOKUPVALUESVWACTIONFK = AttributesEnum.SsoActiveLookupValuesVwActionFK.index();

    /**
     * This is the default constructor (do not remove).
     */
  public DocCcVwViewRowImpl()
  {
  }

  /**
   * Gets the attribute value for the calculated attribute DocTypeFk.
   * @return the DocTypeFk
   */
  public BigDecimal getDocTypeFk()
  {
    return (BigDecimal) getAttributeInternal(DOCTYPEFK);
  }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DocTypeFk.
     * @param value value to set the  DocTypeFk
     */
    public void setDocTypeFk(BigDecimal value) {
        setAttributeInternal(DOCTYPEFK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DisplayDocTypeFk.
     * @return the DisplayDocTypeFk
     */
  public String getDisplayDocTypeFk()
  {
    return (String) getAttributeInternal(DISPLAYDOCTYPEFK);
  }


    /**
     * Gets the attribute value for the calculated attribute DisplayDocTypeFkSearch.
     * @return the DisplayDocTypeFkSearch
     */
  public String getDisplayDocTypeFkSearch()
  {
    return (String) getAttributeInternal(DISPLAYDOCTYPEFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDocTypeFkSearch.
   * @param value value to set the  DisplayDocTypeFkSearch
   */
  public void setDisplayDocTypeFkSearch(String value)
  {
    setAttributeInternal(DISPLAYDOCTYPEFKSEARCH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DocTypeFkSearch.
   * @return the DocTypeFkSearch
   */
  public BigDecimal getDocTypeFkSearch()
  {
    return (BigDecimal) getAttributeInternal(DOCTYPEFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DocTypeFkSearch.
   * @param value value to set the  DocTypeFkSearch
   */
  public void setDocTypeFkSearch(BigDecimal value)
  {
    setAttributeInternal(DOCTYPEFKSEARCH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute IncomingDocCcPk.
   * @return the IncomingDocCcPk
   */
  public BigDecimal getIncomingDocCcPk()
  {
    return (BigDecimal) getAttributeInternal(INCOMINGDOCCCPK);
  }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IncomingDocCcPk.
     * @param value value to set the  IncomingDocCcPk
     */
    public void setIncomingDocCcPk(BigDecimal value) {
        setAttributeInternal(INCOMINGDOCCCPK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DepartmentsFk.
     * @return the DepartmentsFk
     */
  public BigDecimal getDepartmentsFk()
  {
    return (BigDecimal) getAttributeInternal(DEPARTMENTSFK);
  }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DepartmentsFk.
     * @param value value to set the  DepartmentsFk
     */
    public void setDepartmentsFk(BigDecimal value) {
        setAttributeInternal(DEPARTMENTSFK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DisplayDepartmentsFk.
     * @return the DisplayDepartmentsFk
     */
  public String getDisplayDepartmentsFk()
  {
    return (String) getAttributeInternal(DISPLAYDEPARTMENTSFK);
  }


    /**
     * Gets the attribute value for the calculated attribute DisplayActionFk.
     * @return the DisplayActionFk
     */
    public String getDisplayActionFk() {
        return (String) getAttributeInternal(DISPLAYACTIONFK);
    }

    /**
     * Gets the attribute value for the calculated attribute ExecutionDateG.
     * @return the ExecutionDateG
     */
    public Timestamp getExecutionDateG() {
        return (Timestamp) getAttributeInternal(EXECUTIONDATEG);
    }

    /**
     * Gets the attribute value for the calculated attribute ExecutionDateH.
     * @return the ExecutionDateH
     */
    public BigDecimal getExecutionDateH() {
        return (BigDecimal) getAttributeInternal(EXECUTIONDATEH);
    }

    /**
     * Gets the attribute value for the calculated attribute ActionFk.
     * @return the ActionFk
     */
    public BigDecimal getActionFk() {
        return (BigDecimal) getAttributeInternal(ACTIONFK);
    }

    /**
     * Gets the attribute value for the calculated attribute DisplayDepartmentsFkSearch.
     * @return the DisplayDepartmentsFkSearch
     */
  public String getDisplayDepartmentsFkSearch()
  {
    return (String) getAttributeInternal(DISPLAYDEPARTMENTSFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDepartmentsFkSearch.
   * @param value value to set the  DisplayDepartmentsFkSearch
   */
  public void setDisplayDepartmentsFkSearch(String value)
  {
    setAttributeInternal(DISPLAYDEPARTMENTSFKSEARCH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute IncomingDocumentsFk.
   * @return the IncomingDocumentsFk
   */
  public BigDecimal getIncomingDocumentsFk()
  {
    return (BigDecimal) getAttributeInternal(INCOMINGDOCUMENTSFK);
  }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IncomingDocumentsFk.
     * @param value value to set the  IncomingDocumentsFk
     */
    public void setIncomingDocumentsFk(BigDecimal value) {
        setAttributeInternal(INCOMINGDOCUMENTSFK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedBy.
     * @return the CreatedBy
     */
  public BigDecimal getCreatedBy()
  {
    return (BigDecimal) getAttributeInternal(CREATEDBY);
  }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy.
     * @param value value to set the  CreatedBy
     */
    public void setCreatedBy(BigDecimal value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreationDate.
     * @return the CreationDate
     */
  public Timestamp getCreationDate()
  {
    return (Timestamp) getAttributeInternal(CREATIONDATE);
  }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreationDate.
     * @param value value to set the  CreationDate
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ModifiedBy.
     * @return the ModifiedBy
     */
  public BigDecimal getModifiedBy()
  {
    return (BigDecimal) getAttributeInternal(MODIFIEDBY);
  }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ModifiedBy.
     * @param value value to set the  ModifiedBy
     */
    public void setModifiedBy(BigDecimal value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ModifiedDate.
     * @return the ModifiedDate
     */
  public Timestamp getModifiedDate()
  {
    return (Timestamp) getAttributeInternal(MODIFIEDDATE);
  }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ModifiedDate.
     * @param value value to set the  ModifiedDate
     */
    public void setModifiedDate(Timestamp value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UserDepartmentFk.
     * @return the UserDepartmentFk
     */
  public BigDecimal getUserDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(USERDEPARTMENTFK);
  }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UserDepartmentFk.
     * @param value value to set the  UserDepartmentFk
     */
    public void setUserDepartmentFk(BigDecimal value) {
        setAttributeInternal(USERDEPARTMENTFK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DisplayCreatedBy.
     * @return the DisplayCreatedBy
     */
  public String getDisplayCreatedBy()
  {
    return (String) getAttributeInternal(DISPLAYCREATEDBY);
  }


    /**
     * Gets the attribute value for the calculated attribute DisplayCreatedBySearch.
     * @return the DisplayCreatedBySearch
     */
  public String getDisplayCreatedBySearch()
  {
    return (String) getAttributeInternal(DISPLAYCREATEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayCreatedBySearch.
   * @param value value to set the  DisplayCreatedBySearch
   */
  public void setDisplayCreatedBySearch(String value)
  {
    setAttributeInternal(DISPLAYCREATEDBYSEARCH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayModifiedBy.
   * @return the DisplayModifiedBy
   */
  public String getDisplayModifiedBy()
  {
    return (String) getAttributeInternal(DISPLAYMODIFIEDBY);
  }


    /**
     * Gets the attribute value for the calculated attribute DisplayModifiedBySearch.
     * @return the DisplayModifiedBySearch
     */
  public String getDisplayModifiedBySearch()
  {
    return (String) getAttributeInternal(DISPLAYMODIFIEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayModifiedBySearch.
   * @param value value to set the  DisplayModifiedBySearch
   */
  public void setDisplayModifiedBySearch(String value)
  {
    setAttributeInternal(DISPLAYMODIFIEDBYSEARCH, value);
  }

    /**
     * Gets the attribute value for the calculated attribute DisplayActionFkSearch.
     * @return the DisplayActionFkSearch
     */
    public String getDisplayActionFkSearch() {
        return (String) getAttributeInternal(DISPLAYACTIONFK);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SsoActiveLookupValuesVwView1.
     */
    public RowSet getSsoActiveLookupValuesVwActionFK() {
        return (RowSet) getAttributeInternal(SSOACTIVELOOKUPVALUESVWACTIONFK);
    }
}

