package crs.model.ro;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 11 09:50:16 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EntryCountOutgoingDocViewRowImpl
  extends ViewRowImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    Totaloutgoing,
    CreatedBy,
    Createdbydesc;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }
  public static final int TOTALOUTGOING = AttributesEnum.Totaloutgoing.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATEDBYDESC = AttributesEnum.Createdbydesc.index();

  /**
   * This is the default constructor (do not remove).
   */
  public EntryCountOutgoingDocViewRowImpl()
  {
  }
}

