package crs.model.ro;

import java.math.BigDecimal;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 04 13:49:47 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HcmDepartmentsVwViewRowImpl
  extends ViewRowImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    DepartmentsPk,
    DisplayDepartmentsPk,
    AdminParentFk,
    DisplayAdminParentFk,
    DeptExternalFl,
    DisplayDeptStatusFk,
    DeptStatusFl,
    DisplayDepartmentsPkSeacrh,
    DisplayAdminParentFkSearch,
    CrsFilesLocationView,
    CrsAllowedSendDepartmentsView,
    CrsAllowedSendTypesView,
    CrsLetterTemplatesView,
    SsoActiveLookupValuesVwView1;
    private static AttributesEnum[] vals = null;
    ;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int DEPARTMENTSPK = AttributesEnum.DepartmentsPk.index();
  public static final int DISPLAYDEPARTMENTSPK = AttributesEnum.DisplayDepartmentsPk.index();
  public static final int ADMINPARENTFK = AttributesEnum.AdminParentFk.index();
  public static final int DISPLAYADMINPARENTFK = AttributesEnum.DisplayAdminParentFk.index();
  public static final int DEPTEXTERNALFL = AttributesEnum.DeptExternalFl.index();
  public static final int DISPLAYDEPTSTATUSFK = AttributesEnum.DisplayDeptStatusFk.index();
  public static final int DEPTSTATUSFL = AttributesEnum.DeptStatusFl.index();
  public static final int DISPLAYDEPARTMENTSPKSEACRH = AttributesEnum.DisplayDepartmentsPkSeacrh.index();
  public static final int DISPLAYADMINPARENTFKSEARCH = AttributesEnum.DisplayAdminParentFkSearch.index();
  public static final int CRSFILESLOCATIONVIEW = AttributesEnum.CrsFilesLocationView.index();
  public static final int CRSALLOWEDSENDDEPARTMENTSVIEW = AttributesEnum.CrsAllowedSendDepartmentsView.index();
  public static final int CRSALLOWEDSENDTYPESVIEW = AttributesEnum.CrsAllowedSendTypesView.index();
  public static final int CRSLETTERTEMPLATESVIEW = AttributesEnum.CrsLetterTemplatesView.index();
  public static final int SSOACTIVELOOKUPVALUESVWVIEW1 = AttributesEnum.SsoActiveLookupValuesVwView1.index();

  /**
   * This is the default constructor (do not remove).
   */
  public HcmDepartmentsVwViewRowImpl()
  {
  }

  /**
   * Gets the attribute value for the calculated attribute DepartmentsPk.
   * @return the DepartmentsPk
   */
  public BigDecimal getDepartmentsPk()
  {
    return (BigDecimal) getAttributeInternal(DEPARTMENTSPK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DepartmentsPk.
   * @param value value to set the  DepartmentsPk
   */
  public void setDepartmentsPk(BigDecimal value)
  {
    setAttributeInternal(DEPARTMENTSPK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDepartmentsPk.
   * @return the DisplayDepartmentsPk
   */
  public String getDisplayDepartmentsPk()
  {
    return (String) getAttributeInternal(DISPLAYDEPARTMENTSPK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDepartmentsPk.
   * @param value value to set the  DisplayDepartmentsPk
   */
  public void setDisplayDepartmentsPk(String value)
  {
    setAttributeInternal(DISPLAYDEPARTMENTSPK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute AdminParentFk.
   * @return the AdminParentFk
   */
  public BigDecimal getAdminParentFk()
  {
    return (BigDecimal) getAttributeInternal(ADMINPARENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute AdminParentFk.
   * @param value value to set the  AdminParentFk
   */
  public void setAdminParentFk(BigDecimal value)
  {
    setAttributeInternal(ADMINPARENTFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayAdminParentFk.
   * @return the DisplayAdminParentFk
   */
  public String getDisplayAdminParentFk()
  {
    return (String) getAttributeInternal(DISPLAYADMINPARENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayAdminParentFk.
   * @param value value to set the  DisplayAdminParentFk
   */
  public void setDisplayAdminParentFk(String value)
  {
    setAttributeInternal(DISPLAYADMINPARENTFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DeptExternalFl.
   * @return the DeptExternalFl
   */
  public BigDecimal getDeptExternalFl()
  {
    return (BigDecimal) getAttributeInternal(DEPTEXTERNALFL);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DeptExternalFl.
   * @param value value to set the  DeptExternalFl
   */
  public void setDeptExternalFl(BigDecimal value)
  {
    setAttributeInternal(DEPTEXTERNALFL, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDeptStatusFk.
   * @return the DisplayDeptStatusFk
   */
  public String getDisplayDeptStatusFk()
  {
    return (String) getAttributeInternal(DISPLAYDEPTSTATUSFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDeptStatusFk.
   * @param value value to set the  DisplayDeptStatusFk
   */
  public void setDisplayDeptStatusFk(String value)
  {
    setAttributeInternal(DISPLAYDEPTSTATUSFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DeptStatusFl.
   * @return the DeptStatusFl
   */
  public BigDecimal getDeptStatusFl()
  {
    return (BigDecimal) getAttributeInternal(DEPTSTATUSFL);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDepartmentsPkSeacrh.
   * @return the DisplayDepartmentsPkSeacrh
   */
  public String getDisplayDepartmentsPkSeacrh()
  {
    return (String) getAttributeInternal(DISPLAYDEPARTMENTSPK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDepartmentsPkSeacrh.
   * @param value value to set the  DisplayDepartmentsPkSeacrh
   */
  public void setDisplayDepartmentsPkSeacrh(String value)
  {
    setAttributeInternal(DISPLAYDEPARTMENTSPKSEACRH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayAdminParentFkSearch.
   * @return the DisplayAdminParentFkSearch
   */
  public String getDisplayAdminParentFkSearch()
  {
    return (String) getAttributeInternal(DISPLAYADMINPARENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayAdminParentFkSearch.
   * @param value value to set the  DisplayAdminParentFkSearch
   */
  public void setDisplayAdminParentFkSearch(String value)
  {
    setAttributeInternal(DISPLAYADMINPARENTFKSEARCH, value);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link CrsFilesLocationView.
   */
  public RowIterator getCrsFilesLocationView()
  {
    return (RowIterator) getAttributeInternal(CRSFILESLOCATIONVIEW);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link CrsAllowedSendDepartmentsView.
   */
  public RowIterator getCrsAllowedSendDepartmentsView()
  {
    return (RowIterator) getAttributeInternal(CRSALLOWEDSENDDEPARTMENTSVIEW);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link CrsAllowedSendTypesView.
   */
  public RowIterator getCrsAllowedSendTypesView()
  {
    return (RowIterator) getAttributeInternal(CRSALLOWEDSENDTYPESVIEW);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link CrsLetterTemplatesView.
   */
  public RowIterator getCrsLetterTemplatesView()
  {
    return (RowIterator) getAttributeInternal(CRSLETTERTEMPLATESVIEW);
  }


  /**
   * Gets the view accessor <code>RowSet</code> SsoActiveLookupValuesVwView1.
   */
  public RowSet getSsoActiveLookupValuesVwView1()
  {
    return (RowSet) getAttributeInternal(SSOACTIVELOOKUPVALUESVWVIEW1);
  }
}

