package crs.model.ro;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 31 14:06:05 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HcmEmpBasicDataVwRowImpl
  extends ViewRowImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    EmployeesPk,
    DisplayEmployeesPk,
    ActionFk,
    DisplayActionFk,
    Guidance,
    SeletedFl,
    SelectedFl,
    SsoSystemLookupValuesActionFk;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    protected int index()
    {
      return HcmEmpBasicDataVwRowImpl.AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return HcmEmpBasicDataVwRowImpl.AttributesEnum.firstIndex() + HcmEmpBasicDataVwRowImpl.AttributesEnum
                                                                                            .staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = HcmEmpBasicDataVwRowImpl.AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int EMPLOYEESPK = AttributesEnum.EmployeesPk.index();
  public static final int DISPLAYEMPLOYEESPK = AttributesEnum.DisplayEmployeesPk.index();
  public static final int ACTIONFK = AttributesEnum.ActionFk.index();
  public static final int DISPLAYACTIONFK = AttributesEnum.DisplayActionFk.index();
  public static final int GUIDANCE = AttributesEnum.Guidance.index();
  public static final int SELETEDFL = AttributesEnum.SeletedFl.index();
  public static final int SELECTEDFL = AttributesEnum.SelectedFl.index();
  public static final int SSOSYSTEMLOOKUPVALUESACTIONFK = AttributesEnum.SsoSystemLookupValuesActionFk.index();

  /**
   * This is the default constructor (do not remove).
   */
  public HcmEmpBasicDataVwRowImpl()
  {
  }
}

