package crs.model.ro;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.jbo.RowIterator;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 03 19:50:49 EET 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IncomingDocumentCCVwViewRowImpl
  extends ViewRowImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    IncomingDocCcPk,
    CcDepartmentsFk,
    CcDepartmentsName,
    ActionFk,
    DisplayActionFk,
    EmployeeFk,
    DisplayEmployeeFk,
    ExecutionDateG,
    ExecutionDateH,
    IncomingDocumentsPk,
    DisplayInSubject,
    InDocDateG,
    InDocDateH,
    ConfirmAssignmentFl,
    IncomingDocStsFk,
    FromDepartmentFk,
    FromDepartmentsName,
    SecurityLevelFk,
    CcDepartmentsNameSearch,
    DisplayActionFkSearch,
    DisplayEmployeeFkSearch,
    DisplayInSubjectSearch,
    CcDepartmentsFkSearch,
    FromDepartmentsNameSearch,
    CrsIncomingDocCcView;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }
  public static final int INCOMINGDOCCCPK = AttributesEnum.IncomingDocCcPk.index();
  public static final int CCDEPARTMENTSFK = AttributesEnum.CcDepartmentsFk.index();
  public static final int CCDEPARTMENTSNAME = AttributesEnum.CcDepartmentsName.index();
  public static final int ACTIONFK = AttributesEnum.ActionFk.index();
  public static final int DISPLAYACTIONFK = AttributesEnum.DisplayActionFk.index();
  public static final int EMPLOYEEFK = AttributesEnum.EmployeeFk.index();
  public static final int DISPLAYEMPLOYEEFK = AttributesEnum.DisplayEmployeeFk.index();
  public static final int EXECUTIONDATEG = AttributesEnum.ExecutionDateG.index();
  public static final int EXECUTIONDATEH = AttributesEnum.ExecutionDateH.index();
  public static final int INCOMINGDOCUMENTSPK = AttributesEnum.IncomingDocumentsPk.index();
  public static final int DISPLAYINSUBJECT = AttributesEnum.DisplayInSubject.index();
  public static final int INDOCDATEG = AttributesEnum.InDocDateG.index();
  public static final int INDOCDATEH = AttributesEnum.InDocDateH.index();
  public static final int CONFIRMASSIGNMENTFL = AttributesEnum.ConfirmAssignmentFl.index();
  public static final int INCOMINGDOCSTSFK = AttributesEnum.IncomingDocStsFk.index();
  public static final int FROMDEPARTMENTFK = AttributesEnum.FromDepartmentFk.index();
  public static final int FROMDEPARTMENTSNAME = AttributesEnum.FromDepartmentsName.index();
  public static final int SECURITYLEVELFK = AttributesEnum.SecurityLevelFk.index();
  public static final int CCDEPARTMENTSNAMESEARCH = AttributesEnum.CcDepartmentsNameSearch.index();
  public static final int DISPLAYACTIONFKSEARCH = AttributesEnum.DisplayActionFkSearch.index();
  public static final int DISPLAYEMPLOYEEFKSEARCH = AttributesEnum.DisplayEmployeeFkSearch.index();
  public static final int DISPLAYINSUBJECTSEARCH = AttributesEnum.DisplayInSubjectSearch.index();
  public static final int CCDEPARTMENTSFKSEARCH = AttributesEnum.CcDepartmentsFkSearch.index();
  public static final int FROMDEPARTMENTSNAMESEARCH = AttributesEnum.FromDepartmentsNameSearch.index();
  public static final int CRSINCOMINGDOCCCVIEW = AttributesEnum.CrsIncomingDocCcView.index();

  /**
   * This is the default constructor (do not remove).
   */
  public IncomingDocumentCCVwViewRowImpl()
  {
  }

  /**
   * Gets the attribute value for the calculated attribute IncomingDocCcPk.
   * @return the IncomingDocCcPk
   */
  public BigDecimal getIncomingDocCcPk()
  {
    return (BigDecimal) getAttributeInternal(INCOMINGDOCCCPK);
  }

  /**
   * Gets the attribute value for the calculated attribute CcDepartmentsFk.
   * @return the CcDepartmentsFk
   */
  public BigDecimal getCcDepartmentsFk()
  {
    return (BigDecimal) getAttributeInternal(CCDEPARTMENTSFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute CcDepartmentsFk.
   * @param value value to set the  CcDepartmentsFk
   */
  public void setCcDepartmentsFk(BigDecimal value)
  {
    setAttributeInternal(CCDEPARTMENTSFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute CcDepartmentsName.
   * @return the CcDepartmentsName
   */
  public String getCcDepartmentsName()
  {
    return (String) getAttributeInternal(CCDEPARTMENTSNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute CcDepartmentsName.
   * @param value value to set the  CcDepartmentsName
   */
  public void setCcDepartmentsName(String value)
  {
    setAttributeInternal(CCDEPARTMENTSNAME, value);
  }

  /**
   * Gets the attribute value for the calculated attribute ActionFk.
   * @return the ActionFk
   */
  public BigDecimal getActionFk()
  {
    return (BigDecimal) getAttributeInternal(ACTIONFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute ActionFk.
   * @param value value to set the  ActionFk
   */
  public void setActionFk(BigDecimal value)
  {
    setAttributeInternal(ACTIONFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayActionFk.
   * @return the DisplayActionFk
   */
  public String getDisplayActionFk()
  {
    return (String) getAttributeInternal(DISPLAYACTIONFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayActionFk.
   * @param value value to set the  DisplayActionFk
   */
  public void setDisplayActionFk(String value)
  {
    setAttributeInternal(DISPLAYACTIONFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute EmployeeFk.
   * @return the EmployeeFk
   */
  public BigDecimal getEmployeeFk()
  {
    return (BigDecimal) getAttributeInternal(EMPLOYEEFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute EmployeeFk.
   * @param value value to set the  EmployeeFk
   */
  public void setEmployeeFk(BigDecimal value)
  {
    setAttributeInternal(EMPLOYEEFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayEmployeeFk.
   * @return the DisplayEmployeeFk
   */
  public String getDisplayEmployeeFk()
  {
    return (String) getAttributeInternal(DISPLAYEMPLOYEEFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayEmployeeFk.
   * @param value value to set the  DisplayEmployeeFk
   */
  public void setDisplayEmployeeFk(String value)
  {
    setAttributeInternal(DISPLAYEMPLOYEEFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute ExecutionDateG.
   * @return the ExecutionDateG
   */
  public Date getExecutionDateG()
  {
    return (Date) getAttributeInternal(EXECUTIONDATEG);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute ExecutionDateG.
   * @param value value to set the  ExecutionDateG
   */
  public void setExecutionDateG(Date value)
  {
    setAttributeInternal(EXECUTIONDATEG, value);
  }

  /**
   * Gets the attribute value for the calculated attribute ExecutionDateH.
   * @return the ExecutionDateH
   */
  public BigDecimal getExecutionDateH()
  {
    return (BigDecimal) getAttributeInternal(EXECUTIONDATEH);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute ExecutionDateH.
   * @param value value to set the  ExecutionDateH
   */
  public void setExecutionDateH(BigDecimal value)
  {
    setAttributeInternal(EXECUTIONDATEH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute IncomingDocumentsPk.
   * @return the IncomingDocumentsPk
   */
  public BigDecimal getIncomingDocumentsPk()
  {
    return (BigDecimal) getAttributeInternal(INCOMINGDOCUMENTSPK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute IncomingDocumentsPk.
   * @param value value to set the  IncomingDocumentsPk
   */
  public void setIncomingDocumentsPk(BigDecimal value)
  {
    setAttributeInternal(INCOMINGDOCUMENTSPK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayInSubject.
   * @return the DisplayInSubject
   */
  public String getDisplayInSubject()
  {
    return (String) getAttributeInternal(DISPLAYINSUBJECT);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayInSubject.
   * @param value value to set the  DisplayInSubject
   */
  public void setDisplayInSubject(String value)
  {
    setAttributeInternal(DISPLAYINSUBJECT, value);
  }

  /**
   * Gets the attribute value for the calculated attribute InDocDateG.
   * @return the InDocDateG
   */
  public Date getInDocDateG()
  {
    return (Date) getAttributeInternal(INDOCDATEG);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute InDocDateG.
   * @param value value to set the  InDocDateG
   */
  public void setInDocDateG(Date value)
  {
    setAttributeInternal(INDOCDATEG, value);
  }

  /**
   * Gets the attribute value for the calculated attribute InDocDateH.
   * @return the InDocDateH
   */
  public BigDecimal getInDocDateH()
  {
    return (BigDecimal) getAttributeInternal(INDOCDATEH);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute InDocDateH.
   * @param value value to set the  InDocDateH
   */
  public void setInDocDateH(BigDecimal value)
  {
    setAttributeInternal(INDOCDATEH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute ConfirmAssignmentFl.
   * @return the ConfirmAssignmentFl
   */
  public BigDecimal getConfirmAssignmentFl()
  {
    return (BigDecimal) getAttributeInternal(CONFIRMASSIGNMENTFL);
  }

  /**
   * Gets the attribute value for the calculated attribute IncomingDocStsFk.
   * @return the IncomingDocStsFk
   */
  public BigDecimal getIncomingDocStsFk()
  {
    return (BigDecimal) getAttributeInternal(INCOMINGDOCSTSFK);
  }

  /**
   * Gets the attribute value for the calculated attribute FromDepartmentFk.
   * @return the FromDepartmentFk
   */
  public BigDecimal getFromDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(FROMDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute FromDepartmentFk.
   * @param value value to set the  FromDepartmentFk
   */
  public void setFromDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(FROMDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute FromDepartmentsName.
   * @return the FromDepartmentsName
   */
  public String getFromDepartmentsName()
  {
    return (String) getAttributeInternal(FROMDEPARTMENTSNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute FromDepartmentsName.
   * @param value value to set the  FromDepartmentsName
   */
  public void setFromDepartmentsName(String value)
  {
    setAttributeInternal(FROMDEPARTMENTSNAME, value);
  }

  /**
   * Gets the attribute value for the calculated attribute SecurityLevelFk.
   * @return the SecurityLevelFk
   */
  public BigDecimal getSecurityLevelFk()
  {
    return (BigDecimal) getAttributeInternal(SECURITYLEVELFK);
  }

  /**
   * Gets the attribute value for the calculated attribute CcDepartmentsNameSearch.
   * @return the CcDepartmentsNameSearch
   */
  public String getCcDepartmentsNameSearch()
  {
    return (String) getAttributeInternal(CCDEPARTMENTSNAMESEARCH);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute CcDepartmentsNameSearch.
   * @param value value to set the  CcDepartmentsNameSearch
   */
  public void setCcDepartmentsNameSearch(String value)
  {
    setAttributeInternal(CCDEPARTMENTSNAMESEARCH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayActionFkSearch.
   * @return the DisplayActionFkSearch
   */
  public String getDisplayActionFkSearch()
  {
    return (String) getAttributeInternal(DISPLAYACTIONFKSEARCH);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayActionFkSearch.
   * @param value value to set the  DisplayActionFkSearch
   */
  public void setDisplayActionFkSearch(String value)
  {
    setAttributeInternal(DISPLAYACTIONFKSEARCH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayEmployeeFkSearch.
   * @return the DisplayEmployeeFkSearch
   */
  public String getDisplayEmployeeFkSearch()
  {
    return (String) getAttributeInternal(DISPLAYEMPLOYEEFKSEARCH);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayEmployeeFkSearch.
   * @param value value to set the  DisplayEmployeeFkSearch
   */
  public void setDisplayEmployeeFkSearch(String value)
  {
    setAttributeInternal(DISPLAYEMPLOYEEFKSEARCH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayInSubjectSearch.
   * @return the DisplayInSubjectSearch
   */
  public String getDisplayInSubjectSearch()
  {
    return (String) getAttributeInternal(DISPLAYINSUBJECTSEARCH);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayInSubjectSearch.
   * @param value value to set the  DisplayInSubjectSearch
   */
  public void setDisplayInSubjectSearch(String value)
  {
    setAttributeInternal(DISPLAYINSUBJECTSEARCH, value);
  }

  /**
   * Gets the attribute value for the calculated attribute CcDepartmentsFkSearch.
   * @return the CcDepartmentsFkSearch
   */
  public BigDecimal getCcDepartmentsFkSearch()
  {
    return (BigDecimal) getAttributeInternal(CCDEPARTMENTSFKSEARCH);
  }

  /**
   * Gets the attribute value for the calculated attribute FromDepartmentsNameSearch.
   * @return the FromDepartmentsNameSearch
   */
  public String getFromDepartmentsNameSearch()
  {
    return (String) getAttributeInternal(FROMDEPARTMENTSNAMESEARCH);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute FromDepartmentsNameSearch.
   * @param value value to set the  FromDepartmentsNameSearch
   */
  public void setFromDepartmentsNameSearch(String value)
  {
    setAttributeInternal(FROMDEPARTMENTSNAMESEARCH, value);
  }

  /**
   * Gets the associated <code>RowIterator</code> using master-detail link CrsIncomingDocCcView.
   */
  public RowIterator getCrsIncomingDocCcView()
  {
    return (RowIterator) getAttributeInternal(CRSINCOMINGDOCCCVIEW);
  }
}

