package crs.model.ro;

import crs.common.ControllerUtil;

import java.math.BigDecimal;

import java.sql.Date;

import java.sql.Timestamp;

import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 24 09:12:31 EEST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReportParametersRVORowImpl
  extends ViewRowImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    J1,
    TypeFk,
    CrsDocumentsPk,
    IncomingDocumentsNo,
    OutgoingDocumentsNo,
    PShowDetails,
    StatementNumber,
    DateFrom,
    DateTo,
    FromDepartmentFk,
    ToDepartmentFk,
    PriorityFk,
    SecurityLevelFk,
    DocTypeFk,
    DisplayFromDepartmentFk,
    DisplayToDepartmentFk,
    DisplaySecurityLevelFk,
    DisplayDocTypeFk,
    DisplayPriorityFk,
    HijriDateFrom,
    HijriDateTo,
    AddDayToDateTo,
    DepartmentWhere,
    SecurityWhere,
    ActionFk,
    DisplayActionFk,
    DeptGroupFk,
    DisplayDeptGroupFk,
    LetterTemplatesFK,
    DisplayLetterTemplatesFk,
    DepartmentsFk,
    DisplayDepartmentsFk,
    EmployeeFk,
    DisplayEmployeeFk,
    Guidance,
    InsideDepartmentFk,
    DispalyInsideDepartmentFk,
    SsoActiveLookupValuesVwView1,
    HcmDepartmentsFromDepartmentFk,
    HcmDepartmentsToDepartmentFk,
    SsoSystemLookupValuesPriorityFk,
    SsoSystemLookupValuesSecurityLevelFk,
    SsoSystemLookupValuesInDocTypeFk,
    SsoSystemLookupValuesActionFk,
    CrsDeptGroupRVO,
    CrsLetterTemplatesView,
    DeparmentsRVODeptPk,
    HcmEmpBasicDataVw1,
    DeparmentsRVOInsideDept;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int J1 = AttributesEnum.J1.index();
  public static final int TYPEFK = AttributesEnum.TypeFk.index();
  public static final int CRSDOCUMENTSPK = AttributesEnum.CrsDocumentsPk.index();
  public static final int INCOMINGDOCUMENTSNO = AttributesEnum.IncomingDocumentsNo.index();
  public static final int OUTGOINGDOCUMENTSNO = AttributesEnum.OutgoingDocumentsNo.index();
  public static final int PSHOWDETAILS = AttributesEnum.PShowDetails.index();
  public static final int STATEMENTNUMBER = AttributesEnum.StatementNumber.index();
  public static final int DATEFROM = AttributesEnum.DateFrom.index();
  public static final int DATETO = AttributesEnum.DateTo.index();
  public static final int FROMDEPARTMENTFK = AttributesEnum.FromDepartmentFk.index();
  public static final int TODEPARTMENTFK = AttributesEnum.ToDepartmentFk.index();
  public static final int PRIORITYFK = AttributesEnum.PriorityFk.index();
  public static final int SECURITYLEVELFK = AttributesEnum.SecurityLevelFk.index();
  public static final int DOCTYPEFK = AttributesEnum.DocTypeFk.index();
  public static final int DISPLAYFROMDEPARTMENTFK = AttributesEnum.DisplayFromDepartmentFk.index();
  public static final int DISPLAYTODEPARTMENTFK = AttributesEnum.DisplayToDepartmentFk.index();
  public static final int DISPLAYSECURITYLEVELFK = AttributesEnum.DisplaySecurityLevelFk.index();
  public static final int DISPLAYDOCTYPEFK = AttributesEnum.DisplayDocTypeFk.index();
  public static final int DISPLAYPRIORITYFK = AttributesEnum.DisplayPriorityFk.index();
  public static final int HIJRIDATEFROM = AttributesEnum.HijriDateFrom.index();
  public static final int HIJRIDATETO = AttributesEnum.HijriDateTo.index();
  public static final int ADDDAYTODATETO = AttributesEnum.AddDayToDateTo.index();
  public static final int DEPARTMENTWHERE = AttributesEnum.DepartmentWhere.index();
  public static final int SECURITYWHERE = AttributesEnum.SecurityWhere.index();
  public static final int ACTIONFK = AttributesEnum.ActionFk.index();
  public static final int DISPLAYACTIONFK = AttributesEnum.DisplayActionFk.index();
  public static final int DEPTGROUPFK = AttributesEnum.DeptGroupFk.index();
  public static final int DISPLAYDEPTGROUPFK = AttributesEnum.DisplayDeptGroupFk.index();
  public static final int LETTERTEMPLATESFK = AttributesEnum.LetterTemplatesFK.index();
  public static final int DISPLAYLETTERTEMPLATESFK = AttributesEnum.DisplayLetterTemplatesFk.index();
  public static final int DEPARTMENTSFK = AttributesEnum.DepartmentsFk.index();
  public static final int DISPLAYDEPARTMENTSFK = AttributesEnum.DisplayDepartmentsFk.index();
  public static final int EMPLOYEEFK = AttributesEnum.EmployeeFk.index();
  public static final int DISPLAYEMPLOYEEFK = AttributesEnum.DisplayEmployeeFk.index();
  public static final int GUIDANCE = AttributesEnum.Guidance.index();
  public static final int INSIDEDEPARTMENTFK = AttributesEnum.InsideDepartmentFk.index();
  public static final int DISPALYINSIDEDEPARTMENTFK = AttributesEnum.DispalyInsideDepartmentFk.index();
  public static final int SSOACTIVELOOKUPVALUESVWVIEW1 = AttributesEnum.SsoActiveLookupValuesVwView1.index();
  public static final int HCMDEPARTMENTSFROMDEPARTMENTFK = AttributesEnum.HcmDepartmentsFromDepartmentFk.index();
  public static final int HCMDEPARTMENTSTODEPARTMENTFK = AttributesEnum.HcmDepartmentsToDepartmentFk.index();
  public static final int SSOSYSTEMLOOKUPVALUESPRIORITYFK = AttributesEnum.SsoSystemLookupValuesPriorityFk.index();
  public static final int SSOSYSTEMLOOKUPVALUESSECURITYLEVELFK =
    AttributesEnum.SsoSystemLookupValuesSecurityLevelFk.index();
  public static final int SSOSYSTEMLOOKUPVALUESINDOCTYPEFK = AttributesEnum.SsoSystemLookupValuesInDocTypeFk.index();
  public static final int SSOSYSTEMLOOKUPVALUESACTIONFK = AttributesEnum.SsoSystemLookupValuesActionFk.index();
  public static final int CRSDEPTGROUPRVO = AttributesEnum.CrsDeptGroupRVO.index();
  public static final int CRSLETTERTEMPLATESVIEW = AttributesEnum.CrsLetterTemplatesView.index();
  public static final int DEPARMENTSRVODEPTPK = AttributesEnum.DeparmentsRVODeptPk.index();
  public static final int HCMEMPBASICDATAVW1 = AttributesEnum.HcmEmpBasicDataVw1.index();
  public static final int DEPARMENTSRVOINSIDEDEPT = AttributesEnum.DeparmentsRVOInsideDept.index();

  /**
   * This is the default constructor (do not remove).
   */
  public ReportParametersRVORowImpl()
  {
  }

  /**
   * Gets the attribute value for the calculated attribute J1.
   * @return the J1
   */
  public BigDecimal getJ1()
  {
    return (BigDecimal) getAttributeInternal(J1);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute J1.
   * @param value value to set the  J1
   */
  public void setJ1(BigDecimal value)
  {
    setAttributeInternal(J1, value);
  }

  /**
   * Gets the attribute value for the calculated attribute TypeFk.
   * @return the TypeFk
   */
  public BigDecimal getTypeFk()
  {
    return (BigDecimal) getAttributeInternal(TYPEFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute TypeFk.
   * @param value value to set the  TypeFk
   */
  public void setTypeFk(BigDecimal value)
  {
    setAttributeInternal(TYPEFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute IncomingDocumentsPk.
   * @return the IncomingDocumentsPk
   */
  public BigDecimal getCrsDocumentsPk()
  {
    return (BigDecimal) getAttributeInternal(CRSDOCUMENTSPK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute IncomingDocumentsPk.
   * @param value value to set the  IncomingDocumentsPk
   */
  public void setCrsDocumentsPk(BigDecimal value)
  {
    setAttributeInternal(CRSDOCUMENTSPK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute IncomingDocumentsNo.
   * @return the IncomingDocumentsNo
   */
  public BigDecimal getIncomingDocumentsNo()
  {
    return (BigDecimal) getAttributeInternal(INCOMINGDOCUMENTSNO);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute IncomingDocumentsNo.
   * @param value value to set the  IncomingDocumentsNo
   */
  public void setIncomingDocumentsNo(BigDecimal value)
  {
    setAttributeInternal(INCOMINGDOCUMENTSNO, value);
  }

  /**
   * Gets the attribute value for the calculated attribute OutgoingDocumentsNo.
   * @return the OutgoingDocumentsNo
   */
  public BigDecimal getOutgoingDocumentsNo()
  {
    return (BigDecimal) getAttributeInternal(OUTGOINGDOCUMENTSNO);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute OutgoingDocumentsNo.
   * @param value value to set the  OutgoingDocumentsNo
   */
  public void setOutgoingDocumentsNo(BigDecimal value)
  {
    setAttributeInternal(OUTGOINGDOCUMENTSNO, value);
  }


  /**
   * Gets the attribute value for the calculated attribute PShowDetails.
   * @return the PShowDetails
   */
  public String getPShowDetails()
  {
    return (String) getAttributeInternal(PSHOWDETAILS);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute PShowDetails.
   * @param value value to set the  PShowDetails
   */
  public void setPShowDetails(String value)
  {
    setAttributeInternal(PSHOWDETAILS, value);
  }

  /**
   * Gets the attribute value for the calculated attribute StatementNumber.
   * @return the StatementNumber
   */
  public BigDecimal getStatementNumber()
  {
    return (BigDecimal) getAttributeInternal(STATEMENTNUMBER);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute StatementNumber.
   * @param value value to set the  StatementNumber
   */
  public void setStatementNumber(BigDecimal value)
  {
    setAttributeInternal(STATEMENTNUMBER, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DateFrom.
   * @return the DateFrom
   */
  public Timestamp getDateFrom()
  {
    return (Timestamp) getAttributeInternal(DATEFROM);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DateFrom.
   * @param value value to set the  DateFrom
   */
  public void setDateFrom(Timestamp value)
  {
    setAttributeInternal(DATEFROM, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DateTo.
   * @return the DateTo
   */
  public Timestamp getDateTo()
  {
    return (Timestamp) getAttributeInternal(DATETO);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DateTo.
   * @param value value to set the  DateTo
   */
  public void setDateTo(Timestamp value)
  {
    setAttributeInternal(DATETO, ControllerUtil.setTimeToEndOfDay(value));
    //setAttributeInternal(DATETO, value);
  }

  /**
   * Gets the attribute value for the calculated attribute FromDepartmentFk.
   * @return the FromDepartmentFk
   */
  public BigDecimal getFromDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(FROMDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute FromDepartmentFk.
   * @param value value to set the  FromDepartmentFk
   */
  public void setFromDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(FROMDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute ToDepartmentFk.
   * @return the ToDepartmentFk
   */
  public BigDecimal getToDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(TODEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute ToDepartmentFk.
   * @param value value to set the  ToDepartmentFk
   */
  public void setToDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(TODEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute PriorityFk.
   * @return the PriorityFk
   */
  public BigDecimal getPriorityFk()
  {
    return (BigDecimal) getAttributeInternal(PRIORITYFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute PriorityFk.
   * @param value value to set the  PriorityFk
   */
  public void setPriorityFk(BigDecimal value)
  {
    setAttributeInternal(PRIORITYFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute SecurityLevelFk.
   * @return the SecurityLevelFk
   */
  public BigDecimal getSecurityLevelFk()
  {
    return (BigDecimal) getAttributeInternal(SECURITYLEVELFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute SecurityLevelFk.
   * @param value value to set the  SecurityLevelFk
   */
  public void setSecurityLevelFk(BigDecimal value)
  {
    setAttributeInternal(SECURITYLEVELFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DocTypeFk.
   * @return the DocTypeFk
   */
  public BigDecimal getDocTypeFk()
  {
    return (BigDecimal) getAttributeInternal(DOCTYPEFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DocTypeFk.
   * @param value value to set the  DocTypeFk
   */
  public void setDocTypeFk(BigDecimal value)
  {
    setAttributeInternal(DOCTYPEFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayFromDepartmentFk.
   * @return the DisplayFromDepartmentFk
   */
  public String getDisplayFromDepartmentFk()
  {
    return (String) getAttributeInternal(DISPLAYFROMDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayFromDepartmentFk.
   * @param value value to set the  DisplayFromDepartmentFk
   */
  public void setDisplayFromDepartmentFk(String value)
  {
    setAttributeInternal(DISPLAYFROMDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayToDepartmentFk.
   * @return the DisplayToDepartmentFk
   */
  public String getDisplayToDepartmentFk()
  {
    return (String) getAttributeInternal(DISPLAYTODEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayToDepartmentFk.
   * @param value value to set the  DisplayToDepartmentFk
   */
  public void setDisplayToDepartmentFk(String value)
  {
    setAttributeInternal(DISPLAYTODEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplaySecurityLevelFk.
   * @return the DisplaySecurityLevelFk
   */
  public String getDisplaySecurityLevelFk()
  {
    return (String) getAttributeInternal(DISPLAYSECURITYLEVELFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplaySecurityLevelFk.
   * @param value value to set the  DisplaySecurityLevelFk
   */
  public void setDisplaySecurityLevelFk(String value)
  {
    setAttributeInternal(DISPLAYSECURITYLEVELFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDocTypeFk.
   * @return the DisplayDocTypeFk
   */
  public String getDisplayDocTypeFk()
  {
    return (String) getAttributeInternal(DISPLAYDOCTYPEFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDocTypeFk.
   * @param value value to set the  DisplayDocTypeFk
   */
  public void setDisplayDocTypeFk(String value)
  {
    setAttributeInternal(DISPLAYDOCTYPEFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayPriorityFk.
   * @return the DisplayPriorityFk
   */
  public String getDisplayPriorityFk()
  {
    return (String) getAttributeInternal(DISPLAYPRIORITYFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayPriorityFk.
   * @param value value to set the  DisplayPriorityFk
   */
  public void setDisplayPriorityFk(String value)
  {
    setAttributeInternal(DISPLAYPRIORITYFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute HijriDateFrom.
   * @return the HijriDateFrom
   */
  public BigDecimal getHijriDateFrom()
  {
    return (BigDecimal) getAttributeInternal(HIJRIDATEFROM);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute HijriDateFrom.
   * @param value value to set the  HijriDateFrom
   */
  public void setHijriDateFrom(BigDecimal value)
  {
    setAttributeInternal(HIJRIDATEFROM, value);
  }

  /**
   * Gets the attribute value for the calculated attribute HijriDateTo.
   * @return the HijriDateTo
   */
  public BigDecimal getHijriDateTo()
  {
    return (BigDecimal) getAttributeInternal(HIJRIDATETO);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute HijriDateTo.
   * @param value value to set the  HijriDateTo
   */
  public void setHijriDateTo(BigDecimal value)
  {
    setAttributeInternal(HIJRIDATETO, value);
  }


  /**
   * Gets the attribute value for the calculated attribute AddDayToDateTo.
   * @return the AddDayToDateTo
   */
  public Timestamp getAddDayToDateTo()
  {
    return (Timestamp) getAttributeInternal(ADDDAYTODATETO);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute AddDayToDateTo.
   * @param value value to set the  AddDayToDateTo
   */
  public void setAddDayToDateTo(Timestamp value)
  {
    setAttributeInternal(ADDDAYTODATETO, value);
  }

  /**
   * Gets the attribute value for the calculated attribute Department_where.
   * @return the Department_where
   */
  public String getDepartmentWhere()
  {
    return (String) getAttributeInternal(DEPARTMENTWHERE);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DepartmentWhere.
   * @param value value to set the  DepartmentWhere
   */
  public void setDepartmentWhere(String value)
  {
    setAttributeInternal(DEPARTMENTWHERE, value);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute Department_where.
   * @param value value to set the  Department_where
   */
  public void setDepartment_where(String value)
  {
    setAttributeInternal(DEPARTMENTWHERE, value);
  }

  /**
   * Gets the attribute value for the calculated attribute Security_where.
   * @return the Security_where
   */
  public String getSecurityWhere()
  {
    return (String) getAttributeInternal(SECURITYWHERE);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute Security_where.
   * @param value value to set the  Security_where
   */
  public void setSecurityWhere(String value)
  {
    setAttributeInternal(SECURITYWHERE, value);
  }

  /**
   * Gets the attribute value for the calculated attribute ActionFk.
   * @return the ActionFk
   */
  public BigDecimal getActionFk()
  {
    return (BigDecimal) getAttributeInternal(ACTIONFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute ActionFk.
   * @param value value to set the  ActionFk
   */
  public void setActionFk(BigDecimal value)
  {
    setAttributeInternal(ACTIONFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayActionFk.
   * @return the DisplayActionFk
   */
  public String getDisplayActionFk()
  {
    return (String) getAttributeInternal(DISPLAYACTIONFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayActionFk.
   * @param value value to set the  DisplayActionFk
   */
  public void setDisplayActionFk(String value)
  {
    setAttributeInternal(DISPLAYACTIONFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DeptGroupFk.
   * @return the DeptGroupFk
   */
  public BigDecimal getDeptGroupFk()
  {
    return (BigDecimal) getAttributeInternal(DEPTGROUPFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DeptGroupFk.
   * @param value value to set the  DeptGroupFk
   */
  public void setDeptGroupFk(BigDecimal value)
  {
    setAttributeInternal(DEPTGROUPFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDeptGroupFk.
   * @return the DisplayDeptGroupFk
   */
  public String getDisplayDeptGroupFk()
  {
    return (String) getAttributeInternal(DISPLAYDEPTGROUPFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDeptGroupFk.
   * @param value value to set the  DisplayDeptGroupFk
   */
  public void setDisplayDeptGroupFk(String value)
  {
    setAttributeInternal(DISPLAYDEPTGROUPFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute LetterTemplatesFK.
   * @return the LetterTemplatesFK
   */
  public BigDecimal getLetterTemplatesFK()
  {
    return (BigDecimal) getAttributeInternal(LETTERTEMPLATESFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute LetterTemplatesFK.
   * @param value value to set the  LetterTemplatesFK
   */
  public void setLetterTemplatesFK(BigDecimal value)
  {
    setAttributeInternal(LETTERTEMPLATESFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayLetterTemplatesFk.
   * @return the DisplayLetterTemplatesFk
   */
  public String getDisplayLetterTemplatesFk()
  {
    return (String) getAttributeInternal(DISPLAYLETTERTEMPLATESFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayLetterTemplatesFk.
   * @param value value to set the  DisplayLetterTemplatesFk
   */
  public void setDisplayLetterTemplatesFk(String value)
  {
    setAttributeInternal(DISPLAYLETTERTEMPLATESFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DepartmentsFk.
   * @return the DepartmentsFk
   */
  public BigDecimal getDepartmentsFk()
  {
    return (BigDecimal) getAttributeInternal(DEPARTMENTSFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DepartmentsFk.
   * @param value value to set the  DepartmentsFk
   */
  public void setDepartmentsFk(BigDecimal value)
  {
    setAttributeInternal(DEPARTMENTSFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayDepartmentsFk.
   * @return the DisplayDepartmentsFk
   */
  public String getDisplayDepartmentsFk()
  {
    return (String) getAttributeInternal(DISPLAYDEPARTMENTSFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayDepartmentsFk.
   * @param value value to set the  DisplayDepartmentsFk
   */
  public void setDisplayDepartmentsFk(String value)
  {
    setAttributeInternal(DISPLAYDEPARTMENTSFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute EmployeeFk.
   * @return the EmployeeFk
   */
  public BigDecimal getEmployeeFk()
  {
    return (BigDecimal) getAttributeInternal(EMPLOYEEFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute EmployeeFk.
   * @param value value to set the  EmployeeFk
   */
  public void setEmployeeFk(BigDecimal value)
  {
    setAttributeInternal(EMPLOYEEFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DisplayEmployeeFk.
   * @return the DisplayEmployeeFk
   */
  public String getDisplayEmployeeFk()
  {
    return (String) getAttributeInternal(DISPLAYEMPLOYEEFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DisplayEmployeeFk.
   * @param value value to set the  DisplayEmployeeFk
   */
  public void setDisplayEmployeeFk(String value)
  {
    setAttributeInternal(DISPLAYEMPLOYEEFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute Guidance.
   * @return the Guidance
   */
  public String getGuidance()
  {
    return (String) getAttributeInternal(GUIDANCE);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute Guidance.
   * @param value value to set the  Guidance
   */
  public void setGuidance(String value)
  {
    setAttributeInternal(GUIDANCE, value);
  }

  /**
   * Gets the attribute value for the calculated attribute InsideDepartment.
   * @return the InsideDepartment
   */
  public BigDecimal getInsideDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(INSIDEDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute InsideDepartmentFk.
   * @param value value to set the  InsideDepartmentFk
   */
  public void setInsideDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(INSIDEDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DispalyInsideDepartmentFk.
   * @return the DispalyInsideDepartmentFk
   */
  public String getDispalyInsideDepartmentFk()
  {
    return (String) getAttributeInternal(DISPALYINSIDEDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DispalyInsideDepartmentFk.
   * @param value value to set the  DispalyInsideDepartmentFk
   */
  public void setDispalyInsideDepartmentFk(String value)
  {
    setAttributeInternal(DISPALYINSIDEDEPARTMENTFK, value);
  }

  /**
   * Gets the view accessor <code>RowSet</code> SsoActiveLookupValuesVwView1.
   */
  public RowSet getSsoActiveLookupValuesVwView1()
  {
    return (RowSet) getAttributeInternal(SSOACTIVELOOKUPVALUESVWVIEW1);
  }

  /**
   * Gets the view accessor <code>RowSet</code> HcmDepartmentsFromDepartmentFk.
   */
  public RowSet getHcmDepartmentsFromDepartmentFk()
  {
    return (RowSet) getAttributeInternal(HCMDEPARTMENTSFROMDEPARTMENTFK);
  }

  /**
   * Gets the view accessor <code>RowSet</code> HcmDepartmentsToDepartmentFk.
   */
  public RowSet getHcmDepartmentsToDepartmentFk()
  {
    return (RowSet) getAttributeInternal(HCMDEPARTMENTSTODEPARTMENTFK);
  }

  /**
   * Gets the view accessor <code>RowSet</code> SsoSystemLookupValuesPriorityFk.
   */
  public RowSet getSsoSystemLookupValuesPriorityFk()
  {
    return (RowSet) getAttributeInternal(SSOSYSTEMLOOKUPVALUESPRIORITYFK);
  }

  /**
   * Gets the view accessor <code>RowSet</code> SsoSystemLookupValuesSecurityLevelFk.
   */
  public RowSet getSsoSystemLookupValuesSecurityLevelFk()
  {
    return (RowSet) getAttributeInternal(SSOSYSTEMLOOKUPVALUESSECURITYLEVELFK);
  }

  /**
   * Gets the view accessor <code>RowSet</code> SsoSystemLookupValuesInDocTypeFk.
   */
  public RowSet getSsoSystemLookupValuesInDocTypeFk()
  {
    return (RowSet) getAttributeInternal(SSOSYSTEMLOOKUPVALUESINDOCTYPEFK);
  }

  /**
   * Gets the view accessor <code>RowSet</code> SsoSystemLookupValuesActionFk.
   */
  public RowSet getSsoSystemLookupValuesActionFk()
  {
    return (RowSet) getAttributeInternal(SSOSYSTEMLOOKUPVALUESACTIONFK);
  }

  /**
   * Gets the view accessor <code>RowSet</code> CrsDeptGroupRVO.
   */
  public RowSet getCrsDeptGroupRVO()
  {
    return (RowSet) getAttributeInternal(CRSDEPTGROUPRVO);
  }

  /**
   * Gets the view accessor <code>RowSet</code> CrsLetterTemplatesView.
   */
  public RowSet getCrsLetterTemplatesView()
  {
    return (RowSet) getAttributeInternal(CRSLETTERTEMPLATESVIEW);
  }

  /**
   * Gets the view accessor <code>RowSet</code> DeparmentsRVODeptPk.
   */
  public RowSet getDeparmentsRVODeptPk()
  {
    return (RowSet) getAttributeInternal(DEPARMENTSRVODEPTPK);
  }

  /**
   * Gets the view accessor <code>RowSet</code> HcmEmpBasicDataVw1.
   */
  public RowSet getHcmEmpBasicDataVw1()
  {
    return (RowSet) getAttributeInternal(HCMEMPBASICDATAVW1);
  }

  /**
   * Gets the view accessor <code>RowSet</code> DeparmentsRVOInsideDept.
   */
  public RowSet getDeparmentsRVOInsideDept()
  {
    return (RowSet) getAttributeInternal(DEPARMENTSRVOINSIDEDEPT);
  }
}

