package crs.model;


import crs.model.ro.CrsDeptGroupRVOImpl;
import crs.model.ro.DeliverySelectedDocumentsPVOImpl;
import crs.model.ro.DeliveryStatmentAttachPVOImpl;
import crs.model.ro.EmailAttachRoImpl;
import crs.model.ro.EntryCountOutgoingDocViewImpl;
import crs.model.ro.HcmEmpBasicDataVwImpl;
import crs.model.vo.CrsIncomingDocumentsViewImpl;

import gen.common.BaseAppModuleImpl; 
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Apr 01 13:35:56 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl
  extends BaseAppModuleImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public AppModuleImpl()
  {
  }

  /**
   * Container's getter for CrsAllowedSendDepartmentsView1.
   * @return CrsAllowedSendDepartmentsView1
   */
  public ViewObjectImpl getCrsAllowedSendDepartmentsView1()
  {
    return (ViewObjectImpl) findViewObject("CrsAllowedSendDepartmentsView1");
  }

  /**
   * Container's getter for CrsAuditModificationsView1.
   * @return CrsAuditModificationsView1
   */
  public ViewObjectImpl getCrsAuditModificationsView1()
  {
    return (ViewObjectImpl) findViewObject("CrsAuditModificationsView1");
  }

  /**
   * Container's getter for CrsBeneficiariesTlView1.
   * @return CrsBeneficiariesTlView1
   */
  public ViewObjectImpl getCrsBeneficiariesTlView1()
  {
    return (ViewObjectImpl) findViewObject("CrsBeneficiariesTlView1");
  }

  /**
   * Container's getter for CrsBeneficiariesView1.
   * @return CrsBeneficiariesView1
   */
  public ViewObjectImpl getCrsBeneficiariesView1()
  {
    return (ViewObjectImpl) findViewObject("CrsBeneficiariesView1");
  }

  /**
   * Container's getter for CrsBorrowRequestsTlView1.
   * @return CrsBorrowRequestsTlView1
   */
  public ViewObjectImpl getCrsBorrowRequestsTlView1()
  {
    return (ViewObjectImpl) findViewObject("CrsBorrowRequestsTlView1");
  }

  /**
   * Container's getter for CrsBorrowRequestsView1.
   * @return CrsBorrowRequestsView1
   */
  public ViewObjectImpl getCrsBorrowRequestsView1()
  {
    return (ViewObjectImpl) findViewObject("CrsBorrowRequestsView1");
  }

  /**
   * Container's getter for CrsDocumentsDeliveryView1.
   * @return CrsDocumentsDeliveryView1
   */
  public ViewObjectImpl getCrsDocumentsDeliveryView1()
  {
    return (ViewObjectImpl) findViewObject("CrsDocumentsDeliveryView1");
  }

  /**
   * Container's getter for CrsFilesLocationTlView1.
   * @return CrsFilesLocationTlView1
   */
  public ViewObjectImpl getCrsFilesLocationTlView1()
  {
    return (ViewObjectImpl) findViewObject("CrsFilesLocationTlView1");
  }

  /**
   * Container's getter for CrsFilesLocationView1.
   * @return CrsFilesLocationView1
   */
  public ViewObjectImpl getCrsFilesLocationView1()
  {
    return (ViewObjectImpl) findViewObject("CrsFilesLocationView1");
  }

  /**
   * Container's getter for CrsIncomingArchiveTlView1.
   * @return CrsIncomingArchiveTlView1
   */
  public ViewObjectImpl getCrsIncomingArchiveTlView1()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingArchiveTlView1");
  }

  /**
   * Container's getter for CrsIncomingArchiveView1.
   * @return CrsIncomingArchiveView1
   */
  public ViewObjectImpl getCrsIncomingArchiveView1()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingArchiveView1");
  }

  /**
   * Container's getter for CrsIncomingBeneficiariesView1.
   * @return CrsIncomingBeneficiariesView1
   */
  public ViewObjectImpl getCrsIncomingBeneficiariesView1()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingBeneficiariesView1");
  }

  /**
   * Container's getter for CrsIncomingCommentsTlView1.
   * @return CrsIncomingCommentsTlView1
   */
  public ViewObjectImpl getCrsIncomingCommentsTlView1()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingCommentsTlView1");
  }

  /**
   * Container's getter for CrsIncomingCommentsView1.
   * @return CrsIncomingCommentsView1
   */
  public ViewObjectImpl getCrsIncomingCommentsView1()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingCommentsView1");
  }

  /**
   * Container's getter for CrsIncomingDocAttachTlView1.
   * @return CrsIncomingDocAttachTlView1
   */
  public ViewObjectImpl getCrsIncomingDocAttachTlView1()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingDocAttachTlView1");
  }

  /**
   * Container's getter for CrsIncomingDocAttachmentsView1.
   * @return CrsIncomingDocAttachmentsView1
   */
  public ViewObjectImpl getCrsIncomingDocAttachmentsView1()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingDocAttachmentsView1");
  }

  /**
   * Container's getter for CrsIncomingDocCcView1.
   * @return CrsIncomingDocCcView1
   */
  public ViewObjectImpl getCrsIncomingDocCcView1()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingDocCcView1");
  }

  /**
   * Container's getter for CrsIncomingDocumentsTlView1.
   * @return CrsIncomingDocumentsTlView1
   */
  public ViewObjectImpl getCrsIncomingDocumentsTlView1()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingDocumentsTlView1");
  }

  /**
   * Container's getter for CrsIncomingDocumentsView1.
   * @return CrsIncomingDocumentsView1
   */
  public CrsIncomingDocumentsViewImpl getCrsIncomingDocumentsView1()
  {
    return (CrsIncomingDocumentsViewImpl) findViewObject("CrsIncomingDocumentsView1");
  }

  /**
   * Container's getter for CrsIncomingRelatedLettersView1.
   * @return CrsIncomingRelatedLettersView1
   */
  public ViewObjectImpl getCrsIncomingRelatedLettersView1()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingRelatedLettersView1");
  }

  /**
   * Container's getter for CrsOutgoingArchiveTlView1.
   * @return CrsOutgoingArchiveTlView1
   */
  public ViewObjectImpl getCrsOutgoingArchiveTlView1()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingArchiveTlView1");
  }

  /**
   * Container's getter for CrsOutgoingArchiveView1.
   * @return CrsOutgoingArchiveView1
   */
  public ViewObjectImpl getCrsOutgoingArchiveView1()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingArchiveView1");
  }

  /**
   * Container's getter for CrsOutgoingBeneficiariesView1.
   * @return CrsOutgoingBeneficiariesView1
   */
  public ViewObjectImpl getCrsOutgoingBeneficiariesView1()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingBeneficiariesView1");
  }

  /**
   * Container's getter for CrsOutgoingCommentsTlView1.
   * @return CrsOutgoingCommentsTlView1
   */
  public ViewObjectImpl getCrsOutgoingCommentsTlView1()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingCommentsTlView1");
  }

  /**
   * Container's getter for CrsOutgoingCommentsView1.
   * @return CrsOutgoingCommentsView1
   */
  public ViewObjectImpl getCrsOutgoingCommentsView1()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingCommentsView1");
  }

  /**
   * Container's getter for CrsOutgoingDocAttachTlView1.
   * @return CrsOutgoingDocAttachTlView1
   */
  public ViewObjectImpl getCrsOutgoingDocAttachTlView1()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocAttachTlView1");
  }

  /**
   * Container's getter for CrsOutgoingDocAttachmentsView1.
   * @return CrsOutgoingDocAttachmentsView1
   */
  public ViewObjectImpl getCrsOutgoingDocAttachmentsView1()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocAttachmentsView1");
  }

  /**
   * Container's getter for CrsOutgoingDocCcView1.
   * @return CrsOutgoingDocCcView1
   */
  public ViewObjectImpl getCrsOutgoingDocCcView1()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocCcView1");
  }

  /**
   * Container's getter for CrsOutgoingDocPreTlView1.
   * @return CrsOutgoingDocPreTlView1
   */
  public ViewObjectImpl getCrsOutgoingDocPreTlView1()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocPreTlView1");
  }

  /**
   * Container's getter for CrsOutgoingDocPreparationView1.
   * @return CrsOutgoingDocPreparationView1
   */
  public ViewObjectImpl getCrsOutgoingDocPreparationView1()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocPreparationView1");
  }

  /**
   * Container's getter for CrsOutgoingDocumentsTlView1.
   * @return CrsOutgoingDocumentsTlView1
   */
  public ViewObjectImpl getCrsOutgoingDocumentsTlView1()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocumentsTlView1");
  }

  /**
   * Container's getter for CrsOutgoingDocumentsView1.
   * @return CrsOutgoingDocumentsView1
   */
  public ViewObjectImpl getCrsOutgoingDocumentsView1()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocumentsView1");
  }

  /**
   * Container's getter for CrsOutgoingRelatedLettersView1.
   * @return CrsOutgoingRelatedLettersView1
   */
  public ViewObjectImpl getCrsOutgoingRelatedLettersView1()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingRelatedLettersView1");
  }

  /**
   * Container's getter for ArchiveVwView1.
   * @return ArchiveVwView1
   */
  public ViewObjectImpl getArchiveVwView1()
  {
    return (ViewObjectImpl) findViewObject("ArchiveVwView1");
  }

  /**
   * Container's getter for AttachmentsVwView1.
   * @return AttachmentsVwView1
   */
  public ViewObjectImpl getAttachmentsVwView1()
  {
    return (ViewObjectImpl) findViewObject("AttachmentsVwView1");
  }

  /**
   * Container's getter for BeneficiariesVwView1.
   * @return BeneficiariesVwView1
   */
  public ViewObjectImpl getBeneficiariesVwView1()
  {
    return (ViewObjectImpl) findViewObject("BeneficiariesVwView1");
  }

  /**
   * Container's getter for DocumentBeneficiariesVwView1.
   * @return DocumentBeneficiariesVwView1
   */
  public ViewObjectImpl getDocumentBeneficiariesVwView1()
  {
    return (ViewObjectImpl) findViewObject("DocumentBeneficiariesVwView1");
  }

  /**
   * Container's getter for DocumentVwView1.
   * @return DocumentVwView1
   */
  public ViewObjectImpl getDocumentVwView1()
  {
    return (ViewObjectImpl) findViewObject("DocumentVwView1");
  }

  /**
   * Container's getter for DocCcVwView1.
   * @return DocCcVwView1
   */
  public ViewObjectImpl getDocCcVwView1()
  {
    return (ViewObjectImpl) findViewObject("DocCcVwView1");
  }

  /**
   * Container's getter for RelatedLettersVwView1.
   * @return RelatedLettersVwView1
   */
  public ViewObjectImpl getRelatedLettersVwView1()
  {
    return (ViewObjectImpl) findViewObject("RelatedLettersVwView1");
  }

  /**
   * Container's getter for CrsBeneficiariesTlView2.
   * @return CrsBeneficiariesTlView2
   */
  public ViewObjectImpl getCrsBeneficiariesTlView2()
  {
    return (ViewObjectImpl) findViewObject("CrsBeneficiariesTlView2");
  }

  /**
   * Container's getter for CrsBorrowRequestsTlView2.
   * @return CrsBorrowRequestsTlView2
   */
  public ViewObjectImpl getCrsBorrowRequestsTlView2()
  {
    return (ViewObjectImpl) findViewObject("CrsBorrowRequestsTlView2");
  }

  /**
   * Container's getter for CrsFilesLocationView2.
   * @return CrsFilesLocationView2
   */
  public ViewObjectImpl getCrsFilesLocationView2()
  {
    return (ViewObjectImpl) findViewObject("CrsFilesLocationView2");
  }

  /**
   * Container's getter for CrsFilesLocationTlView2.
   * @return CrsFilesLocationTlView2
   */
  public ViewObjectImpl getCrsFilesLocationTlView2()
  {
    return (ViewObjectImpl) findViewObject("CrsFilesLocationTlView2");
  }

  /**
   * Container's getter for CrsIncomingArchiveTlView2.
   * @return CrsIncomingArchiveTlView2
   */
  public ViewObjectImpl getCrsIncomingArchiveTlView2()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingArchiveTlView2");
  }

  /**
   * Container's getter for CrsIncomingBeneficiariesView2.
   * @return CrsIncomingBeneficiariesView2
   */
  public ViewObjectImpl getCrsIncomingBeneficiariesView2()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingBeneficiariesView2");
  }

  /**
   * Container's getter for CrsIncomingCommentsTlView2.
   * @return CrsIncomingCommentsTlView2
   */
  public ViewObjectImpl getCrsIncomingCommentsTlView2()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingCommentsTlView2");
  }

  /**
   * Container's getter for CrsIncomingCommentsView2.
   * @return CrsIncomingCommentsView2
   */
  public ViewObjectImpl getCrsIncomingCommentsView2()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingCommentsView2");
  }

  /**
   * Container's getter for CrsIncomingArchiveView2.
   * @return CrsIncomingArchiveView2
   */
  public ViewObjectImpl getCrsIncomingArchiveView2()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingArchiveView2");
  }

  /**
   * Container's getter for CrsIncomingBeneficiariesView3.
   * @return CrsIncomingBeneficiariesView3
   */
  public ViewObjectImpl getCrsIncomingBeneficiariesView3()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingBeneficiariesView3");
  }

  /**
   * Container's getter for CrsDocumentsDeliveryView2.
   * @return CrsDocumentsDeliveryView2
   */
  public ViewObjectImpl getCrsDocumentsDeliveryView2()
  {
    return (ViewObjectImpl) findViewObject("CrsDocumentsDeliveryView2");
  }

  /**
   * Container's getter for CrsBorrowRequestsView2.
   * @return CrsBorrowRequestsView2
   */
  public ViewObjectImpl getCrsBorrowRequestsView2()
  {
    return (ViewObjectImpl) findViewObject("CrsBorrowRequestsView2");
  }

  /**
   * Container's getter for CrsIncomingDocumentsView2.
   * @return CrsIncomingDocumentsView2
   */
  public CrsIncomingDocumentsViewImpl getCrsIncomingDocumentsView2()
  {
    return (CrsIncomingDocumentsViewImpl) findViewObject("CrsIncomingDocumentsView2");
  }

  /**
   * Container's getter for CrsIncomingDocumentsTlView2.
   * @return CrsIncomingDocumentsTlView2
   */
  public ViewObjectImpl getCrsIncomingDocumentsTlView2()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingDocumentsTlView2");
  }

  /**
   * Container's getter for CrsIncomingDocAttachmentsView2.
   * @return CrsIncomingDocAttachmentsView2
   */
  public ViewObjectImpl getCrsIncomingDocAttachmentsView2()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingDocAttachmentsView2");
  }

  /**
   * Container's getter for CrsIncomingDocAttachTlView2.
   * @return CrsIncomingDocAttachTlView2
   */
  public ViewObjectImpl getCrsIncomingDocAttachTlView2()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingDocAttachTlView2");
  }

  /**
   * Container's getter for CrsIncomingDocCcView2.
   * @return CrsIncomingDocCcView2
   */
  public ViewObjectImpl getCrsIncomingDocCcView2()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingDocCcView2");
  }

  /**
   * Container's getter for CrsIncomingRelatedLettersView2.
   * @return CrsIncomingRelatedLettersView2
   */
  public ViewObjectImpl getCrsIncomingRelatedLettersView2()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingRelatedLettersView2");
  }

  /**
   * Container's getter for CrsIncomingRelatedLettersView3.
   * @return CrsIncomingRelatedLettersView3
   */
  public ViewObjectImpl getCrsIncomingRelatedLettersView3()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingRelatedLettersView3");
  }

  /**
   * Container's getter for CrsOutgoingArchiveTlView2.
   * @return CrsOutgoingArchiveTlView2
   */
  public ViewObjectImpl getCrsOutgoingArchiveTlView2()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingArchiveTlView2");
  }

  /**
   * Container's getter for CrsOutgoingBeneficiariesView2.
   * @return CrsOutgoingBeneficiariesView2
   */
  public ViewObjectImpl getCrsOutgoingBeneficiariesView2()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingBeneficiariesView2");
  }

  /**
   * Container's getter for CrsOutgoingCommentsTlView2.
   * @return CrsOutgoingCommentsTlView2
   */
  public ViewObjectImpl getCrsOutgoingCommentsTlView2()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingCommentsTlView2");
  }

  /**
   * Container's getter for CrsOutgoingBeneficiariesView3.
   * @return CrsOutgoingBeneficiariesView3
   */
  public ViewObjectImpl getCrsOutgoingBeneficiariesView3()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingBeneficiariesView3");
  }

  /**
   * Container's getter for CrsDocumentsDeliveryView3.
   * @return CrsDocumentsDeliveryView3
   */
  public ViewObjectImpl getCrsDocumentsDeliveryView3()
  {
    return (ViewObjectImpl) findViewObject("CrsDocumentsDeliveryView3");
  }

  /**
   * Container's getter for CrsBorrowRequestsView3.
   * @return CrsBorrowRequestsView3
   */
  public ViewObjectImpl getCrsBorrowRequestsView3()
  {
    return (ViewObjectImpl) findViewObject("CrsBorrowRequestsView3");
  }

  /**
   * Container's getter for CrsOutgoingArchiveView2.
   * @return CrsOutgoingArchiveView2
   */
  public ViewObjectImpl getCrsOutgoingArchiveView2()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingArchiveView2");
  }

  /**
   * Container's getter for CrsIncomingDocumentsView3.
   * @return CrsIncomingDocumentsView3
   */
  public CrsIncomingDocumentsViewImpl getCrsIncomingDocumentsView3()
  {
    return (CrsIncomingDocumentsViewImpl) findViewObject("CrsIncomingDocumentsView3");
  }

  /**
   * Container's getter for CrsIncomingRelatedLettersView4.
   * @return CrsIncomingRelatedLettersView4
   */
  public ViewObjectImpl getCrsIncomingRelatedLettersView4()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingRelatedLettersView4");
  }

  /**
   * Container's getter for CrsOutgoingCommentsView2.
   * @return CrsOutgoingCommentsView2
   */
  public ViewObjectImpl getCrsOutgoingCommentsView2()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingCommentsView2");
  }

  /**
   * Container's getter for CrsOutgoingDocumentsView2.
   * @return CrsOutgoingDocumentsView2
   */
  public ViewObjectImpl getCrsOutgoingDocumentsView2()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocumentsView2");
  }

  /**
   * Container's getter for CrsOutgoingDocumentsView3.
   * @return CrsOutgoingDocumentsView3
   */
  public ViewObjectImpl getCrsOutgoingDocumentsView3()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocumentsView3");
  }

  /**
   * Container's getter for CrsOutgoingDocumentsTlView2.
   * @return CrsOutgoingDocumentsTlView2
   */
  public ViewObjectImpl getCrsOutgoingDocumentsTlView2()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocumentsTlView2");
  }

  /**
   * Container's getter for CrsOutgoingDocAttachmentsView2.
   * @return CrsOutgoingDocAttachmentsView2
   */
  public ViewObjectImpl getCrsOutgoingDocAttachmentsView2()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocAttachmentsView2");
  }

  /**
   * Container's getter for CrsOutgoingDocAttachTlView2.
   * @return CrsOutgoingDocAttachTlView2
   */
  public ViewObjectImpl getCrsOutgoingDocAttachTlView2()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocAttachTlView2");
  }

  /**
   * Container's getter for CrsOutgoingDocCcView2.
   * @return CrsOutgoingDocCcView2
   */
  public ViewObjectImpl getCrsOutgoingDocCcView2()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocCcView2");
  }

  /**
   * Container's getter for CrsOutgoingBeneficiariesView4.
   * @return CrsOutgoingBeneficiariesView4
   */
  public ViewObjectImpl getCrsOutgoingBeneficiariesView4()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingBeneficiariesView4");
  }

  /**
   * Container's getter for CrsOutgoingArchiveView3.
   * @return CrsOutgoingArchiveView3
   */
  public ViewObjectImpl getCrsOutgoingArchiveView3()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingArchiveView3");
  }

  /**
   * Container's getter for CrsOutgoingDocCcView3.
   * @return CrsOutgoingDocCcView3
   */
  public ViewObjectImpl getCrsOutgoingDocCcView3()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocCcView3");
  }

  /**
   * Container's getter for CrsOutgoingDocAttachmentsView3.
   * @return CrsOutgoingDocAttachmentsView3
   */
  public ViewObjectImpl getCrsOutgoingDocAttachmentsView3()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocAttachmentsView3");
  }

  /**
   * Container's getter for CrsOutgoingDocPreparationView2.
   * @return CrsOutgoingDocPreparationView2
   */
  public ViewObjectImpl getCrsOutgoingDocPreparationView2()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocPreparationView2");
  }

  /**
   * Container's getter for CrsOutgoingDocPreparationView3.
   * @return CrsOutgoingDocPreparationView3
   */
  public ViewObjectImpl getCrsOutgoingDocPreparationView3()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocPreparationView3");
  }

  /**
   * Container's getter for CrsOutgoingDocPreparationView4.
   * @return CrsOutgoingDocPreparationView4
   */
  public ViewObjectImpl getCrsOutgoingDocPreparationView4()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocPreparationView4");
  }

  /**
   * Container's getter for CrsOutgoingDocPreTlView2.
   * @return CrsOutgoingDocPreTlView2
   */
  public ViewObjectImpl getCrsOutgoingDocPreTlView2()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocPreTlView2");
  }

  /**
   * Container's getter for CrsOutgoingRelatedLettersView2.
   * @return CrsOutgoingRelatedLettersView2
   */
  public ViewObjectImpl getCrsOutgoingRelatedLettersView2()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingRelatedLettersView2");
  }


  /**
   * Container's getter for CrsOutgoingRelatedLettersView4.
   * @return CrsOutgoingRelatedLettersView4
   */
  public ViewObjectImpl getCrsOutgoingRelatedLettersView4()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingRelatedLettersView4");
  }

  /**
   * Container's getter for CrsOutgoingRelatedLettersView5.
   * @return CrsOutgoingRelatedLettersView5
   */
  public ViewObjectImpl getCrsOutgoingRelatedLettersView5()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingRelatedLettersView5");
  }

  /**
   * Container's getter for CrsBeneficiariesTlFkLink1.
   * @return CrsBeneficiariesTlFkLink1
   */
  public ViewLinkImpl getCrsBeneficiariesTlFkLink1()
  {
    return (ViewLinkImpl) findViewLink("CrsBeneficiariesTlFkLink1");
  }

  /**
   * Container's getter for CrsDocBorrowReqTlFk1Link1.
   * @return CrsDocBorrowReqTlFk1Link1
   */
  public ViewLinkImpl getCrsDocBorrowReqTlFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsDocBorrowReqTlFk1Link1");
  }

  /**
   * Container's getter for CrsFilesLocationFk1Link1.
   * @return CrsFilesLocationFk1Link1
   */
  public ViewLinkImpl getCrsFilesLocationFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsFilesLocationFk1Link1");
  }

  /**
   * Container's getter for CrsFilesLocationTlFk1Link1.
   * @return CrsFilesLocationTlFk1Link1
   */
  public ViewLinkImpl getCrsFilesLocationTlFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsFilesLocationTlFk1Link1");
  }

  /**
   * Container's getter for CrsIncomingArchiveTlFk1Link1.
   * @return CrsIncomingArchiveTlFk1Link1
   */
  public ViewLinkImpl getCrsIncomingArchiveTlFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsIncomingArchiveTlFk1Link1");
  }

  /**
   * Container's getter for CrsIncomingBeneficiarieFk2Link1.
   * @return CrsIncomingBeneficiarieFk2Link1
   */
  public ViewLinkImpl getCrsIncomingBeneficiarieFk2Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsIncomingBeneficiarieFk2Link1");
  }

  /**
   * Container's getter for CrsIncomingCommentsTlFk1Link1.
   * @return CrsIncomingCommentsTlFk1Link1
   */
  public ViewLinkImpl getCrsIncomingCommentsTlFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsIncomingCommentsTlFk1Link1");
  }

  /**
   * Container's getter for CrsIncomingCommentsFk1Link1.
   * @return CrsIncomingCommentsFk1Link1
   */
  public ViewLinkImpl getCrsIncomingCommentsFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsIncomingCommentsFk1Link1");
  }

  /**
   * Container's getter for CrsIncomingArchiveFk1Link1.
   * @return CrsIncomingArchiveFk1Link1
   */
  public ViewLinkImpl getCrsIncomingArchiveFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsIncomingArchiveFk1Link1");
  }

  /**
   * Container's getter for CrsIncomingBeneficiarieFk1Link1.
   * @return CrsIncomingBeneficiarieFk1Link1
   */
  public ViewLinkImpl getCrsIncomingBeneficiarieFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsIncomingBeneficiarieFk1Link1");
  }

  /**
   * Container's getter for CrsDocumentsDeliveryFk1Link1.
   * @return CrsDocumentsDeliveryFk1Link1
   */
  public ViewLinkImpl getCrsDocumentsDeliveryFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsDocumentsDeliveryFk1Link1");
  }

  /**
   * Container's getter for CrsDocBorrowRequestsFk1Link1.
   * @return CrsDocBorrowRequestsFk1Link1
   */
  public ViewLinkImpl getCrsDocBorrowRequestsFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsDocBorrowRequestsFk1Link1");
  }

  /**
   * Container's getter for CrsIncomingDocumentsFk3Link1.
   * @return CrsIncomingDocumentsFk3Link1
   */
  public ViewLinkImpl getCrsIncomingDocumentsFk3Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsIncomingDocumentsFk3Link1");
  }

  /**
   * Container's getter for CrsIncomingDocumentsTlFk1Link1.
   * @return CrsIncomingDocumentsTlFk1Link1
   */
  public ViewLinkImpl getCrsIncomingDocumentsTlFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsIncomingDocumentsTlFk1Link1");
  }

  /**
   * Container's getter for CrsIncomingDocAttachmeFk1Link1.
   * @return CrsIncomingDocAttachmeFk1Link1
   */
  public ViewLinkImpl getCrsIncomingDocAttachmeFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsIncomingDocAttachmeFk1Link1");
  }

  /**
   * Container's getter for CrsIncomingDocAttachTFk1Link1.
   * @return CrsIncomingDocAttachTFk1Link1
   */
  public ViewLinkImpl getCrsIncomingDocAttachTFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsIncomingDocAttachTFk1Link1");
  }

  /**
   * Container's getter for CrsIncomingDocCcFk1Link1.
   * @return CrsIncomingDocCcFk1Link1
   */
  public ViewLinkImpl getCrsIncomingDocCcFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsIncomingDocCcFk1Link1");
  }

  /**
   * Container's getter for CrsIncomingRelatedLettFk1Link1.
   * @return CrsIncomingRelatedLettFk1Link1
   */
  public ViewLinkImpl getCrsIncomingRelatedLettFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsIncomingRelatedLettFk1Link1");
  }

  /**
   * Container's getter for CrsIncomingRelatedLettFk4Link1.
   * @return CrsIncomingRelatedLettFk4Link1
   */
  public ViewLinkImpl getCrsIncomingRelatedLettFk4Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsIncomingRelatedLettFk4Link1");
  }

  /**
   * Container's getter for CrsOutgoingArchiveTlFk1Link1.
   * @return CrsOutgoingArchiveTlFk1Link1
   */
  public ViewLinkImpl getCrsOutgoingArchiveTlFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingArchiveTlFk1Link1");
  }

  /**
   * Container's getter for CrsOutgoingBeneficiarieFk2Link1.
   * @return CrsOutgoingBeneficiarieFk2Link1
   */
  public ViewLinkImpl getCrsOutgoingBeneficiarieFk2Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingBeneficiarieFk2Link1");
  }

  /**
   * Container's getter for CrsOutgoingCommentsTlFk1Link1.
   * @return CrsOutgoingCommentsTlFk1Link1
   */
  public ViewLinkImpl getCrsOutgoingCommentsTlFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingCommentsTlFk1Link1");
  }

  /**
   * Container's getter for CrsOutgoingBeneficiarieFk1Link1.
   * @return CrsOutgoingBeneficiarieFk1Link1
   */
  public ViewLinkImpl getCrsOutgoingBeneficiarieFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingBeneficiarieFk1Link1");
  }

  /**
   * Container's getter for CrsDocumentsDeliveryFk2Link1.
   * @return CrsDocumentsDeliveryFk2Link1
   */
  public ViewLinkImpl getCrsDocumentsDeliveryFk2Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsDocumentsDeliveryFk2Link1");
  }

  /**
   * Container's getter for CrsBorrowRequestsFk1Link1.
   * @return CrsBorrowRequestsFk1Link1
   */
  public ViewLinkImpl getCrsBorrowRequestsFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsBorrowRequestsFk1Link1");
  }

  /**
   * Container's getter for CrsOutgoingArchiveFk1Link1.
   * @return CrsOutgoingArchiveFk1Link1
   */
  public ViewLinkImpl getCrsOutgoingArchiveFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingArchiveFk1Link1");
  }

  /**
   * Container's getter for CrsIncomingDocumentsFk6Link1.
   * @return CrsIncomingDocumentsFk6Link1
   */
  public ViewLinkImpl getCrsIncomingDocumentsFk6Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsIncomingDocumentsFk6Link1");
  }

  /**
   * Container's getter for CrsIncomingRelatedLettFk2Link1.
   * @return CrsIncomingRelatedLettFk2Link1
   */
  public ViewLinkImpl getCrsIncomingRelatedLettFk2Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsIncomingRelatedLettFk2Link1");
  }

  /**
   * Container's getter for CrsOutgoingCommentsFk1Link1.
   * @return CrsOutgoingCommentsFk1Link1
   */
  public ViewLinkImpl getCrsOutgoingCommentsFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingCommentsFk1Link1");
  }

  /**
   * Container's getter for CrsOutgoingDocumentsFk4Link1.
   * @return CrsOutgoingDocumentsFk4Link1
   */
  public ViewLinkImpl getCrsOutgoingDocumentsFk4Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingDocumentsFk4Link1");
  }

  /**
   * Container's getter for CrsOutgoingDocumentsFk8Link1.
   * @return CrsOutgoingDocumentsFk8Link1
   */
  public ViewLinkImpl getCrsOutgoingDocumentsFk8Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingDocumentsFk8Link1");
  }

  /**
   * Container's getter for CrsOutgoingDocumentsTlFk1Link1.
   * @return CrsOutgoingDocumentsTlFk1Link1
   */
  public ViewLinkImpl getCrsOutgoingDocumentsTlFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingDocumentsTlFk1Link1");
  }

  /**
   * Container's getter for CrsOutgoingDocAttachmeFk1Link1.
   * @return CrsOutgoingDocAttachmeFk1Link1
   */
  public ViewLinkImpl getCrsOutgoingDocAttachmeFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingDocAttachmeFk1Link1");
  }

  /**
   * Container's getter for CrsOutgoingDocAttachTFk2Link1.
   * @return CrsOutgoingDocAttachTFk2Link1
   */
  public ViewLinkImpl getCrsOutgoingDocAttachTFk2Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingDocAttachTFk2Link1");
  }

  /**
   * Container's getter for CrsOutgoingDocCcFk1Link1.
   * @return CrsOutgoingDocCcFk1Link1
   */
  public ViewLinkImpl getCrsOutgoingDocCcFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingDocCcFk1Link1");
  }

  /**
   * Container's getter for CrsOutgoingBeneficiarieFk3Link1.
   * @return CrsOutgoingBeneficiarieFk3Link1
   */
  public ViewLinkImpl getCrsOutgoingBeneficiarieFk3Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingBeneficiarieFk3Link1");
  }

  /**
   * Container's getter for CrsOutgoingArchiveFk3Link1.
   * @return CrsOutgoingArchiveFk3Link1
   */
  public ViewLinkImpl getCrsOutgoingArchiveFk3Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingArchiveFk3Link1");
  }

  /**
   * Container's getter for CrsOutgoingDocCcFk3Link1.
   * @return CrsOutgoingDocCcFk3Link1
   */
  public ViewLinkImpl getCrsOutgoingDocCcFk3Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingDocCcFk3Link1");
  }

  /**
   * Container's getter for CrsOutgoingDocAttachmeFk2Link1.
   * @return CrsOutgoingDocAttachmeFk2Link1
   */
  public ViewLinkImpl getCrsOutgoingDocAttachmeFk2Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingDocAttachmeFk2Link1");
  }

  /**
   * Container's getter for CrsOutgoingDocPreparatFk2Link1.
   * @return CrsOutgoingDocPreparatFk2Link1
   */
  public ViewLinkImpl getCrsOutgoingDocPreparatFk2Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingDocPreparatFk2Link1");
  }

  /**
   * Container's getter for CrsOutgoingDocPreparatFk5Link1.
   * @return CrsOutgoingDocPreparatFk5Link1
   */
  public ViewLinkImpl getCrsOutgoingDocPreparatFk5Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingDocPreparatFk5Link1");
  }

  /**
   * Container's getter for CrsOutgoingDocPreparatFk7Link1.
   * @return CrsOutgoingDocPreparatFk7Link1
   */
  public ViewLinkImpl getCrsOutgoingDocPreparatFk7Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingDocPreparatFk7Link1");
  }

  /**
   * Container's getter for CrsOutgoingDocPreTlFk1Link1.
   * @return CrsOutgoingDocPreTlFk1Link1
   */
  public ViewLinkImpl getCrsOutgoingDocPreTlFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingDocPreTlFk1Link1");
  }

  /**
   * Container's getter for CrsOutgoingRelatedLettFk1Link1.
   * @return CrsOutgoingRelatedLettFk1Link1
   */
  public ViewLinkImpl getCrsOutgoingRelatedLettFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingRelatedLettFk1Link1");
  }


  /**
   * Container's getter for CrsOutgoingRelatedLettFk3Link1.
   * @return CrsOutgoingRelatedLettFk3Link1
   */
  public ViewLinkImpl getCrsOutgoingRelatedLettFk3Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingRelatedLettFk3Link1");
  }

  /**
   * Container's getter for CrsOutgoingRelatedLettFk4Link1.
   * @return CrsOutgoingRelatedLettFk4Link1
   */
  public ViewLinkImpl getCrsOutgoingRelatedLettFk4Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingRelatedLettFk4Link1");
  }

  /**
   * Container's getter for HcmDepartmentsVwView1.
   * @return HcmDepartmentsVwView1
   */
  public ViewObjectImpl getHcmDepartmentsVwView1()
  {
    return (ViewObjectImpl) findViewObject("HcmDepartmentsVwView1");
  }

  /**
   * Container's getter for CrsAllowedSendDepartmentsView2.
   * @return CrsAllowedSendDepartmentsView2
   */
  public ViewObjectImpl getCrsAllowedSendDepartmentsView2()
  {
    return (ViewObjectImpl) findViewObject("CrsAllowedSendDepartmentsView2");
  }

  /**
   * Container's getter for DepartmentsAllowedSendDepartments1.
   * @return DepartmentsAllowedSendDepartments1
   */
  public ViewLinkImpl getDepartmentsAllowedSendDepartments1()
  {
    return (ViewLinkImpl) findViewLink("DepartmentsAllowedSendDepartments1");
  }

  /**
   * Container's getter for CrsFilesLocationView3.
   * @return CrsFilesLocationView3
   */
  public ViewObjectImpl getCrsFilesLocationView3()
  {
    return (ViewObjectImpl) findViewObject("CrsFilesLocationView3");
  }

  /**
   * Container's getter for DepartmentsFileLocationVL1.
   * @return DepartmentsFileLocationVL1
   */
  public ViewLinkImpl getDepartmentsFileLocationVL1()
  {
    return (ViewLinkImpl) findViewLink("DepartmentsFileLocationVL1");
  }

  /**
   * Container's getter for CrsFilesLocationTlView3.
   * @return CrsFilesLocationTlView3
   */
  public ViewObjectImpl getCrsFilesLocationTlView3()
  {
    return (ViewObjectImpl) findViewObject("CrsFilesLocationTlView3");
  }

  /**
   * Container's getter for CrsFilesLocationTlFk1Link2.
   * @return CrsFilesLocationTlFk1Link2
   */
  public ViewLinkImpl getCrsFilesLocationTlFk1Link2()
  {
    return (ViewLinkImpl) findViewLink("CrsFilesLocationTlFk1Link2");
  }

  /**
   * Container's getter for ArchiveVwView2.
   * @return ArchiveVwView2
   */
  public ViewObjectImpl getArchiveVwView2()
  {
    return (ViewObjectImpl) findViewObject("ArchiveVwView2");
  }

  /**
   * Container's getter for DocumentsVwArchiveVl1.
   * @return DocumentsVwArchiveVl1
   */
  public ViewLinkImpl getDocumentsVwArchiveVl1()
  {
    return (ViewLinkImpl) findViewLink("DocumentsVwArchiveVl1");
  }

  /**
   * Container's getter for AttachmentsVwView2.
   * @return AttachmentsVwView2
   */
  public ViewObjectImpl getAttachmentsVwView2()
  {
    return (ViewObjectImpl) findViewObject("AttachmentsVwView2");
  }

  /**
   * Container's getter for DocumentsVwAttachmentsVl1.
   * @return DocumentsVwAttachmentsVl1
   */
  public ViewLinkImpl getDocumentsVwAttachmentsVl1()
  {
    return (ViewLinkImpl) findViewLink("DocumentsVwAttachmentsVl1");
  }

  /**
   * Container's getter for BeneficiariesVwView2.
   * @return BeneficiariesVwView2
   */
  public ViewObjectImpl getBeneficiariesVwView2()
  {
    return (ViewObjectImpl) findViewObject("BeneficiariesVwView2");
  }

  /**
   * Container's getter for DocumentsVwBeneficiariesVl1.
   * @return DocumentsVwBeneficiariesVl1
   */
  public ViewLinkImpl getDocumentsVwBeneficiariesVl1()
  {
    return (ViewLinkImpl) findViewLink("DocumentsVwBeneficiariesVl1");
  }

  /**
   * Container's getter for DocCcVwView2.
   * @return DocCcVwView2
   */
  public ViewObjectImpl getDocCcVwView2()
  {
    return (ViewObjectImpl) findViewObject("DocCcVwView2");
  }

  /**
   * Container's getter for DocumentsVwDocCCVl1.
   * @return DocumentsVwDocCCVl1
   */
  public ViewLinkImpl getDocumentsVwDocCCVl1()
  {
    return (ViewLinkImpl) findViewLink("DocumentsVwDocCCVl1");
  }

  /**
   * Container's getter for RelatedLettersVwView2.
   * @return RelatedLettersVwView2
   */
  public ViewObjectImpl getRelatedLettersVwView2()
  {
    return (ViewObjectImpl) findViewObject("RelatedLettersVwView2");
  }

  /**
   * Container's getter for DocumentsVwRelatedLettersVl1.
   * @return DocumentsVwRelatedLettersVl1
   */
  public ViewLinkImpl getDocumentsVwRelatedLettersVl1()
  {
    return (ViewLinkImpl) findViewLink("DocumentsVwRelatedLettersVl1");
  }

  /**
   * Container's getter for ArchiveVwView3.
   * @return ArchiveVwView3
   */
  public ViewObjectImpl getArchiveVwView3()
  {
    return (ViewObjectImpl) findViewObject("ArchiveVwView3");
  }

  /**
   * Container's getter for DocumentBeneficiariesVwArchiveVl1.
   * @return DocumentBeneficiariesVwArchiveVl1
   */
  public ViewLinkImpl getDocumentBeneficiariesVwArchiveVl1()
  {
    return (ViewLinkImpl) findViewLink("DocumentBeneficiariesVwArchiveVl1");
  }

  /**
   * Container's getter for AttachmentsVwView3.
   * @return AttachmentsVwView3
   */
  public ViewObjectImpl getAttachmentsVwView3()
  {
    return (ViewObjectImpl) findViewObject("AttachmentsVwView3");
  }

  /**
   * Container's getter for DocumentBeneficiariesVwAttachmentsVl1.
   * @return DocumentBeneficiariesVwAttachmentsVl1
   */
  public ViewLinkImpl getDocumentBeneficiariesVwAttachmentsVl1()
  {
    return (ViewLinkImpl) findViewLink("DocumentBeneficiariesVwAttachmentsVl1");
  }

  /**
   * Container's getter for DocCcVwView3.
   * @return DocCcVwView3
   */
  public ViewObjectImpl getDocCcVwView3()
  {
    return (ViewObjectImpl) findViewObject("DocCcVwView3");
  }

  /**
   * Container's getter for DocumentBeneficiariesVwDocCCVl1.
   * @return DocumentBeneficiariesVwDocCCVl1
   */
  public ViewLinkImpl getDocumentBeneficiariesVwDocCCVl1()
  {
    return (ViewLinkImpl) findViewLink("DocumentBeneficiariesVwDocCCVl1");
  }

  /**
   * Container's getter for RelatedLettersVwView3.
   * @return RelatedLettersVwView3
   */
  public ViewObjectImpl getRelatedLettersVwView3()
  {
    return (ViewObjectImpl) findViewObject("RelatedLettersVwView3");
  }

  /**
   * Container's getter for DocumentBeneficiariesVwRelatedLettersVl1.
   * @return DocumentBeneficiariesVwRelatedLettersVl1
   */
  public ViewLinkImpl getDocumentBeneficiariesVwRelatedLettersVl1()
  {
    return (ViewLinkImpl) findViewLink("DocumentBeneficiariesVwRelatedLettersVl1");
  }

  /**
   * Container's getter for BeneficiariesVwView3.
   * @return BeneficiariesVwView3
   */
  public ViewObjectImpl getBeneficiariesVwView3()
  {
    return (ViewObjectImpl) findViewObject("BeneficiariesVwView3");
  }

  /**
   * Container's getter for DocumentBeneficiariesVwBeneficiariesVl1.
   * @return DocumentBeneficiariesVwBeneficiariesVl1
   */
  public ViewLinkImpl getDocumentBeneficiariesVwBeneficiariesVl1()
  {
    return (ViewLinkImpl) findViewLink("DocumentBeneficiariesVwBeneficiariesVl1");
  }

  /**
   * Container's getter for CrsIncomingArchiveTlView3.
   * @return CrsIncomingArchiveTlView3
   */
  public ViewObjectImpl getCrsIncomingArchiveTlView3()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingArchiveTlView3");
  }

  /**
   * Container's getter for CrsIncomingArchiveTlFk1Link2.
   * @return CrsIncomingArchiveTlFk1Link2
   */
  public ViewLinkImpl getCrsIncomingArchiveTlFk1Link2()
  {
    return (ViewLinkImpl) findViewLink("CrsIncomingArchiveTlFk1Link2");
  }

  /**
   * Container's getter for CrsIncomingDocAttachTlView3.
   * @return CrsIncomingDocAttachTlView3
   */
  public ViewObjectImpl getCrsIncomingDocAttachTlView3()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingDocAttachTlView3");
  }

  /**
   * Container's getter for CrsIncomingDocAttachTFk1Link2.
   * @return CrsIncomingDocAttachTFk1Link2
   */
  public ViewLinkImpl getCrsIncomingDocAttachTFk1Link2()
  {
    return (ViewLinkImpl) findViewLink("CrsIncomingDocAttachTFk1Link2");
  }

    /**
     * Container's getter for CrsIncomingCommentsTlView3.
     * @return CrsIncomingCommentsTlView3
     */
    public ViewObjectImpl getCrsIncomingCommentsTlView3() {
        return (ViewObjectImpl) findViewObject("CrsIncomingCommentsTlView3");
    }

    /**
     * Container's getter for CrsIncomingCommentsTlFk1Link2.
     * @return CrsIncomingCommentsTlFk1Link2
     */
    public ViewLinkImpl getCrsIncomingCommentsTlFk1Link2() {
        return (ViewLinkImpl) findViewLink("CrsIncomingCommentsTlFk1Link2");
    }

  /**
   * Container's getter for CrsOutgoingArchiveTlView3.
   * @return CrsOutgoingArchiveTlView3
   */
  public ViewObjectImpl getCrsOutgoingArchiveTlView3()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingArchiveTlView3");
  }

  /**
   * Container's getter for CrsOutgoingArchiveTlFk1Link2.
   * @return CrsOutgoingArchiveTlFk1Link2
   */
  public ViewLinkImpl getCrsOutgoingArchiveTlFk1Link2()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingArchiveTlFk1Link2");
  }

  /**
   * Container's getter for CrsOutgoingDocAttachTlView3.
   * @return CrsOutgoingDocAttachTlView3
   */
  public ViewObjectImpl getCrsOutgoingDocAttachTlView3()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocAttachTlView3");
  }

  /**
   * Container's getter for CrsOutgoingDocAttachTFk2Link2.
   * @return CrsOutgoingDocAttachTFk2Link2
   */
  public ViewLinkImpl getCrsOutgoingDocAttachTFk2Link2()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingDocAttachTFk2Link2");
  }

  /**
   * Container's getter for CrsOutgoingCommentsTlView3.
   * @return CrsOutgoingCommentsTlView3
   */
  public ViewObjectImpl getCrsOutgoingCommentsTlView3()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingCommentsTlView3");
  }

  /**
   * Container's getter for CrsOutgoingCommentsTlFk1Link2.
   * @return CrsOutgoingCommentsTlFk1Link2
   */
  public ViewLinkImpl getCrsOutgoingCommentsTlFk1Link2()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingCommentsTlFk1Link2");
  }

  /**
   * Container's getter for CrsBorrowRequestsView4.
   * @return CrsBorrowRequestsView4
   */
  public ViewObjectImpl getCrsBorrowRequestsView4()
  {
    return (ViewObjectImpl) findViewObject("CrsBorrowRequestsView4");
  }

  /**
   * Container's getter for CrsOutgoingDocumentsView4.
   * @return CrsOutgoingDocumentsView4
   */
  public ViewObjectImpl getCrsOutgoingDocumentsView4()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocumentsView4");
  }

  /**
   * Container's getter for CrsOutgoingArchiveView4.
   * @return CrsOutgoingArchiveView4
   */
  public ViewObjectImpl getCrsOutgoingArchiveView4()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingArchiveView4");
  }

  /**
   * Container's getter for CrsOutgoingArchiveFk1Link2.
   * @return CrsOutgoingArchiveFk1Link2
   */
  public ViewLinkImpl getCrsOutgoingArchiveFk1Link2()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingArchiveFk1Link2");
  }

  /**
   * Container's getter for CrsOutgoingDocAttachTlView4.
   * @return CrsOutgoingDocAttachTlView4
   */
  public ViewObjectImpl getCrsOutgoingDocAttachTlView4()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocAttachTlView4");
  }

  /**
   * Container's getter for CrsOutgoingDocAttachTFk2Link3.
   * @return CrsOutgoingDocAttachTFk2Link3
   */
  public ViewLinkImpl getCrsOutgoingDocAttachTFk2Link3()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingDocAttachTFk2Link3");
  }

  /**
   * Container's getter for ReportParametersRVO1.
   * @return ReportParametersRVO1
   */
  public ViewObjectImpl getReportParametersRVO1()
  {
    return (ViewObjectImpl) findViewObject("ReportParametersRVO1");
  }

  /**
   * Container's getter for CrsIncomingRelatedLettersView5.
   * @return CrsIncomingRelatedLettersView5
   */
  public ViewObjectImpl getCrsIncomingRelatedLettersView5()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingRelatedLettersView5");
  }

  /**
   * Container's getter for CrsIncomingRelatedLettFk2Link2.
   * @return CrsIncomingRelatedLettFk2Link2
   */
  public ViewLinkImpl getCrsIncomingRelatedLettFk2Link2()
  {
    return (ViewLinkImpl) findViewLink("CrsIncomingRelatedLettFk2Link2");
  }

  /**
   * Container's getter for CrsOutgoingBeneficiariesView5.
   * @return CrsOutgoingBeneficiariesView5
   */
  public ViewObjectImpl getCrsOutgoingBeneficiariesView5()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingBeneficiariesView5");
  }

  /**
   * Container's getter for CrsOutgoingBeneficiarieFk1Link2.
   * @return CrsOutgoingBeneficiarieFk1Link2
   */
  public ViewLinkImpl getCrsOutgoingBeneficiarieFk1Link2()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingBeneficiarieFk1Link2");
  }

  /**
   * Container's getter for CrsOutgoingCommentsView3.
   * @return CrsOutgoingCommentsView3
   */
  public ViewObjectImpl getCrsOutgoingCommentsView3()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingCommentsView3");
  }

  /**
   * Container's getter for CrsOutgoingCommentsFk1Link2.
   * @return CrsOutgoingCommentsFk1Link2
   */
  public ViewLinkImpl getCrsOutgoingCommentsFk1Link2()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingCommentsFk1Link2");
  }

  /**
   * Container's getter for CrsOutgoingDocAttachmentsView4.
   * @return CrsOutgoingDocAttachmentsView4
   */
  public ViewObjectImpl getCrsOutgoingDocAttachmentsView4()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocAttachmentsView4");
  }

  /**
   * Container's getter for CrsOutgoingDocAttachmeFk1Link2.
   * @return CrsOutgoingDocAttachmeFk1Link2
   */
  public ViewLinkImpl getCrsOutgoingDocAttachmeFk1Link2()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingDocAttachmeFk1Link2");
  }

  /**
   * Container's getter for CrsOutgoingDocCcView4.
   * @return CrsOutgoingDocCcView4
   */
  public ViewObjectImpl getCrsOutgoingDocCcView4()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocCcView4");
  }

  /**
   * Container's getter for CrsOutgoingDocCcFk1Link2.
   * @return CrsOutgoingDocCcFk1Link2
   */
  public ViewLinkImpl getCrsOutgoingDocCcFk1Link2()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingDocCcFk1Link2");
  }


  /**
   * Container's getter for EmailAttachRo1.
   * @return EmailAttachRo1
   */
  public EmailAttachRoImpl getEmailAttachRo1()
  {
    return (EmailAttachRoImpl) findViewObject("EmailAttachRo1");
  }

  /**
   * Container's getter for CrsDeptGroupDeptsView1.
   * @return CrsDeptGroupDeptsView1
   */
  public ViewObjectImpl getCrsDeptGroupDeptsView1()
  {
    return (ViewObjectImpl) findViewObject("CrsDeptGroupDeptsView1");
  }

  /**
   * Container's getter for CrsDeptGroupTlView1.
   * @return CrsDeptGroupTlView1
   */
  public ViewObjectImpl getCrsDeptGroupTlView1()
  {
    return (ViewObjectImpl) findViewObject("CrsDeptGroupTlView1");
  }

  /**
   * Container's getter for CrsDeptGroupView1.
   * @return CrsDeptGroupView1
   */
  public ViewObjectImpl getCrsDeptGroupView1()
  {
    return (ViewObjectImpl) findViewObject("CrsDeptGroupView1");
  }

  /**
   * Container's getter for CrsDocClassCcTlView1.
   * @return CrsDocClassCcTlView1
   */
  public ViewObjectImpl getCrsDocClassCcTlView1()
  {
    return (ViewObjectImpl) findViewObject("CrsDocClassCcTlView1");
  }

  /**
   * Container's getter for CrsDocClassCcView1.
   * @return CrsDocClassCcView1
   */
  public ViewObjectImpl getCrsDocClassCcView1()
  {
    return (ViewObjectImpl) findViewObject("CrsDocClassCcView1");
  }

  /**
   * Container's getter for CrsDocClassTlView1.
   * @return CrsDocClassTlView1
   */
  public ViewObjectImpl getCrsDocClassTlView1()
  {
    return (ViewObjectImpl) findViewObject("CrsDocClassTlView1");
  }

  /**
   * Container's getter for CrsDocClassView1.
   * @return CrsDocClassView1
   */
  public ViewObjectImpl getCrsDocClassView1()
  {
    return (ViewObjectImpl) findViewObject("CrsDocClassView1");
  }

  /**
   * Container's getter for CrsIncomingDocCcTlView1.
   * @return CrsIncomingDocCcTlView1
   */
  public ViewObjectImpl getCrsIncomingDocCcTlView1()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingDocCcTlView1");
  }

  /**
   * Container's getter for CrsOutgoingDocCcTlView1.
   * @return CrsOutgoingDocCcTlView1
   */
  public ViewObjectImpl getCrsOutgoingDocCcTlView1()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocCcTlView1");
  }

  /**
   * Container's getter for CrsDeptGroupDeptsView2.
   * @return CrsDeptGroupDeptsView2
   */
  public ViewObjectImpl getCrsDeptGroupDeptsView2()
  {
    return (ViewObjectImpl) findViewObject("CrsDeptGroupDeptsView2");
  }

  /**
   * Container's getter for CrsDeptGroupTlView2.
   * @return CrsDeptGroupTlView2
   */
  public ViewObjectImpl getCrsDeptGroupTlView2()
  {
    return (ViewObjectImpl) findViewObject("CrsDeptGroupTlView2");
  }

  /**
   * Container's getter for CrsDocClassCcView2.
   * @return CrsDocClassCcView2
   */
  public ViewObjectImpl getCrsDocClassCcView2()
  {
    return (ViewObjectImpl) findViewObject("CrsDocClassCcView2");
  }

  /**
   * Container's getter for CrsDocClassCcTlView2.
   * @return CrsDocClassCcTlView2
   */
  public ViewObjectImpl getCrsDocClassCcTlView2()
  {
    return (ViewObjectImpl) findViewObject("CrsDocClassCcTlView2");
  }

  /**
   * Container's getter for CrsDocClassTlView2.
   * @return CrsDocClassTlView2
   */
  public ViewObjectImpl getCrsDocClassTlView2()
  {
    return (ViewObjectImpl) findViewObject("CrsDocClassTlView2");
  }

  /**
   * Container's getter for CrsDeptGroupDeptsFk1Link1.
   * @return CrsDeptGroupDeptsFk1Link1
   */
  public ViewLinkImpl getCrsDeptGroupDeptsFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsDeptGroupDeptsFk1Link1");
  }

  /**
   * Container's getter for CrsDeptGroupTlFk1Link1.
   * @return CrsDeptGroupTlFk1Link1
   */
  public ViewLinkImpl getCrsDeptGroupTlFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsDeptGroupTlFk1Link1");
  }

  /**
   * Container's getter for CrsDocClassCcFk1Link1.
   * @return CrsDocClassCcFk1Link1
   */
  public ViewLinkImpl getCrsDocClassCcFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsDocClassCcFk1Link1");
  }

  /**
   * Container's getter for CrsDocClassCcTlFk1Link1.
   * @return CrsDocClassCcTlFk1Link1
   */
  public ViewLinkImpl getCrsDocClassCcTlFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsDocClassCcTlFk1Link1");
  }

  /**
   * Container's getter for CrsDocClassTlFk1Link1.
   * @return CrsDocClassTlFk1Link1
   */
  public ViewLinkImpl getCrsDocClassTlFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsDocClassTlFk1Link1");
  }

  /**
   * Container's getter for CrsAllowedSendTypesView1.
   * @return CrsAllowedSendTypesView1
   */
  public ViewObjectImpl getCrsAllowedSendTypesView1()
  {
    return (ViewObjectImpl) findViewObject("CrsAllowedSendTypesView1");
  }

  /**
   * Container's getter for CrsOutgoingArchiveTlView4.
   * @return CrsOutgoingArchiveTlView4
   */
  public ViewObjectImpl getCrsOutgoingArchiveTlView4()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingArchiveTlView4");
  }

  /**
   * Container's getter for CrsOutgoingArchiveTlFk1Link3.
   * @return CrsOutgoingArchiveTlFk1Link3
   */
  public ViewLinkImpl getCrsOutgoingArchiveTlFk1Link3()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingArchiveTlFk1Link3");
  }


  /**
   * Container's getter for CrsOutgoingDocCcTlView2.
   * @return CrsOutgoingDocCcTlView2
   */
  public ViewObjectImpl getCrsOutgoingDocCcTlView2()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingDocCcTlView2");
  }

  /**
   * Container's getter for OutgoingDocCcTlVL1.
   * @return OutgoingDocCcTlVL1
   */
  public ViewLinkImpl getOutgoingDocCcTlVL1()
  {
    return (ViewLinkImpl) findViewLink("OutgoingDocCcTlVL1");
  }

  /**
   * Container's getter for CrsOutgoingCommentsView4.
   * @return CrsOutgoingCommentsView4
   */
  public ViewObjectImpl getCrsOutgoingCommentsView4()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingCommentsView4");
  }

  /**
   * Container's getter for CrsOutgoingCommentsFk2Link1.
   * @return CrsOutgoingCommentsFk2Link1
   */
  public ViewLinkImpl getCrsOutgoingCommentsFk2Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingCommentsFk2Link1");
  }

  /**
   * Container's getter for CrsOutgoingCommentsTlView4.
   * @return CrsOutgoingCommentsTlView4
   */
  public ViewObjectImpl getCrsOutgoingCommentsTlView4()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingCommentsTlView4");
  }

  /**
   * Container's getter for CrsOutgoingCommentsTlFk1Link3.
   * @return CrsOutgoingCommentsTlFk1Link3
   */
  public ViewLinkImpl getCrsOutgoingCommentsTlFk1Link3()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingCommentsTlFk1Link3");
  }

  /**
   * Container's getter for EntryCountDocView1.
   * @return EntryCountDocView1
   */
  public ViewObjectImpl getEntryCountDocView1()
  {
    return (ViewObjectImpl) findViewObject("EntryCountDocView1");
  }

  /**
   * Container's getter for EntryCountOutgoingDocView1.
   * @return EntryCountOutgoingDocView1
   */
  public EntryCountOutgoingDocViewImpl getEntryCountOutgoingDocView1()
  {
    return (EntryCountOutgoingDocViewImpl) findViewObject("EntryCountOutgoingDocView1");
  }

  /**
   * Container's getter for CrsAllowedSendTypesView2.
   * @return CrsAllowedSendTypesView2
   */
  public ViewObjectImpl getCrsAllowedSendTypesView2()
  {
    return (ViewObjectImpl) findViewObject("CrsAllowedSendTypesView2");
  }

  /**
   * Container's getter for CrsAllowedSendTypeFKLink1.
   * @return CrsAllowedSendTypeFKLink1
   */
  public ViewLinkImpl getCrsAllowedSendTypeFKLink1()
  {
    return (ViewLinkImpl) findViewLink("CrsAllowedSendTypeFKLink1");
  }

  /**
   * Container's getter for CrsLetterTemplatesView1.
   * @return CrsLetterTemplatesView1
   */
  public ViewObjectImpl getCrsLetterTemplatesView1()
  {
    return (ViewObjectImpl) findViewObject("CrsLetterTemplatesView1");
  }

  /**
   * Container's getter for CrsLetterTemplatesView2.
   * @return CrsLetterTemplatesView2
   */
  public ViewObjectImpl getCrsLetterTemplatesView2()
  {
    return (ViewObjectImpl) findViewObject("CrsLetterTemplatesView2");
  }

  /**
   * Container's getter for DepartmentTemplatesVL1.
   * @return DepartmentTemplatesVL1
   */
  public ViewLinkImpl getDepartmentTemplatesVL1()
  {
    return (ViewLinkImpl) findViewLink("DepartmentTemplatesVL1");
  }

  /**
   * Container's getter for CrsDocClassCcTlView3.
   * @return CrsDocClassCcTlView3
   */
  public ViewObjectImpl getCrsDocClassCcTlView3()
  {
    return (ViewObjectImpl) findViewObject("CrsDocClassCcTlView3");
  }

  /**
   * Container's getter for CrsDocClassCcTlFk1Link2.
   * @return CrsDocClassCcTlFk1Link2
   */
  public ViewLinkImpl getCrsDocClassCcTlFk1Link2()
  {
    return (ViewLinkImpl) findViewLink("CrsDocClassCcTlFk1Link2");
  }

  /**
   * Container's getter for DeliverySelectedDocumentsPVO1.
   * @return DeliverySelectedDocumentsPVO1
   */
  public DeliverySelectedDocumentsPVOImpl getDeliverySelectedDocumentsPVO1()
  {
    return (DeliverySelectedDocumentsPVOImpl) findViewObject("DeliverySelectedDocumentsPVO1");
  }

  /**
   * Container's getter for DeliveryStatmentAttachPVO1.
   * @return DeliveryStatmentAttachPVO1
   */
  public DeliveryStatmentAttachPVOImpl getDeliveryStatmentAttachPVO1()
  {
    return (DeliveryStatmentAttachPVOImpl) findViewObject("DeliveryStatmentAttachPVO1");
  }

  /**
   * Container's getter for DeparmentsRVO1.
   * @return DeparmentsRVO1
   */
  public ViewObjectImpl getDeparmentsRVO()
  {
    return (ViewObjectImpl) findViewObject("DeparmentsRVO");
  }

  /**
   * Container's getter for CrsDeptGroupRVO1.
   * @return CrsDeptGroupRVO1
   */
  public CrsDeptGroupRVOImpl getCrsDeptGroupRVO()
  {
    return (CrsDeptGroupRVOImpl) findViewObject("CrsDeptGroupRVO");
  }

  /**
   * Container's getter for CrsIncomingDocumentsView4.
   * @return CrsIncomingDocumentsView4
   */
//  public gen.common.BaseViewObjectImpl getCrsIncomingDocumentsCopyDocCcView()
//  {
//    return (gen.common.BaseViewObjectImpl) findViewObject("CrsIncomingDocumentsCopyDocCcView");
//  }

  /**
   * Container's getter for CrsIncomingDocumentsDocAssignmentView.
   * @return CrsIncomingDocumentsDocAssignmentView
   */
//  public gen.common.BaseViewObjectImpl getCrsIncomingDocumentsDocAssignmentView()
//  {
//    return (gen.common.BaseViewObjectImpl) findViewObject("CrsIncomingDocumentsDocAssignmentView");
//  }
//  

  /**
   * Container's getter for CrsIncomingDocCcView3.
   * @return CrsIncomingDocCcView3
   */
  public ViewObjectImpl getCrsIncomingDocCcDocAssignmentView()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingDocCcDocAssignmentView");
  }

  /**
   * Container's getter for CrsIncomingDocCcFk1Link2.
   * @return CrsIncomingDocCcFk1Link2
   */
  public ViewLinkImpl getCrsIncomingDocCcFk1Link2()
  {
    return (ViewLinkImpl) findViewLink("CrsIncomingDocCcFk1Link2");
  }

  /**
   * Container's getter for CrsIncomingArchiveView3.
   * @return CrsIncomingArchiveView3
   */
  public ViewObjectImpl getCrsIncomingArchiveDocAssignmentView()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingArchiveDocAssignmentView");
  }

  /**
   * Container's getter for CrsIncomingArchiveFk1Link2.
   * @return CrsIncomingArchiveFk1Link2
   */
  public ViewLinkImpl getCrsIncomingArchiveFk1Link2()
  {
    return (ViewLinkImpl) findViewLink("CrsIncomingArchiveFk1Link2");
  }

  /**
   * Container's getter for CrsIncomingArchiveTlView4.
   * @return CrsIncomingArchiveTlView4
   */
  public ViewObjectImpl getCrsIncomingArchiveTlDocAssignmentView()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingArchiveTlDocAssignmentView");
  }

  /**
   * Container's getter for CrsIncomingArchiveTlFk1Link3.
   * @return CrsIncomingArchiveTlFk1Link3
   */
  public ViewLinkImpl getCrsIncomingArchiveTlFk1Link3()
  {
    return (ViewLinkImpl) findViewLink("CrsIncomingArchiveTlFk1Link3");
  }

  /**
   * Container's getter for CrsIncomingDocCcView3.
   * @return CrsIncomingDocCcView3
   */
  public ViewObjectImpl getCrsIncomingDocCcCopyView()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingDocCcCopyView");
  }

  /**
   * Container's getter for IncomingDocumentCCVwView1.
   * @return IncomingDocumentCCVwView1
   */
  public ViewObjectImpl getIncomingDocumentCCVwView1()
  {
    return (ViewObjectImpl) findViewObject("IncomingDocumentCCVwView1");
  }

  /**
   * Container's getter for HcmDepartmentsView1.
   * @return HcmDepartmentsView1
   */
  public ViewObjectImpl getHcmDepartmentsView1()
  {
    return (ViewObjectImpl) findViewObject("HcmDepartmentsView1");
  }

  /**
   * Container's getter for CrsAllowedSendDepartmentsView3.
   * @return CrsAllowedSendDepartmentsView3
   */
  public ViewObjectImpl getCrsAllowedSendDepartmentsView3()
  {
    return (ViewObjectImpl) findViewObject("CrsAllowedSendDepartmentsView3");
  }

  /**
   * Container's getter for CrsDepartmentsFollowupFk1Link1.
   * @return CrsDepartmentsFollowupFk1Link1
   */
  public ViewLinkImpl getCrsDepartmentsFollowupFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsDepartmentsFollowupFk1Link1");
  }

  /**
   * Container's getter for CrsAllowedSendTypesView3.
   * @return CrsAllowedSendTypesView3
   */
  public ViewObjectImpl getCrsAllowedSendTypesView3()
  {
    return (ViewObjectImpl) findViewObject("CrsAllowedSendTypesView3");
  }

  /**
   * Container's getter for CrsAllowedSendTypesFkLink1.
   * @return CrsAllowedSendTypesFkLink1
   */
  public ViewLinkImpl getCrsAllowedSendTypesFkLink1()
  {
    return (ViewLinkImpl) findViewLink("CrsAllowedSendTypesFkLink1");
  }

  /**
   * Container's getter for CrsFilesLocationView4.
   * @return CrsFilesLocationView4
   */
  public ViewObjectImpl getCrsFilesLocationView4()
  {
    return (ViewObjectImpl) findViewObject("CrsFilesLocationView4");
  }

  /**
   * Container's getter for CrsFileLocationFkLink1.
   * @return CrsFileLocationFkLink1
   */
  public ViewLinkImpl getCrsFileLocationFkLink1()
  {
    return (ViewLinkImpl) findViewLink("CrsFileLocationFkLink1");
  }

  /**
   * Container's getter for CrsLetterTemplatesView3.
   * @return CrsLetterTemplatesView3
   */
  public ViewObjectImpl getCrsLetterTemplatesView3()
  {
    return (ViewObjectImpl) findViewObject("CrsLetterTemplatesView3");
  }

  /**
   * Container's getter for CrsLetterTemplatesFk1Link1.
   * @return CrsLetterTemplatesFk1Link1
   */
  public ViewLinkImpl getCrsLetterTemplatesFk1Link1()
  {
    return (ViewLinkImpl) findViewLink("CrsLetterTemplatesFk1Link1");
  }

  /**
   * Container's getter for CrsFilesLocationTlView4.
   * @return CrsFilesLocationTlView4
   */
  public ViewObjectImpl getCrsFilesLocationTlView4()
  {
    return (ViewObjectImpl) findViewObject("CrsFilesLocationTlView4");
  }

  /**
   * Container's getter for CrsFilesLocationTlFk1Link3.
   * @return CrsFilesLocationTlFk1Link3
   */
  public ViewLinkImpl getCrsFilesLocationTlFk1Link3()
  {
    return (ViewLinkImpl) findViewLink("CrsFilesLocationTlFk1Link3");
  }

  /**
   * Container's getter for CrsIncomingDocumentsDocAssignmentView.
   * @return CrsIncomingDocumentsDocAssignmentView
   */
//  public gen.common.BaseViewObjectImpl getCrsIncomingDocumentsDocAssignmentView()
//  {
//    return (gen.common.BaseViewObjectImpl) findViewObject("CrsIncomingDocumentsDocAssignmentView");
//  }

  /**
   * Container's getter for CrsIncomingDocumentsCopyDocCcView.
   * @return CrsIncomingDocumentsCopyDocCcView
   */
//  public gen.common.BaseViewObjectImpl getCrsIncomingDocumentsCopyDocCcView()
//  {
//    return (gen.common.BaseViewObjectImpl) findViewObject("CrsIncomingDocumentsCopyDocCcView");
//  }


  /**
   * Container's getter for CrsIncomingDocCcView3.
   * @return CrsIncomingDocCcView3
   */
  public ViewObjectImpl getCrsIncomingDocCcView3()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingDocCcView3");
  }

  /**
   * Container's getter for IncomingDocumentCCVwLink1.
   * @return IncomingDocumentCCVwLink1
   */
  public ViewLinkImpl getIncomingDocumentCCVwLink1()
  {
    return (ViewLinkImpl) findViewLink("IncomingDocumentCCVwLink1");
  }

  /**
   * Container's getter for CrsIncomingDocCcTlView2.
   * @return CrsIncomingDocCcTlView2
   */
  public ViewObjectImpl getCrsIncomingDocCcTlView2()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingDocCcTlView2");
  }

  /**
   * Container's getter for CrsIncomingDocCcLink1.
   * @return CrsIncomingDocCcLink1
   */
  public ViewLinkImpl getCrsIncomingDocCcLink1()
  {
    return (ViewLinkImpl) findViewLink("CrsIncomingDocCcLink1");
  }

  /**
   * Container's getter for CrsIncomingDocumentsDocAssignmentView.
   * @return CrsIncomingDocumentsDocAssignmentView
   */
//  public gen.common.BaseViewObjectImpl getCrsIncomingDocumentsDocAssignmentView()
//  {
//    return (gen.common.BaseViewObjectImpl) findViewObject("CrsIncomingDocumentsDocAssignmentView");
//  }

  /**
   * Container's getter for CrsIncomingDocumentsCopyDocCcView.
   * @return CrsIncomingDocumentsCopyDocCcView
   */
//  public gen.common.BaseViewObjectImpl getCrsIncomingDocumentsCopyDocCcView()
//  {
//    return (gen.common.BaseViewObjectImpl) findViewObject("CrsIncomingDocumentsCopyDocCcView");
//  }

  /**
   * Container's getter for CrsIncomingDocCcTlView3.
   * @return CrsIncomingDocCcTlView3
   */
  public ViewObjectImpl getCrsIncomingDocCcTlView3()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingDocCcTlView3");
  }

  /**
   * Container's getter for CrsIncomingDocCcLink2.
   * @return CrsIncomingDocCcLink2
   */
  public ViewLinkImpl getCrsIncomingDocCcLink2()
  {
    return (ViewLinkImpl) findViewLink("CrsIncomingDocCcLink2");
  }

  /**
   * Container's getter for CrsIncomingDocumentsDocAssignmentView.
   * @return CrsIncomingDocumentsDocAssignmentView
   */

  /**
   * Container's getter for CrsIncomingDocumentsCopyDocCcView.
   * @return CrsIncomingDocumentsCopyDocCcView
   */

  /**
   * Container's getter for CrsOutgoingRelatedLettersView3.
   * @return CrsOutgoingRelatedLettersView3
   */
  public ViewObjectImpl getCrsOutgoingRelatedLettersView3()
  {
    return (ViewObjectImpl) findViewObject("CrsOutgoingRelatedLettersView3");
  }

  /**
   * Container's getter for CrsOutgoingRelatedLettFk1Link2.
   * @return CrsOutgoingRelatedLettFk1Link2
   */
  public ViewLinkImpl getCrsOutgoingRelatedLettFk1Link2()
  {
    return (ViewLinkImpl) findViewLink("CrsOutgoingRelatedLettFk1Link2");
  }
  /**
   * Container's getter for SsoActiveLookupValuesVwView1.
   * @return SsoActiveLookupValuesVwView1
   */
  public ViewObjectImpl getSsoActiveLookupValuesVwView1()
  {
    return (ViewObjectImpl) findViewObject("SsoActiveLookupValuesVwView1");
  }

  /**
   * Container's getter for CrsIncomingDocumentsDocAssignmentView.
   * @return CrsIncomingDocumentsDocAssignmentView
   */
  public ViewObjectImpl getCrsIncomingDocumentsDocAssignmentView()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingDocumentsDocAssignmentView");
  }

  /**
   * Container's getter for CrsIncomingDocumentsCopyDocCcView.
   * @return CrsIncomingDocumentsCopyDocCcView
   */
  public ViewObjectImpl getCrsIncomingDocumentsCopyDocCcView()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingDocumentsCopyDocCcView");
  }

  /**
   * Container's getter for HcmEmpBasicDataVw1.
   * @return HcmEmpBasicDataVw1
   */
  public HcmEmpBasicDataVwImpl getHcmEmpBasicDataVw1()
  {
    return (HcmEmpBasicDataVwImpl) findViewObject("HcmEmpBasicDataVw1");
  }

  /**
   * Container's getter for CrsIncomingDocCcTlView4.
   * @return CrsIncomingDocCcTlView4
   */
  public ViewObjectImpl getCrsIncomingDocCcTlView4()
  {
    return (ViewObjectImpl) findViewObject("CrsIncomingDocCcTlView4");
  }

  /**
   * Container's getter for CrsIncomingDocCcLink3.
   * @return CrsIncomingDocCcLink3
   */
  public ViewLinkImpl getCrsIncomingDocCcLink3()
  {
    return (ViewLinkImpl) findViewLink("CrsIncomingDocCcLink3");
  }
}

