package crs.model.eo;

import gen.common.GenLib;

import java.math.BigDecimal;

import java.sql.Timestamp;

import java.util.List;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Apr 01 13:33:20 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CrsBorrowRequestsImpl
  extends AuditEntityImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    BorrowRequestsPk,
    IncomingDocumentsFk,
    RequestPeriod,
    CreatedBy,
    CreationDate,
    ModifiedBy,
    ModifiedDate,
    UserDepartmentFk,
    OutgoingDocumentsFk,
    DisplayRequestReason,
    DisplayNotes,
    DocumentTypeFk,
    CrsBorrowRequestsTl,
    CrsIncomingDocuments,
    CrsOutgoingDocuments;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int BORROWREQUESTSPK = AttributesEnum.BorrowRequestsPk.index();
  public static final int INCOMINGDOCUMENTSFK = AttributesEnum.IncomingDocumentsFk.index();
  public static final int REQUESTPERIOD = AttributesEnum.RequestPeriod.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
  public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
  public static final int USERDEPARTMENTFK = AttributesEnum.UserDepartmentFk.index();
  public static final int OUTGOINGDOCUMENTSFK = AttributesEnum.OutgoingDocumentsFk.index();
  public static final int DISPLAYREQUESTREASON = AttributesEnum.DisplayRequestReason.index();
  public static final int DISPLAYNOTES = AttributesEnum.DisplayNotes.index();
  public static final int DOCUMENTTYPEFK = AttributesEnum.DocumentTypeFk.index();
  public static final int CRSBORROWREQUESTSTL = AttributesEnum.CrsBorrowRequestsTl.index();
  public static final int CRSINCOMINGDOCUMENTS = AttributesEnum.CrsIncomingDocuments.index();
  public static final int CRSOUTGOINGDOCUMENTS = AttributesEnum.CrsOutgoingDocuments.index();

  /**
   * This is the default constructor (do not remove).
   */
  public CrsBorrowRequestsImpl()
  {
  }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    return EntityDefImpl.findDefObject("crs.model.eo.CrsBorrowRequests");
  }


  /**
   * Gets the attribute value for BorrowRequestsPk, using the alias name BorrowRequestsPk.
   * @return the value of BorrowRequestsPk
   */
  public BigDecimal getBorrowRequestsPk()
  {
    return (BigDecimal) getAttributeInternal(BORROWREQUESTSPK);
  }

  /**
   * Sets <code>value</code> as the attribute value for BorrowRequestsPk.
   * @param value value to set the BorrowRequestsPk
   */
  public void setBorrowRequestsPk(BigDecimal value)
  {
    setAttributeInternal(BORROWREQUESTSPK, value);
  }

  /**
   * Gets the attribute value for IncomingDocumentsFk, using the alias name IncomingDocumentsFk.
   * @return the value of IncomingDocumentsFk
   */
  public BigDecimal getIncomingDocumentsFk()
  {
    return (BigDecimal) getAttributeInternal(INCOMINGDOCUMENTSFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for IncomingDocumentsFk.
   * @param value value to set the IncomingDocumentsFk
   */
  public void setIncomingDocumentsFk(BigDecimal value)
  {
    setAttributeInternal(INCOMINGDOCUMENTSFK, value);
  }

  /**
   * Gets the attribute value for RequestPeriod, using the alias name RequestPeriod.
   * @return the value of RequestPeriod
   */
  public BigDecimal getRequestPeriod()
  {
    return (BigDecimal) getAttributeInternal(REQUESTPERIOD);
  }

  /**
   * Sets <code>value</code> as the attribute value for RequestPeriod.
   * @param value value to set the RequestPeriod
   */
  public void setRequestPeriod(BigDecimal value)
  {
    setAttributeInternal(REQUESTPERIOD, value);
  }

  /**
   * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
   * @return the value of CreatedBy
   */
  public BigDecimal getCreatedBy()
  {
    return (BigDecimal) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreatedBy.
   * @param value value to set the CreatedBy
   */
  public void setCreatedBy(BigDecimal value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CreationDate, using the alias name CreationDate.
   * @return the value of CreationDate
   */
  public Timestamp getCreationDate()
  {
    return (Timestamp) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreationDate.
   * @param value value to set the CreationDate
   */
  public void setCreationDate(Timestamp value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for ModifiedBy, using the alias name ModifiedBy.
   * @return the value of ModifiedBy
   */
  public BigDecimal getModifiedBy()
  {
    return (BigDecimal) getAttributeInternal(MODIFIEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedBy.
   * @param value value to set the ModifiedBy
   */
  public void setModifiedBy(BigDecimal value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
   * @return the value of ModifiedDate
   */
  public Timestamp getModifiedDate()
  {
    return (Timestamp) getAttributeInternal(MODIFIEDDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedDate.
   * @param value value to set the ModifiedDate
   */
  public void setModifiedDate(Timestamp value)
  {
    setAttributeInternal(MODIFIEDDATE, value);
  }

  /**
   * Gets the attribute value for UserDepartmentFk, using the alias name UserDepartmentFk.
   * @return the value of UserDepartmentFk
   */
  public BigDecimal getUserDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(USERDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for UserDepartmentFk.
   * @param value value to set the UserDepartmentFk
   */
  public void setUserDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(USERDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for OutgoingDocumentsFk, using the alias name OutgoingDocumentsFk.
   * @return the value of OutgoingDocumentsFk
   */
  public BigDecimal getOutgoingDocumentsFk()
  {
    return (BigDecimal) getAttributeInternal(OUTGOINGDOCUMENTSFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for OutgoingDocumentsFk.
   * @param value value to set the OutgoingDocumentsFk
   */
  public void setOutgoingDocumentsFk(BigDecimal value)
  {
    setAttributeInternal(OUTGOINGDOCUMENTSFK, value);
  }

  /**
   * Gets the attribute value for DisplayRequestReason, using the alias name DisplayRequestReason.
   * @return the value of DisplayRequestReason
   */
  public String getDisplayRequestReason()
  {
    return (String) getAttributeInternal(DISPLAYREQUESTREASON);
  }

  /**
   * Sets <code>value</code> as the attribute value for DisplayRequestReason.
   * @param value value to set the DisplayRequestReason
   */
  public void setDisplayRequestReason(String value)
  {
    setAttributeInternal(DISPLAYREQUESTREASON, value);
  }

  /**
   * Gets the attribute value for DisplayNotes, using the alias name DisplayNotes.
   * @return the value of DisplayNotes
   */
  public String getDisplayNotes()
  {
    return (String) getAttributeInternal(DISPLAYNOTES);
  }

  /**
   * Sets <code>value</code> as the attribute value for DisplayNotes.
   * @param value value to set the DisplayNotes
   */
  public void setDisplayNotes(String value)
  {
    setAttributeInternal(DISPLAYNOTES, value);
  }

  /**
   * Gets the attribute value for DocumentTypeFk, using the alias name DocumentTypeFk.
   * @return the value of DocumentTypeFk
   */
  public BigDecimal getDocumentTypeFk()
  {
    return (BigDecimal) getAttributeInternal(DOCUMENTTYPEFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for DocumentTypeFk.
   * @param value value to set the DocumentTypeFk
   */
  public void setDocumentTypeFk(BigDecimal value)
  {
    setAttributeInternal(DOCUMENTTYPEFK, value);
  }

  /**
   * @return the associated entity oracle.jbo.RowIterator.
   */
  public RowIterator getCrsBorrowRequestsTl()
  {
    return (RowIterator) getAttributeInternal(CRSBORROWREQUESTSTL);
  }

  /**
   * @return the associated entity CrsIncomingDocumentsImpl.
   */
  public CrsIncomingDocumentsImpl getCrsIncomingDocuments()
  {
    return (CrsIncomingDocumentsImpl) getAttributeInternal(CRSINCOMINGDOCUMENTS);
  }

  /**
   * Sets <code>value</code> as the associated entity CrsIncomingDocumentsImpl.
   */
  public void setCrsIncomingDocuments(CrsIncomingDocumentsImpl value)
  {
    setAttributeInternal(CRSINCOMINGDOCUMENTS, value);
  }

  /**
   * @return the associated entity CrsOutgoingDocumentsImpl.
   */
  public CrsOutgoingDocumentsImpl getCrsOutgoingDocuments()
  {
    return (CrsOutgoingDocumentsImpl) getAttributeInternal(CRSOUTGOINGDOCUMENTS);
  }

  /**
   * Sets <code>value</code> as the associated entity CrsOutgoingDocumentsImpl.
   */
  public void setCrsOutgoingDocuments(CrsOutgoingDocumentsImpl value)
  {
    setAttributeInternal(CRSOUTGOINGDOCUMENTS, value);
  }


  /**
   * @param borrowRequestsPk key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(BigDecimal borrowRequestsPk)
  {
    return new Key(new Object[] { borrowRequestsPk });
  }

 
  protected void doDML(int operation, oracle.jbo.server.TransactionEvent e)
  {
    super.doDML(operation, e);
    if ( operation == DML_INSERT ){
      BigDecimal crsBorrowRequestsPk = gen.common.GenLib.getPrimaryKeyValue(getDBTransaction(), "CRS_BORROW_REQUESTS_SEQ");
      setBorrowRequestsPk(crsBorrowRequestsPk);
      insertToCrsBorrowRequestsTl();
    }
  }
  
  private void insertToCrsBorrowRequestsTl(){ 
  
      oracle.jbo.server.EntityDefImpl crsBorrowRequestsTlDefinition = CrsBorrowRequestsTlImpl.getDefinitionObject();
      List<Integer> activeLanguages = GenLib.getActiveDataLanguages(getDBTransaction());
      for (Integer languageId : activeLanguages) {
        CrsBorrowRequestsTlImpl crsBorrowRequestsTl = (CrsBorrowRequestsTlImpl)crsBorrowRequestsTlDefinition.createInstance2(getDBTransaction(), null);
        crsBorrowRequestsTl.setLanguagesFk(BigDecimal.valueOf(languageId));
        crsBorrowRequestsTl.setRequestReason(getDisplayRequestReason());
        crsBorrowRequestsTl.setNotes(getDisplayNotes());
        crsBorrowRequestsTl.setBorrowRequestsFk(getBorrowRequestsPk());
      }
    }
  public void remove()
  {
    gen.common.GenLib.removeTranlationRows(getCrsBorrowRequestsTl());
    super.remove();
  }

}

