package crs.model.eo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Apr 01 13:33:16 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CrsBeneficiariesTlImpl
  extends AuditEntityImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    BeneficiariesTlPk,
    BeneficiaryName,
    Notes,
    BeneficiariesFk,
    LanguagesFk,
    CreatedBy,
    CreationDate,
    ModifiedBy,
    ModifiedDate,
    UserDepartmentFk,
    CrsBeneficiaries;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }

  public static final int BENEFICIARIESTLPK = AttributesEnum.BeneficiariesTlPk.index();
  public static final int BENEFICIARYNAME = AttributesEnum.BeneficiaryName.index();
  public static final int NOTES = AttributesEnum.Notes.index();
  public static final int BENEFICIARIESFK = AttributesEnum.BeneficiariesFk.index();
  public static final int LANGUAGESFK = AttributesEnum.LanguagesFk.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
  public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
  public static final int USERDEPARTMENTFK = AttributesEnum.UserDepartmentFk.index();
  public static final int CRSBENEFICIARIES = AttributesEnum.CrsBeneficiaries.index();

  /**
   * This is the default constructor (do not remove).
   */
  public CrsBeneficiariesTlImpl()
  {
  }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    return EntityDefImpl.findDefObject("crs.model.eo.CrsBeneficiariesTl");
  }

  /**
   * Gets the attribute value for BeneficiariesTlPk, using the alias name BeneficiariesTlPk.
   * @return the value of BeneficiariesTlPk
   */
  public BigDecimal getBeneficiariesTlPk()
  {
    return (BigDecimal) getAttributeInternal(BENEFICIARIESTLPK);
  }

  /**
   * Sets <code>value</code> as the attribute value for BeneficiariesTlPk.
   * @param value value to set the BeneficiariesTlPk
   */
  public void setBeneficiariesTlPk(BigDecimal value)
  {
    setAttributeInternal(BENEFICIARIESTLPK, value);
  }

  /**
   * Gets the attribute value for BeneficiaryName, using the alias name BeneficiaryName.
   * @return the value of BeneficiaryName
   */
  public String getBeneficiaryName()
  {
    return (String) getAttributeInternal(BENEFICIARYNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for BeneficiaryName.
   * @param value value to set the BeneficiaryName
   */
  public void setBeneficiaryName(String value)
  {
    setAttributeInternal(BENEFICIARYNAME, value);
  }

  /**
   * Gets the attribute value for Notes, using the alias name Notes.
   * @return the value of Notes
   */
  public String getNotes()
  {
    return (String) getAttributeInternal(NOTES);
  }

  /**
   * Sets <code>value</code> as the attribute value for Notes.
   * @param value value to set the Notes
   */
  public void setNotes(String value)
  {
    setAttributeInternal(NOTES, value);
  }

  /**
   * Gets the attribute value for BeneficiariesFk, using the alias name BeneficiariesFk.
   * @return the value of BeneficiariesFk
   */
  public BigDecimal getBeneficiariesFk()
  {
    return (BigDecimal) getAttributeInternal(BENEFICIARIESFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for BeneficiariesFk.
   * @param value value to set the BeneficiariesFk
   */
  public void setBeneficiariesFk(BigDecimal value)
  {
    setAttributeInternal(BENEFICIARIESFK, value);
  }

  /**
   * Gets the attribute value for LanguagesFk, using the alias name LanguagesFk.
   * @return the value of LanguagesFk
   */
  public BigDecimal getLanguagesFk()
  {
    return (BigDecimal) getAttributeInternal(LANGUAGESFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for LanguagesFk.
   * @param value value to set the LanguagesFk
   */
  public void setLanguagesFk(BigDecimal value)
  {
    setAttributeInternal(LANGUAGESFK, value);
  }

  /**
   * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
   * @return the value of CreatedBy
   */
  public BigDecimal getCreatedBy()
  {
    return (BigDecimal) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreatedBy.
   * @param value value to set the CreatedBy
   */
  public void setCreatedBy(BigDecimal value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CreationDate, using the alias name CreationDate.
   * @return the value of CreationDate
   */
  public Timestamp getCreationDate()
  {
    return (Timestamp) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreationDate.
   * @param value value to set the CreationDate
   */
  public void setCreationDate(Timestamp value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for ModifiedBy, using the alias name ModifiedBy.
   * @return the value of ModifiedBy
   */
  public BigDecimal getModifiedBy()
  {
    return (BigDecimal) getAttributeInternal(MODIFIEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedBy.
   * @param value value to set the ModifiedBy
   */
  public void setModifiedBy(BigDecimal value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
   * @return the value of ModifiedDate
   */
  public Timestamp getModifiedDate()
  {
    return (Timestamp) getAttributeInternal(MODIFIEDDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedDate.
   * @param value value to set the ModifiedDate
   */
  public void setModifiedDate(Timestamp value)
  {
    setAttributeInternal(MODIFIEDDATE, value);
  }

  /**
   * Gets the attribute value for UserDepartmentFk, using the alias name UserDepartmentFk.
   * @return the value of UserDepartmentFk
   */
  public BigDecimal getUserDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(USERDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for UserDepartmentFk.
   * @param value value to set the UserDepartmentFk
   */
  public void setUserDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(USERDEPARTMENTFK, value);
  }

  /**
   * @return the associated entity CrsBeneficiariesImpl.
   */
  public CrsBeneficiariesImpl getCrsBeneficiaries()
  {
    return (CrsBeneficiariesImpl) getAttributeInternal(CRSBENEFICIARIES);
  }

  /**
   * Sets <code>value</code> as the associated entity CrsBeneficiariesImpl.
   */
  public void setCrsBeneficiaries(CrsBeneficiariesImpl value)
  {
    setAttributeInternal(CRSBENEFICIARIES, value);
  }

  /**
   * @param beneficiariesTlPk key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(BigDecimal beneficiariesTlPk)
  {
    return new Key(new Object[] { beneficiariesTlPk });
  }



  

  protected void doDML(int operation, oracle.jbo.server.TransactionEvent e)
  {
    super.doDML(operation, e);

    if ( operation == DML_INSERT )
    {
      BigDecimal beneficiariesTlPk = gen.common.GenLib.getPrimaryKeyValue(getDBTransaction(), "CRS_BENEFICIARIES_TL_SEQ");
      setBeneficiariesTlPk(beneficiariesTlPk);
    }
  }

}

