package crs.model.eo;

import gen.common.GenLib;

import java.math.BigDecimal;
import java.sql.Timestamp;

import java.util.List;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Apr 01 13:34:21 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CrsOutgoingArchiveImpl
  extends AuditEntityImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    OutgoingArchivePk,
    ArcFilePath,
    OutgoingDocumentsFk,
    OutgoingDocPreparationFk,
    SecurityLevelFk,
    CreatedBy,
    CreationDate,
    ModifiedBy,
    ModifiedDate,
    UserDepartmentFk,
    DisplayArcDocName,
    DisplayArcDocDesc,
    CrsOutgoingArchiveTl,
    CrsOutgoingDocuments,
    CrsOutgoingDocPreparation;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }

  public static final int OUTGOINGARCHIVEPK = AttributesEnum.OutgoingArchivePk.index();
  public static final int ARCFILEPATH = AttributesEnum.ArcFilePath.index();
  public static final int OUTGOINGDOCUMENTSFK = AttributesEnum.OutgoingDocumentsFk.index();
  public static final int OUTGOINGDOCPREPARATIONFK = AttributesEnum.OutgoingDocPreparationFk.index();
  public static final int SECURITYLEVELFK = AttributesEnum.SecurityLevelFk.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
  public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
  public static final int USERDEPARTMENTFK = AttributesEnum.UserDepartmentFk.index();
  public static final int DISPLAYARCDOCNAME = AttributesEnum.DisplayArcDocName.index();
  public static final int DISPLAYARCDOCDESC = AttributesEnum.DisplayArcDocDesc.index();
  public static final int CRSOUTGOINGARCHIVETL = AttributesEnum.CrsOutgoingArchiveTl.index();
  public static final int CRSOUTGOINGDOCUMENTS = AttributesEnum.CrsOutgoingDocuments.index();
  public static final int CRSOUTGOINGDOCPREPARATION = AttributesEnum.CrsOutgoingDocPreparation.index();

  /**
   * This is the default constructor (do not remove).
   */
  public CrsOutgoingArchiveImpl()
  {
  }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    return EntityDefImpl.findDefObject("crs.model.eo.CrsOutgoingArchive");
  }

  /**
   * Gets the attribute value for OutgoingArchivePk, using the alias name OutgoingArchivePk.
   * @return the value of OutgoingArchivePk
   */
  public BigDecimal getOutgoingArchivePk()
  {
    return (BigDecimal) getAttributeInternal(OUTGOINGARCHIVEPK);
  }

  /**
   * Sets <code>value</code> as the attribute value for OutgoingArchivePk.
   * @param value value to set the OutgoingArchivePk
   */
  public void setOutgoingArchivePk(BigDecimal value)
  {
    setAttributeInternal(OUTGOINGARCHIVEPK, value);
  }

  /**
   * Gets the attribute value for ArcFilePath, using the alias name ArcFilePath.
   * @return the value of ArcFilePath
   */
  public String getArcFilePath()
  {
    return (String) getAttributeInternal(ARCFILEPATH);
  }

  /**
   * Sets <code>value</code> as the attribute value for ArcFilePath.
   * @param value value to set the ArcFilePath
   */
  public void setArcFilePath(String value)
  {
    setAttributeInternal(ARCFILEPATH, value);
  }

  /**
   * Gets the attribute value for OutgoingDocumentsFk, using the alias name OutgoingDocumentsFk.
   * @return the value of OutgoingDocumentsFk
   */
  public BigDecimal getOutgoingDocumentsFk()
  {
    return (BigDecimal) getAttributeInternal(OUTGOINGDOCUMENTSFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for OutgoingDocumentsFk.
   * @param value value to set the OutgoingDocumentsFk
   */
  public void setOutgoingDocumentsFk(BigDecimal value)
  {
    setAttributeInternal(OUTGOINGDOCUMENTSFK, value);
  }

  /**
   * Gets the attribute value for OutgoingDocPreparationFk, using the alias name OutgoingDocPreparationFk.
   * @return the value of OutgoingDocPreparationFk
   */
  public BigDecimal getOutgoingDocPreparationFk()
  {
    return (BigDecimal) getAttributeInternal(OUTGOINGDOCPREPARATIONFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for OutgoingDocPreparationFk.
   * @param value value to set the OutgoingDocPreparationFk
   */
  public void setOutgoingDocPreparationFk(BigDecimal value)
  {
    setAttributeInternal(OUTGOINGDOCPREPARATIONFK, value);
  }

  /**
   * Gets the attribute value for SecurityLevelFk, using the alias name SecurityLevelFk.
   * @return the value of SecurityLevelFk
   */
  public BigDecimal getSecurityLevelFk()
  {
    return (BigDecimal) getAttributeInternal(SECURITYLEVELFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for SecurityLevelFk.
   * @param value value to set the SecurityLevelFk
   */
  public void setSecurityLevelFk(BigDecimal value)
  {
    setAttributeInternal(SECURITYLEVELFK, value);
  }

  /**
   * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
   * @return the value of CreatedBy
   */
  public BigDecimal getCreatedBy()
  {
    return (BigDecimal) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreatedBy.
   * @param value value to set the CreatedBy
   */
  public void setCreatedBy(BigDecimal value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CreationDate, using the alias name CreationDate.
   * @return the value of CreationDate
   */
  public Timestamp getCreationDate()
  {
    return (Timestamp) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreationDate.
   * @param value value to set the CreationDate
   */
  public void setCreationDate(Timestamp value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for ModifiedBy, using the alias name ModifiedBy.
   * @return the value of ModifiedBy
   */
  public BigDecimal getModifiedBy()
  {
    return (BigDecimal) getAttributeInternal(MODIFIEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedBy.
   * @param value value to set the ModifiedBy
   */
  public void setModifiedBy(BigDecimal value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
   * @return the value of ModifiedDate
   */
  public Timestamp getModifiedDate()
  {
    return (Timestamp) getAttributeInternal(MODIFIEDDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedDate.
   * @param value value to set the ModifiedDate
   */
  public void setModifiedDate(Timestamp value)
  {
    setAttributeInternal(MODIFIEDDATE, value);
  }

  /**
   * Gets the attribute value for UserDepartmentFk, using the alias name UserDepartmentFk.
   * @return the value of UserDepartmentFk
   */
  public BigDecimal getUserDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(USERDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for UserDepartmentFk.
   * @param value value to set the UserDepartmentFk
   */
  public void setUserDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(USERDEPARTMENTFK, value);
  }

  /**
   * Gets the attribute value for DisplayArcDocName, using the alias name DisplayArcDocName.
   * @return the value of DisplayArcDocName
   */
  public String getDisplayArcDocName()
  {
    return (String) getAttributeInternal(DISPLAYARCDOCNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for DisplayArcDocName.
   * @param value value to set the DisplayArcDocName
   */
  public void setDisplayArcDocName(String value)
  {
    setAttributeInternal(DISPLAYARCDOCNAME, value);
  }

  /**
   * Gets the attribute value for DisplayArcDocDesc, using the alias name DisplayArcDocDesc.
   * @return the value of DisplayArcDocDesc
   */
  public String getDisplayArcDocDesc()
  {
    return (String) getAttributeInternal(DISPLAYARCDOCDESC);
  }

  /**
   * Sets <code>value</code> as the attribute value for DisplayArcDocDesc.
   * @param value value to set the DisplayArcDocDesc
   */
  public void setDisplayArcDocDesc(String value)
  {
    setAttributeInternal(DISPLAYARCDOCDESC, value);
  }

  /**
   * @return the associated entity oracle.jbo.RowIterator.
   */
  public RowIterator getCrsOutgoingArchiveTl()
  {
    return (RowIterator) getAttributeInternal(CRSOUTGOINGARCHIVETL);
  }

  /**
   * @return the associated entity CrsOutgoingDocumentsImpl.
   */
  public CrsOutgoingDocumentsImpl getCrsOutgoingDocuments()
  {
    return (CrsOutgoingDocumentsImpl) getAttributeInternal(CRSOUTGOINGDOCUMENTS);
  }

  /**
   * Sets <code>value</code> as the associated entity CrsOutgoingDocumentsImpl.
   */
  public void setCrsOutgoingDocuments(CrsOutgoingDocumentsImpl value)
  {
    setAttributeInternal(CRSOUTGOINGDOCUMENTS, value);
  }

  /**
   * @return the associated entity CrsOutgoingDocPreparationImpl.
   */
  public CrsOutgoingDocPreparationImpl getCrsOutgoingDocPreparation()
  {
    return (CrsOutgoingDocPreparationImpl) getAttributeInternal(CRSOUTGOINGDOCPREPARATION);
  }

  /**
   * Sets <code>value</code> as the associated entity CrsOutgoingDocPreparationImpl.
   */
  public void setCrsOutgoingDocPreparation(CrsOutgoingDocPreparationImpl value)
  {
    setAttributeInternal(CRSOUTGOINGDOCPREPARATION, value);
  }

  /**
   * @param outgoingArchivePk key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(BigDecimal outgoingArchivePk)
  {
    return new Key(new Object[] { outgoingArchivePk });
  }

  protected void doDML(int operation, oracle.jbo.server.TransactionEvent e){
    
    super.doDML(operation, e);

    if (operation == DML_INSERT){
      BigDecimal outgoingArchivePk = gen.common.GenLib.getPrimaryKeyValue(getDBTransaction(), "CRS_OUTGOING_ARCHIVE_SEQ");
      setOutgoingArchivePk(outgoingArchivePk);
      insertIntoCrsOutgoingArchiveTl();
    }
  }

  private void insertIntoCrsOutgoingArchiveTl(){
    oracle.jbo.server.EntityDefImpl crsOutgoingArchiveTlDef = CrsOutgoingArchiveTlImpl.getDefinitionObject();
    List<Integer> activeLanguages = GenLib.getActiveDataLanguages(getDBTransaction());
    for (Integer languageId : activeLanguages){
      CrsOutgoingArchiveTlImpl crsOutgoingArchiveTl = (CrsOutgoingArchiveTlImpl) crsOutgoingArchiveTlDef.
                                                                      createInstance2(getDBTransaction(), null);
      crsOutgoingArchiveTl.setLanguagesFk(BigDecimal.valueOf(languageId));
      crsOutgoingArchiveTl.setArcDocName(getDisplayArcDocName());
      crsOutgoingArchiveTl.setArcDocDesc(getDisplayArcDocDesc());
      crsOutgoingArchiveTl.setOutgoingArchiveFk(getOutgoingArchivePk());
    }
  }
  
  public void remove(){
    gen.common.GenLib.removeTranlationRows(getCrsOutgoingArchiveTl());
    super.remove();
  }
}