package crs.model.eo;

import java.math.BigDecimal;
import java.sql.Timestamp;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Apr 01 13:34:25 GMT+03:00 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CrsOutgoingArchiveTlImpl
  extends AuditEntityImpl
{
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
   */
  protected enum AttributesEnum
  {
    OutgoingArchiveTlPk,
    ArcDocName,
    ArcDocDesc,
    LanguagesFk,
    OutgoingArchiveFk,
    CreatedBy,
    CreationDate,
    ModifiedBy,
    ModifiedDate,
    UserDepartmentFk,
    CrsOutgoingArchive;
    private static AttributesEnum[] vals = null;
    private static final int firstIndex = 0;

    protected int index()
    {
      return AttributesEnum.firstIndex() + ordinal();
    }

    protected static final int firstIndex()
    {
      return firstIndex;
    }

    protected static int count()
    {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    protected static final AttributesEnum[] staticValues()
    {
      if (vals == null)
      {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }

  public static final int OUTGOINGARCHIVETLPK = AttributesEnum.OutgoingArchiveTlPk.index();
  public static final int ARCDOCNAME = AttributesEnum.ArcDocName.index();
  public static final int ARCDOCDESC = AttributesEnum.ArcDocDesc.index();
  public static final int LANGUAGESFK = AttributesEnum.LanguagesFk.index();
  public static final int OUTGOINGARCHIVEFK = AttributesEnum.OutgoingArchiveFk.index();
  public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
  public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
  public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
  public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
  public static final int USERDEPARTMENTFK = AttributesEnum.UserDepartmentFk.index();
  public static final int CRSOUTGOINGARCHIVE = AttributesEnum.CrsOutgoingArchive.index();

  /**
   * This is the default constructor (do not remove).
   */
  public CrsOutgoingArchiveTlImpl()
  {
  }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject()
  {
    return EntityDefImpl.findDefObject("crs.model.eo.CrsOutgoingArchiveTl");
  }

  /**
   * Gets the attribute value for OutgoingArchiveTlPk, using the alias name OutgoingArchiveTlPk.
   * @return the value of OutgoingArchiveTlPk
   */
  public BigDecimal getOutgoingArchiveTlPk()
  {
    return (BigDecimal) getAttributeInternal(OUTGOINGARCHIVETLPK);
  }

  /**
   * Sets <code>value</code> as the attribute value for OutgoingArchiveTlPk.
   * @param value value to set the OutgoingArchiveTlPk
   */
  public void setOutgoingArchiveTlPk(BigDecimal value)
  {
    setAttributeInternal(OUTGOINGARCHIVETLPK, value);
  }

  /**
   * Gets the attribute value for ArcDocName, using the alias name ArcDocName.
   * @return the value of ArcDocName
   */
  public String getArcDocName()
  {
    return (String) getAttributeInternal(ARCDOCNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for ArcDocName.
   * @param value value to set the ArcDocName
   */
  public void setArcDocName(String value)
  {
    setAttributeInternal(ARCDOCNAME, value);
  }

  /**
   * Gets the attribute value for ArcDocDesc, using the alias name ArcDocDesc.
   * @return the value of ArcDocDesc
   */
  public String getArcDocDesc()
  {
    return (String) getAttributeInternal(ARCDOCDESC);
  }

  /**
   * Sets <code>value</code> as the attribute value for ArcDocDesc.
   * @param value value to set the ArcDocDesc
   */
  public void setArcDocDesc(String value)
  {
    setAttributeInternal(ARCDOCDESC, value);
  }

  /**
   * Gets the attribute value for LanguagesFk, using the alias name LanguagesFk.
   * @return the value of LanguagesFk
   */
  public BigDecimal getLanguagesFk()
  {
    return (BigDecimal) getAttributeInternal(LANGUAGESFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for LanguagesFk.
   * @param value value to set the LanguagesFk
   */
  public void setLanguagesFk(BigDecimal value)
  {
    setAttributeInternal(LANGUAGESFK, value);
  }

  /**
   * Gets the attribute value for OutgoingArchiveFk, using the alias name OutgoingArchiveFk.
   * @return the value of OutgoingArchiveFk
   */
  public BigDecimal getOutgoingArchiveFk()
  {
    return (BigDecimal) getAttributeInternal(OUTGOINGARCHIVEFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for OutgoingArchiveFk.
   * @param value value to set the OutgoingArchiveFk
   */
  public void setOutgoingArchiveFk(BigDecimal value)
  {
    setAttributeInternal(OUTGOINGARCHIVEFK, value);
  }

  /**
   * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
   * @return the value of CreatedBy
   */
  public BigDecimal getCreatedBy()
  {
    return (BigDecimal) getAttributeInternal(CREATEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreatedBy.
   * @param value value to set the CreatedBy
   */
  public void setCreatedBy(BigDecimal value)
  {
    setAttributeInternal(CREATEDBY, value);
  }

  /**
   * Gets the attribute value for CreationDate, using the alias name CreationDate.
   * @return the value of CreationDate
   */
  public Timestamp getCreationDate()
  {
    return (Timestamp) getAttributeInternal(CREATIONDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for CreationDate.
   * @param value value to set the CreationDate
   */
  public void setCreationDate(Timestamp value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }

  /**
   * Gets the attribute value for ModifiedBy, using the alias name ModifiedBy.
   * @return the value of ModifiedBy
   */
  public BigDecimal getModifiedBy()
  {
    return (BigDecimal) getAttributeInternal(MODIFIEDBY);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedBy.
   * @param value value to set the ModifiedBy
   */
  public void setModifiedBy(BigDecimal value)
  {
    setAttributeInternal(MODIFIEDBY, value);
  }

  /**
   * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
   * @return the value of ModifiedDate
   */
  public Timestamp getModifiedDate()
  {
    return (Timestamp) getAttributeInternal(MODIFIEDDATE);
  }

  /**
   * Sets <code>value</code> as the attribute value for ModifiedDate.
   * @param value value to set the ModifiedDate
   */
  public void setModifiedDate(Timestamp value)
  {
    setAttributeInternal(MODIFIEDDATE, value);
  }

  /**
   * Gets the attribute value for UserDepartmentFk, using the alias name UserDepartmentFk.
   * @return the value of UserDepartmentFk
   */
  public BigDecimal getUserDepartmentFk()
  {
    return (BigDecimal) getAttributeInternal(USERDEPARTMENTFK);
  }

  /**
   * Sets <code>value</code> as the attribute value for UserDepartmentFk.
   * @param value value to set the UserDepartmentFk
   */
  public void setUserDepartmentFk(BigDecimal value)
  {
    setAttributeInternal(USERDEPARTMENTFK, value);
  }

  /**
   * @return the associated entity CrsOutgoingArchiveImpl.
   */
  public CrsOutgoingArchiveImpl getCrsOutgoingArchive()
  {
    return (CrsOutgoingArchiveImpl) getAttributeInternal(CRSOUTGOINGARCHIVE);
  }

  /**
   * Sets <code>value</code> as the associated entity CrsOutgoingArchiveImpl.
   */
  public void setCrsOutgoingArchive(CrsOutgoingArchiveImpl value)
  {
    setAttributeInternal(CRSOUTGOINGARCHIVE, value);
  }

  /**
   * @param outgoingArchiveTlPk key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(BigDecimal outgoingArchiveTlPk)
  {
    return new Key(new Object[] { outgoingArchiveTlPk });
  }

  protected void doDML(int operation, oracle.jbo.server.TransactionEvent e)
  {
    
    super.doDML(operation, e);

    if (operation == DML_INSERT){
      BigDecimal outgoingArchiveTlPk = gen.common.GenLib.getPrimaryKeyValue(getDBTransaction(), "CRS_OUTGOING_ARCHIVE_TL_SEQ");
      setOutgoingArchiveTlPk(outgoingArchiveTlPk);
    }
  }
}